import { MarketService, type MarketPrice } from '@/lib/kisan/market';
import { getUserLocationData } from '@/lib/kisan/geolocation';

export type Language = 'en' | 'hi' | string;

export interface LocationData {
  city: string;
  state?: string;
  country?: string;
  lat?: number;
  lng?: number;
}

export function getCurrentLanguage(): Language {
  try {
    if (typeof window !== 'undefined') {
      const store = require('@/lib/store');
      const state = store.useAppStore.getState();
      return (state.userProfile?.language as Language) || 'en';
    }
  } catch (e) {
    // ignore
  }
  return 'en';
}

const KISAN_TRANSLATIONS: Record<string, Record<string, string>> = {
hi: {
    'crops.marketPrices': 'मंडी भाव',
    'crops.searchCrops': 'फसल खोजें...',
    'market.highpriceincrease': 'के लिए उच्च मूल्य वृद्धि',
    'market.pricesdecline': 'की कीमतें घट रही हैं',
    'market.stableprices': 'के लिए बाजार स्थिर है',
    'crops.shopDetails': 'दुकान का विवरण',
    'crops.getDirections': 'दिशा-निर्देश प्राप्त करें',
    'crops.callNow': 'कॉल करें',
    'crops.availableItems': 'उपलब्ध उत्पाद',
    'crops.distance': 'दूरी',
    'inputFinder.title': 'इनपुट खोजक',
    'inputFinder.description': 'आसपास की दुकानें खोजें',
    'inputFinder.searchPlaceholder': 'इनपुट खोजें...',
    'inputFinder.allShops': 'सभी दुकानें',
    'inputFinder.pmkskCenters': 'पीएमकेएसके केंद्र',
    'inputFinder.privateShops': 'निजी दुकानें',
    'inputFinder.kmAway': 'किमी दूर',
    'inputFinder.currentPrices': 'वर्तमान मूल्य',
    'inputFinder.callNow': 'कॉल करें',
    'inputFinder.call': 'कॉल करें',
    'inputFinder.getDirections': 'दिशा',
    'dashboard.cropDiagnosis.title': 'फसल निदान (AI)',
    'dashboard.cropDiagnosis.description': 'बीमार फसल की फोटो लें...',
    'dashboard.cropDiagnosis.imageTooLarge': 'छवि बहुत बड़ी है। कृपया 5MB से छोटी छवि का उपयोग करें।',
    'dashboard.cropDiagnosis.invalidFileType': 'कृपया एक मान्य छवि फ़ाइल अपलोड करें।',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'छवि का विश्लेषण करने में विफल। कृपया सुनिश्चित करें कि फ़ोटो स्पष्ट है।',
    'dashboard.cropDiagnosis.note': 'AI विश्लेषण 100% सटीक नहीं हो सकता है',
    'diagnosis.takePhoto': 'फोटो खींचें',
    'diagnosis.uploadFromGallery': 'गैलरी से चुनें',
    'diagnosis.tipsTitle': 'अच्छी तस्वीरों के लिए सुझाव',
    'diagnosis.tip1': 'अच्छी रोशनी सुनिश्चित करें',
    'diagnosis.tip2': 'संक्रमित हिस्से पर ध्यान केंद्रित करें',
    'diagnosis.tip3': 'पत्ते को स्थिर रखें',
    'diagnosis.tip4': 'परछाई से बचें',
    'diagnosis.cropImageAlt': 'फसल की छवि',
    'diagnosis.remove': 'हटाएं',
    'diagnosis.analyzeWithAI': 'AI से विश्लेषण करें',
    'diagnosis.retrying': 'पुनः प्रयास किया जा रहा है',
    'diagnosis.analyzing': 'फसल छवि का विश्लेषण हो रहा है...',
    'diagnosis.analyzingSubtext': 'हम रोग का पता लगाने के लिए उन्नत विजन AI का उपयोग कर रहे हैं।',
    'diagnosis.analysisComplete': 'विश्लेषण पूर्ण',
    'diagnosis.laymanHealthy': 'बहुत बढ़िया! आपकी {crop_name} की फसल स्वस्थ दिख रही है। इसे ऐसा ही बनाए रखने के लिए, उचित सिंचाई सुनिश्चित करें और भविष्य में किसी भी समस्या के लिए निगरानी रखें।',
    'diagnosis.laymanDiseased': 'ऐसा लग रहा है कि आपकी {crop_name} की फसल {disease_name} से पीड़ित है। कुछ सामान्य लक्षण जो आपने देखे होंगे वे हैं {symptoms}। इसके उपचार के लिए, आप जैविक समाधान जैसे {treatment_organic} या रासायनिक विकल्प जैसे {treatment_chemical} का उपयोग कर सकते हैं। भविष्य में बचाव के लिए, {prevention}।',
    'cropRecommendation.title': 'फसल सलाहकार',
    'cropRecommendation.description': 'अपनी मिट्टी और मौसम के आधार पर सही फसल चुनें',
    'cropRecommendation.loamy': 'दोमट मिट्टी',
    'cropRecommendation.clay': 'चिकनी मिट्टी',
    'cropRecommendation.sandy': 'बलुई मिट्टी',
    'cropRecommendation.silt': 'गाद मिट्टी',
    'cropRecommendation.redSoil': 'लाल मिट्टी',
    'cropRecommendation.blackSoil': 'काली मिट्टी',
    'cropRecommendation.alluvial': 'जलोढ़ मिट्टी',
    'cropRecommendation.location': 'स्थान',
    'cropRecommendation.locationPlaceholder': 'शहर या क्षेत्र दर्ज करें',
    'cropRecommendation.season': 'मौसम',
    'cropRecommendation.kharif': 'खरीफ',
    'cropRecommendation.rabi': 'रबी',
    'cropRecommendation.zaid': 'ज़ैद',
    'cropRecommendation.waterAvailability': 'पानी की उपलब्धता',
    'cropRecommendation.abundant': 'पर्याप्त',
    'cropRecommendation.moderate': 'मध्यम',
    'cropRecommendation.limited': 'सीमित',
    'cropRecommendation.rainDependent': 'वर्षा आधारित',
    'cropRecommendation.fillRequiredFields': 'कृपया सभी आवश्यक फ़ील्ड भरें।',
    'cropRecommendation.generateRecommendations': 'सुझाव उत्पन्न करें',
    'cropRecommendation.analyzing': 'विश्लेषण हो रहा है...',
    'cropRecommendation.gettingRecommendations': 'हम आपके क्षेत्र के लिए सर्वोत्तम फसल खोज रहे हैं।',
    'cropRecommendation.recommendationsReady': 'सुझाव तैयार हैं!',
    'cropRecommendation.yieldLabel': 'अनुमानित उपज:',
    'cropRecommendation.waterLabel': 'पानी की आवश्यकता:',
    'cropRecommendation.marketLabel': 'बाज़ार मूल्य:',
    'cropRecommendation.durationLabel': 'अवधि:',
    'cropRecommendation.conditionsLabel': 'आवश्यक शर्तें:',
    'cropRecommendation.investmentLabel': 'निवेश विवरण:',
    'cropRecommendation.newSearch': 'नई खोज',
    'cropRecommendation.shareTitle': 'फसल सुझाव रिकॉर्ड',
    'cropRecommendation.share': 'साझा करें',
    'cropRecommendation.errorMessage': 'सुझाव प्राप्त करने में त्रुटि',
    'cropRecommendation.soilType': 'मिट्टी का प्रकार',
  },
  en: {
    'crops.marketPrices': 'Live Mandi Prices',
    'crops.searchCrops': 'Search Crops...',
    'market.highpriceincrease': 'High price increase for',
    'market.pricesdecline': 'Prices are declining for',
    'market.stableprices': 'Market is stable for',
    'crops.shopDetails': 'Shop Details',
    'crops.getDirections': 'Get Directions',
    'crops.callNow': 'Call Now',
    'crops.availableItems': 'Available Items',
    'crops.distance': 'Distance',
    'inputFinder.title': 'Input Finder',
    'inputFinder.description': 'Find shops nearby',
    'inputFinder.searchPlaceholder': 'Search inputs...',
    'inputFinder.allShops': 'All Shops',
    'inputFinder.pmkskCenters': 'PMKSK Centers',
    'inputFinder.privateShops': 'Private Shops',
    'inputFinder.kmAway': 'km away',
    'inputFinder.currentPrices': 'Current Prices',
    'inputFinder.callNow': 'Call Now',
    'inputFinder.call': 'Call',
    'inputFinder.getDirections': 'Directions',
    'dashboard.cropDiagnosis.title': 'Crop Diagnosis (AI)',
    'dashboard.cropDiagnosis.description': 'Take a photo of your diseased crop...',
    'dashboard.cropDiagnosis.imageTooLarge': 'Image too large. Please use an image smaller than 5MB.',
    'dashboard.cropDiagnosis.invalidFileType': 'Please upload a valid image file.',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'Failed to analyze image. Please ensure the photo is clear.',
    'dashboard.cropDiagnosis.note': 'AI analysis may not be 100% accurate',
    'diagnosis.takePhoto': 'Take Photo',
    'diagnosis.uploadFromGallery': 'Choose from Gallery',
    'diagnosis.tipsTitle': 'Tips for good photos',
    'diagnosis.tip1': 'Ensure good lighting',
    'diagnosis.tip2': 'Focus on the infected area',
    'diagnosis.tip3': 'Keep the leaf steady',
    'diagnosis.tip4': 'Avoid shadows',
    'diagnosis.cropImageAlt': 'Crop Image',
    'diagnosis.remove': 'Remove',
    'diagnosis.analyzeWithAI': 'Analyze with AI',
    'diagnosis.retrying': 'Retrying',
    'diagnosis.analyzing': 'Analyzing Crop Image...',
    'diagnosis.analyzingSubtext': 'Using advanced Vision AI to detect anomalies.',
    'diagnosis.analysisComplete': 'Analysis Complete',
    'diagnosis.laymanHealthy': 'Great news! Your {crop_name} crop looks healthy. To keep it this way, ensure proper watering and monitor for any future issues.',
    'diagnosis.laymanDiseased': 'It looks like your {crop_name} is suffering from {disease_name}. Some common symptoms you might have noticed are {symptoms}. To treat this, you can use organic solutions like {treatment_organic} or chemical options like {treatment_chemical}. For prevention in the future, {prevention}.',
    'cropRecommendation.title': 'Crop Advisor',
    'cropRecommendation.description': 'Get AI recommendations based on your soil and weather',
    'cropRecommendation.loamy': 'Loamy',
    'cropRecommendation.clay': 'Clay',
    'cropRecommendation.sandy': 'Sandy',
    'cropRecommendation.silt': 'Silt',
    'cropRecommendation.redSoil': 'Red Soil',
    'cropRecommendation.blackSoil': 'Black Soil',
    'cropRecommendation.alluvial': 'Alluvial',
    'cropRecommendation.location': 'Location',
    'cropRecommendation.locationPlaceholder': 'Enter city or region',
    'cropRecommendation.season': 'Season',
    'cropRecommendation.kharif': 'Kharif',
    'cropRecommendation.rabi': 'Rabi',
    'cropRecommendation.zaid': 'Zaid',
    'cropRecommendation.waterAvailability': 'Water Availability',
    'cropRecommendation.abundant': 'Abundant',
    'cropRecommendation.moderate': 'Moderate',
    'cropRecommendation.limited': 'Limited',
    'cropRecommendation.rainDependent': 'Rain Dependent',
    'cropRecommendation.fillRequiredFields': 'Please fill all required fields.',
    'cropRecommendation.generateRecommendations': 'Generate Recommendations',
    'cropRecommendation.analyzing': 'Analyzing...',
    'cropRecommendation.gettingRecommendations': 'Finding the best crops for your region...',
    'cropRecommendation.recommendationsReady': 'Recommendations Ready!',
    'cropRecommendation.yieldLabel': 'Expected Yield:',
    'cropRecommendation.waterLabel': 'Water Req:',
    'cropRecommendation.marketLabel': 'Market Price:',
    'cropRecommendation.durationLabel': 'Duration:',
    'cropRecommendation.conditionsLabel': 'Conditions:',
    'cropRecommendation.investmentLabel': 'Investment:',
    'cropRecommendation.newSearch': 'New Search',
    'cropRecommendation.shareTitle': 'Crop Recommendations',
    'cropRecommendation.share': 'Share',
    'cropRecommendation.errorMessage': 'Error generating recommendation',
    'cropRecommendation.soilType': 'Soil Type',
  },
  bn: {
    'crops.marketPrices': 'লাইভ মান্ডি দাম',
    'crops.searchCrops': 'ফসল অনুসন্ধান করুন...',
    'market.highpriceincrease': 'দাম বৃদ্ধির জন্য উচ্চ মূল্য বৃদ্ধি',
    'market.pricesdecline': 'দাম কমছে',
    'market.stableprices': 'এর জন্য বাজার স্থিতিশীল',
    'crops.shopDetails': 'কেনাকাটার বিবরণ',
    'crops.getDirections': 'দিকনির্দেশনা পান',
    'crops.callNow': 'এখনই কল করুন',
    'crops.availableItems': 'উপলভ্য আইটেম',
    'crops.distance': 'দূরত্ব',
    'inputFinder.title': 'ইনপুট ফাইন্ডার',
    'inputFinder.description': 'কাছাকাছি দোকানগুলি সন্ধান করুন',
    'inputFinder.searchPlaceholder': 'ইনপুটগুলি অনুসন্ধান করুন...',
    'inputFinder.allShops': 'সকল দোকান',
    'inputFinder.pmkskCenters': 'পিএমকেএসকে কেন্দ্র',
    'inputFinder.privateShops': 'ব্যক্তিগত দোকান',
    'inputFinder.kmAway': 'দূরে কিমি',
    'inputFinder.currentPrices': 'বর্তমান মূল্য',
    'inputFinder.callNow': 'এখনই কল করুন',
    'inputFinder.call': 'কল করুন',
    'inputFinder.getDirections': 'দিকনির্দেশনা',
    'dashboard.cropDiagnosis.title': 'ফসল নির্ণয় (এআই)',
    'dashboard.cropDiagnosis.description': 'আপনার রোগাক্রান্ত ফসলের ছবি তুলুন...',
    'dashboard.cropDiagnosis.imageTooLarge': 'চিত্রটি অত্যন্ত বড়। দয়া করে 5MB এর চেয়ে ছোট একটি চিত্র ব্যবহার করুন।',
    'dashboard.cropDiagnosis.invalidFileType': 'অনুগ্রহ করে একটি বৈধ চিত্র ফাইল আপলোড করুন।',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'চিত্র বিশ্লেষণ করতে ব্যর্থ হয়েছে। দয়া করে নিশ্চিত করুন যে ছবিটি পরিষ্কার আছে।',
    'dashboard.cropDiagnosis.note': 'এআই বিশ্লেষণ 100% সঠিক নাও হতে পারে',
    'diagnosis.takePhoto': 'ছবি তুলুন',
    'diagnosis.uploadFromGallery': 'গ্যালারি থেকে চয়ন করুন',
    'diagnosis.tipsTitle': 'ভালো ছবির টিপস',
    'diagnosis.tip1': 'ভালো আলো নিশ্চিত করুন',
    'diagnosis.tip2': 'সংক্রামিত এলাকার দিকে নজর দিন',
    'diagnosis.tip3': 'পাতা স্থির রাখুন',
    'diagnosis.tip4': 'ছায়া এড়িয়ে চলুন',
    'diagnosis.cropImageAlt': 'ক্রপ ইমেজ',
    'diagnosis.remove': 'অপসারণ করুন',
    'diagnosis.analyzeWithAI': 'এআই দিয়ে বিশ্লেষণ করুন',
    'diagnosis.retrying': 'পুনরায় চেষ্টা করা',
    'diagnosis.analyzing': 'ক্রপ চিত্র বিশ্লেষণ করা হচ্ছে...',
    'diagnosis.analyzingSubtext': 'অসঙ্গতিগুলি শনাক্ত করতে উন্নত Vision AI ব্যবহার করা।',
    'diagnosis.analysisComplete': 'বিশ্লেষণ সম্পূর্ণ',
    'diagnosis.laymanHealthy': 'দারুণ খবর! আপনার {crop_name} টি ফসল স্বাস্থ্যকর দেখাচ্ছে। এটি এভাবে রাখতে, সঠিক জল নিশ্চিত করুন এবং ভবিষ্যতের কোনও সমস্যার জন্য পর্যবেক্ষণ করুন।',
    'diagnosis.laymanDiseased': 'দেখে মনে হচ্ছে আপনার {crop_name} {disease_name} এ ভুগছেন। কিছু সাধারণ লক্ষণ যা আপনি লক্ষ্য করতে পারেন তা হ\'ল {লক্ষণ}। এটির চিকিত্সার জন্য, আপনি {treatment_organic} এর মতো জৈব দ্রবণ বা {treatment_chemical} এর মতো রাসায়নিক বিকল্পগুলি ব্যবহার করতে পারেন। ভবিষ্যতে প্রতিরোধের জন্য, {প্রতিরোধ}।',
    'cropRecommendation.title': 'ফসল উপদেষ্টা',
    'cropRecommendation.description': 'আপনার মাটি ও আবহাওয়ার ভিত্তিতে AI সুপারিশগুলি পান',
    'cropRecommendation.loamy': 'লোমি',
    'cropRecommendation.clay': 'কাদামাটি',
    'cropRecommendation.sandy': 'স্যান্ডি',
    'cropRecommendation.silt': 'পলি',
    'cropRecommendation.redSoil': 'লাল মাটি',
    'cropRecommendation.blackSoil': 'কালো মাটি',
    'cropRecommendation.alluvial': 'পলি',
    'cropRecommendation.location': 'অবস্থান',
    'cropRecommendation.locationPlaceholder': 'শহর বা অঞ্চল লিখুন',
    'cropRecommendation.season': 'ঋতু',
    'cropRecommendation.kharif': 'খরিফ',
    'cropRecommendation.rabi': 'রবি',
    'cropRecommendation.zaid': 'জায়েদ',
    'cropRecommendation.waterAvailability': 'জলের প্রাপ্যতা',
    'cropRecommendation.abundant': 'প্রচুর পরিমাণে',
    'cropRecommendation.moderate': 'মাঝারি',
    'cropRecommendation.limited': 'লিমিটেড',
    'cropRecommendation.rainDependent': 'বৃষ্টি নির্ভর',
    'cropRecommendation.fillRequiredFields': 'দয়া করে সমস্ত প্রয়োজনীয় ক্ষেত্র পূরণ করুন।',
    'cropRecommendation.generateRecommendations': 'সুপারিশ তৈরি করুন',
    'cropRecommendation.analyzing': 'বিশ্লেষণ করা হচ্ছে...',
    'cropRecommendation.gettingRecommendations': 'আপনার অঞ্চলের জন্য সেরা ফসল সন্ধান করা...',
    'cropRecommendation.recommendationsReady': 'সুপারিশ প্রস্তুত!',
    'cropRecommendation.yieldLabel': 'প্রত্যাশিত ফলন:',
    'cropRecommendation.waterLabel': 'ওয়াটার রিকিউ:',
    'cropRecommendation.marketLabel': 'বাজার মূল্য:',
    'cropRecommendation.durationLabel': 'সময়কাল:',
    'cropRecommendation.conditionsLabel': 'শর্তাবলী:',
    'cropRecommendation.investmentLabel': 'বিনিয়োগ:',
    'cropRecommendation.newSearch': 'নতুন অনুসন্ধান',
    'cropRecommendation.shareTitle': 'ফসলের সুপারিশ',
    'cropRecommendation.share': 'শেয়ার করুন',
    'cropRecommendation.errorMessage': 'সুপারিশ তৈরি করতে ত্রুটি',
    'cropRecommendation.soilType': 'মাটির ধরন',
  },
  te: {
    'crops.marketPrices': 'లైవ్ మండి ధరలు',
    'crops.searchCrops': 'పంటలను శోధించండి...',
    'market.highpriceincrease': 'అధిక ధరల పెరుగుదల',
    'market.pricesdecline': 'ధరలు తగ్గుముఖం పట్టాయి.',
    'market.stableprices': 'మార్కెట్ నిలకడగా ఉంది',
    'crops.shopDetails': 'షాప్ వివరాలు',
    'crops.getDirections': 'దిశలను పొందండి',
    'crops.callNow': 'ఇప్పుడే కాల్ చేయండి',
    'crops.availableItems': 'అందుబాటులో ఉన్న అంశాలు',
    'crops.distance': 'దూరం',
    'inputFinder.title': 'ఇన్ పుట్ ఫైండర్',
    'inputFinder.description': 'దగ్గరల్లో ఉన్న దుకాణాలను కనుగొనండి',
    'inputFinder.searchPlaceholder': 'ఇన్ పుట్ లను శోధించండి...',
    'inputFinder.allShops': 'అన్ని దుకాణాలు',
    'inputFinder.pmkskCenters': 'పీఎంకేఎస్కే కేంద్రాలు',
    'inputFinder.privateShops': 'ప్రైవేట్ షాపులు',
    'inputFinder.kmAway': 'కి.మీ దూరంలో',
    'inputFinder.currentPrices': 'ప్రస్తుత ధరలు',
    'inputFinder.callNow': 'ఇప్పుడే కాల్ చేయండి',
    'inputFinder.call': 'కాల్ చేయండి',
    'inputFinder.getDirections': 'దిశలు',
    'dashboard.cropDiagnosis.title': 'పంట నిర్ధారణ (AI)',
    'dashboard.cropDiagnosis.description': 'మీ వ్యాధిగ్రస్త పంట యొక్క ఫోటో తీసుకోండి...',
    'dashboard.cropDiagnosis.imageTooLarge': 'చిత్రం చాలా పెద్దదిగా ఉంది. దయచేసి 5MB కంటే చిన్న ఇమేజ్ ఉపయోగించండి.',
    'dashboard.cropDiagnosis.invalidFileType': 'దయచేసి చెల్లుబాటు అయ్యే ఇమేజ్ ఫైలును అప్ లోడ్ చేయండి.',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'చిత్రాన్ని విశ్లేషించడం విఫలమైంది. ఫోటో స్పష్టంగా ఉందని దయచేసి ధృవీకరించుకోండి.',
    'dashboard.cropDiagnosis.note': 'AI విశ్లేషణ 100% ఖచ్చితమైనది కాకపోవచ్చు',
    'diagnosis.takePhoto': 'ఫోటో తీయండి',
    'diagnosis.uploadFromGallery': 'గ్యాలరీ నుండి ఎంచుకోండి',
    'diagnosis.tipsTitle': 'మంచి ఫోటోల కోసం చిట్కాలు',
    'diagnosis.tip1': 'మంచి లైటింగ్ ఉండేలా చూసుకోండి',
    'diagnosis.tip2': 'సోకిన ప్రాంతంపై దృష్టి సారించండి',
    'diagnosis.tip3': 'ఆకును నిలకడగా ఉంచండి.',
    'diagnosis.tip4': 'నీడలను నివారించండి',
    'diagnosis.cropImageAlt': 'కత్తిరించిన చిత్రం',
    'diagnosis.remove': 'తీసివేయి',
    'diagnosis.analyzeWithAI': 'AI తో విశ్లేషించండి',
    'diagnosis.retrying': 'తిరిగి ప్రయత్నించడం',
    'diagnosis.analyzing': 'కత్తిరింపు చిత్రాన్ని విశ్లేషిస్తోంది...',
    'diagnosis.analyzingSubtext': 'క్రమరాహిత్యాలను గుర్తించడానికి అధునాతన విజన్ AIని ఉపయోగించడం.',
    'diagnosis.analysisComplete': 'విశ్లేషణ పూర్తయింది',
    'diagnosis.laymanHealthy': 'గొప్ప వార్త! మీ {crop_name} పంట ఆరోగ్యంగా కనిపిస్తోంది. దీన్ని ఈ విధంగా ఉంచడానికి, సరైన నీరు త్రాగుటను నిర్ధారించుకోండి మరియు భవిష్యత్తులో ఏవైనా సమస్యల కోసం పర్యవేక్షించండి.',
    'diagnosis.laymanDiseased': 'మీరు {crop_name} {disease_name}తో బాధపడుతున్నట్లుగా కనిపిస్తోంది. మీరు గమనించిన కొన్ని సాధారణ లక్షణాలు {లక్షణాలు}. దీనికి చికిత్స చేయడం కొరకు, మీరు {treatment_organic} వంటి సేంద్రియ ద్రావణాలు లేదా {treatment_chemical} వంటి రసాయన ఆప్షన్ లను ఉపయోగించవచ్చు. భవిష్యత్తులో నివారణ కొరకు, {prevention}.',
    'cropRecommendation.title': 'పంట సలహాదారు',
    'cropRecommendation.description': 'మీ నేల మరియు వాతావరణం ఆధారంగా AI సిఫార్సులను పొందండి',
    'cropRecommendation.loamy': 'లోమీ',
    'cropRecommendation.clay': 'బంకమట్టి',
    'cropRecommendation.sandy': 'శాండీ',
    'cropRecommendation.silt': 'సిల్ట్',
    'cropRecommendation.redSoil': 'ఎర్ర మట్టి',
    'cropRecommendation.blackSoil': 'నల్ల మట్టి',
    'cropRecommendation.alluvial': 'ఒండ్రు',
    'cropRecommendation.location': 'స్థానం',
    'cropRecommendation.locationPlaceholder': 'నగరం లేదా ప్రాంతాన్ని నమోదు చేయండి',
    'cropRecommendation.season': 'సీజన్',
    'cropRecommendation.kharif': 'ఖరీఫ్',
    'cropRecommendation.rabi': 'రబీ',
    'cropRecommendation.zaid': 'జైద్',
    'cropRecommendation.waterAvailability': 'నీటి లభ్యత',
    'cropRecommendation.abundant': 'సమృద్ధిగా ఉంది',
    'cropRecommendation.moderate': 'మితమైన',
    'cropRecommendation.limited': 'లిమిటెడ్',
    'cropRecommendation.rainDependent': 'వర్షం ఆధారపడి ఉంటుంది',
    'cropRecommendation.fillRequiredFields': 'దయచేసి అవసరమైన అన్ని ఫీల్డ్ లను నింపండి.',
    'cropRecommendation.generateRecommendations': 'సిఫార్సులను జనరేట్ చేయండి',
    'cropRecommendation.analyzing': 'విశ్లేషిస్తోంది...',
    'cropRecommendation.gettingRecommendations': 'మీ ప్రాంతానికి అత్యుత్తమ పంటలను కనుగొనడం...',
    'cropRecommendation.recommendationsReady': 'సిఫార్సులు సిద్ధంగా ఉన్నాయి!',
    'cropRecommendation.yieldLabel': 'ఆశించిన దిగుబడి:',
    'cropRecommendation.waterLabel': 'వాటర్ రిక్యూ:',
    'cropRecommendation.marketLabel': 'మార్కెట్ ధర:',
    'cropRecommendation.durationLabel': 'వ్యవధి:',
    'cropRecommendation.conditionsLabel': 'షరతులు:',
    'cropRecommendation.investmentLabel': 'పెట్టుబడి:',
    'cropRecommendation.newSearch': 'కొత్త శోధన',
    'cropRecommendation.shareTitle': 'పంట సిఫార్సులు',
    'cropRecommendation.share': 'భాగస్వామ్యం',
    'cropRecommendation.errorMessage': 'సిఫార్సును రూపొందించడంలో దోషం',
    'cropRecommendation.soilType': 'నేల రకం',
  },
  mr: {
    'crops.marketPrices': 'थेट मंडईचे दर',
    'crops.searchCrops': 'पिके शोधा ...',
    'market.highpriceincrease': 'यासाठी दरवाढ',
    'market.pricesdecline': 'किंमती कमी होत आहेत.',
    'market.stableprices': 'बाजार स्थिर आहे.',
    'crops.shopDetails': 'दुकानाचा तपशील',
    'crops.getDirections': 'दिशानिर्देश मिळवा',
    'crops.callNow': 'आता कॉल करा',
    'crops.availableItems': 'उपलब्ध वस्तू',
    'crops.distance': 'अंतर',
    'inputFinder.title': 'इनपुट शोधक',
    'inputFinder.description': 'जवळपासची दुकाने शोधा',
    'inputFinder.searchPlaceholder': 'इनपुट शोधा ...',
    'inputFinder.allShops': 'सर्व दुकाने',
    'inputFinder.pmkskCenters': 'पीएमकेएसके केंद्रे',
    'inputFinder.privateShops': 'खासगी दुकाने',
    'inputFinder.kmAway': 'किमी दूर',
    'inputFinder.currentPrices': 'सध्याचे दर',
    'inputFinder.callNow': 'आता कॉल करा',
    'inputFinder.call': 'कॉल करा',
    'inputFinder.getDirections': 'दिशानिर्देश',
    'dashboard.cropDiagnosis.title': 'पीक निदान (एआय)',
    'dashboard.cropDiagnosis.description': 'आपल्या रोगट पिकाचा फोटो घ्या ...',
    'dashboard.cropDiagnosis.imageTooLarge': 'प्रतिमा खूप मोठी. कृपया 5MB पेक्षा लहान प्रतिमा वापरा.',
    'dashboard.cropDiagnosis.invalidFileType': 'कृपया एक वैध प्रतिमा फाइल अपलोड करा.',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'प्रतिमेचे विश्लेषण करण्यात अयशस्वी. कृपया फोटो स्पष्ट असल्याची खात्री करा.',
    'dashboard.cropDiagnosis.note': 'एआय विश्लेषण 100% अचूक असू शकत नाही',
    'diagnosis.takePhoto': 'फोटो घ्या',
    'diagnosis.uploadFromGallery': 'गॅलरीमधून निवडा',
    'diagnosis.tipsTitle': 'चांगल्या फोटोंसाठी टिप्स',
    'diagnosis.tip1': 'चांगली प्रकाशाची खात्री करा',
    'diagnosis.tip2': 'संक्रमित क्षेत्रावर लक्ष केंद्रित करा',
    'diagnosis.tip3': 'पान स्थिर ठेवा',
    'diagnosis.tip4': 'सावली टाळा',
    'diagnosis.cropImageAlt': 'क्रॉप इमेज',
    'diagnosis.remove': 'काढा',
    'diagnosis.analyzeWithAI': 'एआयसह विश्लेषण करा',
    'diagnosis.retrying': 'पुन्हा प्रयत्न करणे',
    'diagnosis.analyzing': 'क्रॉप प्रतिमेचे विश्लेषण करत आहे...',
    'diagnosis.analyzingSubtext': 'विसंगती शोधण्यासाठी प्रगत व्हिजन एआय वापरणे.',
    'diagnosis.analysisComplete': 'विश्लेषण पूर्ण झाले',
    'diagnosis.laymanHealthy': 'चांगली बातमी! आपले {crop_name} पीक निरोगी दिसते. हे अशा प्रकारे ठेवण्यासाठी, योग्य पाणी देण्याची खात्री करा आणि भविष्यातील कोणत्याही समस्यांचे परीक्षण करा.',
    'diagnosis.laymanDiseased': 'असे दिसते की आपला {crop_name} {disease_name} ग्रस्त आहे. आपल्याला दिसणारी काही सामान्य लक्षणे म्हणजे {लक्षणे}. यावर उपचार करण्यासाठी, आपण {treatment_organic} सारख्या सेंद्रिय सोल्यूशन्स किंवा {treatment_chemical} सारख्या रासायनिक पर्यायांचा वापर करू शकता. भविष्यात प्रतिबंधासाठी, {प्रतिबंध}.',
    'cropRecommendation.title': 'पीक सल्लागार',
    'cropRecommendation.description': 'आपली माती आणि हवामानावर आधारित एआय शिफारसी मिळवा',
    'cropRecommendation.loamy': 'लोमी',
    'cropRecommendation.clay': 'क्ले',
    'cropRecommendation.sandy': 'सँडी',
    'cropRecommendation.silt': 'गाळ',
    'cropRecommendation.redSoil': 'लाल माती',
    'cropRecommendation.blackSoil': 'काळी माती',
    'cropRecommendation.alluvial': 'जलोढ',
    'cropRecommendation.location': 'स्थान',
    'cropRecommendation.locationPlaceholder': 'शहर किंवा प्रदेश प्रविष्ट करा',
    'cropRecommendation.season': 'हंगाम',
    'cropRecommendation.kharif': 'खरीप',
    'cropRecommendation.rabi': 'रबी',
    'cropRecommendation.zaid': 'झैद',
    'cropRecommendation.waterAvailability': 'पाण्याची उपलब्धता .',
    'cropRecommendation.abundant': 'मुबलक प्रमाणात',
    'cropRecommendation.moderate': 'मध्यम',
    'cropRecommendation.limited': 'मर्यादित',
    'cropRecommendation.rainDependent': 'पावसावर अवलंबून',
    'cropRecommendation.fillRequiredFields': 'कृपया सर्व आवश्यक फील्ड भरा.',
    'cropRecommendation.generateRecommendations': 'शिफारसी तयार करा',
    'cropRecommendation.analyzing': 'विश्लेषण करत आहे ...',
    'cropRecommendation.gettingRecommendations': 'आपल्या प्रदेशासाठी सर्वोत्तम पिके शोधत आहे ...',
    'cropRecommendation.recommendationsReady': 'शिफारसी तयार आहेत!',
    'cropRecommendation.yieldLabel': 'अपेक्षित उत्पादन:',
    'cropRecommendation.waterLabel': 'पाण्याची आवश्यकता:',
    'cropRecommendation.marketLabel': 'बाजार किंमत:',
    'cropRecommendation.durationLabel': 'कालावधी:',
    'cropRecommendation.conditionsLabel': 'अटी:',
    'cropRecommendation.investmentLabel': 'गुंतवणूक:',
    'cropRecommendation.newSearch': 'नवीन शोध',
    'cropRecommendation.shareTitle': 'पिकांच्या शिफारशी',
    'cropRecommendation.share': 'शेअर करा',
    'cropRecommendation.errorMessage': 'शिफारस तयार करण्यात त्रुटी',
    'cropRecommendation.soilType': 'मातीचा प्रकार',
  },
  ta: {
    'crops.marketPrices': 'நேரடி மண்டி விலைகள்',
    'crops.searchCrops': 'பயிர்களைத் தேடுங்கள்...',
    'market.highpriceincrease': 'அதிக விலை உயர்வு',
    'market.pricesdecline': 'விலைகள் குறைந்து வருகின்றன',
    'market.stableprices': 'சந்தை நிலையானதாக உள்ளது',
    'crops.shopDetails': 'கடை விவரங்கள்',
    'crops.getDirections': 'திசைகளைப் பெறுங்கள்',
    'crops.callNow': 'இப்போதே அழைக்கவும்',
    'crops.availableItems': 'கிடைக்கும் பொருட்கள்',
    'crops.distance': 'தூரம்',
    'inputFinder.title': 'உள்ளீட்டு கண்டுபிடிப்பாளர்',
    'inputFinder.description': 'அருகிலுள்ள கடைகளைக் கண்டறியவும்',
    'inputFinder.searchPlaceholder': 'தேடல் உள்ளீடுகள்...',
    'inputFinder.allShops': 'அனைத்து கடைகள்',
    'inputFinder.pmkskCenters': 'PMKSK மையங்கள்',
    'inputFinder.privateShops': 'தனியார் கடைகள்',
    'inputFinder.kmAway': 'கி.மீ தொலைவில்',
    'inputFinder.currentPrices': 'தற்போதைய விலைகள்',
    'inputFinder.callNow': 'இப்போதே அழைக்கவும்',
    'inputFinder.call': 'அழைப்பு',
    'inputFinder.getDirections': 'செய்முறை :',
    'dashboard.cropDiagnosis.title': 'பயிர் நோயறிதல் (AI)',
    'dashboard.cropDiagnosis.description': 'உங்கள் நோயுற்ற பயிரின் புகைப்படத்தை எடுங்கள்...',
    'dashboard.cropDiagnosis.imageTooLarge': 'படம் மிகப் பெரியது. 5MB க்கும் குறைவான படத்தைப் பயன்படுத்தவும்.',
    'dashboard.cropDiagnosis.invalidFileType': 'செல்லுபடியாகும் படக் கோப்பைப் பதிவேற்றவும்.',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'படத்தை பகுப்பாய்வு செய்வதில் தோல்வி. புகைப்படம் தெளிவாக இருப்பதை உறுதிசெய்யவும்.',
    'dashboard.cropDiagnosis.note': 'AI பகுப்பாய்வு 100% துல்லியமாக இருக்காது',
    'diagnosis.takePhoto': 'புகைப்படம் எடுக்கவும்',
    'diagnosis.uploadFromGallery': 'கேலரியில் இருந்து தேர்வு செய்யவும்',
    'diagnosis.tipsTitle': 'நல்ல புகைப்படங்களுக்கான உதவிக்குறிப்புகள்',
    'diagnosis.tip1': 'நல்ல வெளிச்சத்தை உறுதி செய்யவும்',
    'diagnosis.tip2': 'பாதிக்கப்பட்ட பகுதியில் கவனம் செலுத்துங்கள்',
    'diagnosis.tip3': 'இலையை சீராக வைத்திருங்கள்',
    'diagnosis.tip4': 'நிழல்களைத் தவிர்க்கவும்',
    'diagnosis.cropImageAlt': 'பயிர் படம்',
    'diagnosis.remove': 'அகற்று',
    'diagnosis.analyzeWithAI': 'AI உடன் பகுப்பாய்வு செய்யவும்',
    'diagnosis.retrying': 'மீண்டும் முயற்சித்தல்',
    'diagnosis.analyzing': 'பயிர் படத்தை பகுப்பாய்வு செய்கிறது...',
    'diagnosis.analyzingSubtext': 'முரண்பாடுகளைக் கண்டறிய மேம்பட்ட விஷன் AI ஐப் பயன்படுத்துதல்.',
    'diagnosis.analysisComplete': 'பகுப்பாய்வு முடிந்தது',
    'diagnosis.laymanHealthy': 'பெரிய செய்தி! உங்கள் {crop_name} பயிர் ஆரோக்கியமாகத் தெரிகிறது. இதை இந்த வழியில் வைத்திருக்க, சரியான நீர்ப்பாசனத்தை உறுதி செய்து, எதிர்கால சிக்கல்களை கண்காணிக்கவும்.',
    'diagnosis.laymanDiseased': 'உங்கள் {crop_name} {disease_name} நோயால் பாதிக்கப்படுவது போல் தெரிகிறது. நீங்கள் கவனித்திருக்கக்கூடிய சில பொதுவான அறிகுறிகள் {அறிகுறிகள்}. இதற்கு சிகிச்சையளிக்க, நீங்கள் {treatment_organic} போன்ற கரிமக் கரைசல்கள் அல்லது {treatment_chemical} போன்ற வேதியியல் விருப்பங்களைப் பயன்படுத்தலாம். எதிர்காலத்தில் தடுப்புக்காக, {prevention}.',
    'cropRecommendation.title': 'பயிர் ஆலோசகர்',
    'cropRecommendation.description': 'உங்கள் மண் மற்றும் வானிலையின் அடிப்படையில் AI பரிந்துரைகளைப் பெறுங்கள்',
    'cropRecommendation.loamy': 'களிமணை',
    'cropRecommendation.clay': 'களிமண்',
    'cropRecommendation.sandy': 'சாண்டி',
    'cropRecommendation.silt': 'வண்டல் மண்',
    'cropRecommendation.redSoil': 'செம்மண்',
    'cropRecommendation.blackSoil': 'கருப்பு மண்',
    'cropRecommendation.alluvial': 'வண்டல்',
    'cropRecommendation.location': 'இடம்',
    'cropRecommendation.locationPlaceholder': 'நகரம் அல்லது வட்டாரத்தை உள்ளிடவும்',
    'cropRecommendation.season': 'பருவம்',
    'cropRecommendation.kharif': 'காரீஃப்',
    'cropRecommendation.rabi': 'ரபி',
    'cropRecommendation.zaid': 'ஜயீத்',
    'cropRecommendation.waterAvailability': 'நீர் கிடைக்கும் தன்மை',
    'cropRecommendation.abundant': 'ஏராளமான',
    'cropRecommendation.moderate': 'மிதமான',
    'cropRecommendation.limited': 'லிமிடெட்',
    'cropRecommendation.rainDependent': 'மழை சார்ந்தது',
    'cropRecommendation.fillRequiredFields': 'தேவையான அனைத்து புலங்களையும் நிரப்பவும்.',
    'cropRecommendation.generateRecommendations': 'பரிந்துரைகளை உருவாக்கவும்',
    'cropRecommendation.analyzing': 'பகுப்பாய்வு செய்கிறது...',
    'cropRecommendation.gettingRecommendations': 'உங்கள் பகுதிக்கு சிறந்த பயிர்களைக் கண்டறிதல்...',
    'cropRecommendation.recommendationsReady': 'பரிந்துரைகள் தயார்!',
    'cropRecommendation.yieldLabel': 'எதிர்பார்க்கப்படும் மகசூல்:',
    'cropRecommendation.waterLabel': 'நீர் அளவு:',
    'cropRecommendation.marketLabel': 'சந்தை விலை:',
    'cropRecommendation.durationLabel': 'காலம்:',
    'cropRecommendation.conditionsLabel': 'நிபந்தனைகள்:',
    'cropRecommendation.investmentLabel': 'முதலீடு:',
    'cropRecommendation.newSearch': 'புதிய தேடல்',
    'cropRecommendation.shareTitle': 'பயிர் பரிந்துரைகள்',
    'cropRecommendation.share': 'இந்த',
    'cropRecommendation.errorMessage': 'பரிந்துரையை உருவாக்குவதில் பிழை',
    'cropRecommendation.soilType': 'மண் வகை',
  },
  gu: {
    'crops.marketPrices': 'લાઇવ મંડી ભાવ',
    'crops.searchCrops': 'પાકો શોધો...',
    'market.highpriceincrease': 'ભાવમાં ઊંચો વધારો',
    'market.pricesdecline': 'કિંમતો ઘટી રહી છે',
    'market.stableprices': 'બજાર સ્થિર છે',
    'crops.shopDetails': 'દુકાનની વિગતો',
    'crops.getDirections': 'દિશાનિર્દેશો મેળવો',
    'crops.callNow': 'હમણાં જ કોલ કરો',
    'crops.availableItems': 'ઉપલ્બધ વસ્તુઓ',
    'crops.distance': 'અંતર',
    'inputFinder.title': 'ઇનપુટ શોધનાર',
    'inputFinder.description': 'નજીકની દુકાનો શોધો',
    'inputFinder.searchPlaceholder': 'ઈનપુટ શોધો...',
    'inputFinder.allShops': 'બધી દુકાનો',
    'inputFinder.pmkskCenters': 'પીએમકેએસકે કેન્દ્રો',
    'inputFinder.privateShops': 'ખાનગી દુકાનો',
    'inputFinder.kmAway': 'કિમી દૂર',
    'inputFinder.currentPrices': 'વર્તમાન કિંમતો',
    'inputFinder.callNow': 'હમણાં જ કોલ કરો',
    'inputFinder.call': 'કોલ કરો',
    'inputFinder.getDirections': 'દિશાઓ',
    'dashboard.cropDiagnosis.title': 'પાક નિદાન (એઆઈ)',
    'dashboard.cropDiagnosis.description': 'તમારા રોગગ્રસ્ત પાકનો ફોટો લો...',
    'dashboard.cropDiagnosis.imageTooLarge': 'ચિત્ર ઘણુ લાંબુ છે. કૃપા કરીને 5MB કરતા નાની છબીનો ઉપયોગ કરો.',
    'dashboard.cropDiagnosis.invalidFileType': 'મહેરબાની કરીને માન્ય ઇમેજ ફાઇલ અપલોડ કરો.',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'ચિત્રનું વિશ્લેષણ કરવામાં નિષ્ફળ. કૃપા કરીને ખાતરી કરો કે ફોટો સ્પષ્ટ છે.',
    'dashboard.cropDiagnosis.note': 'AI વિશ્લેષણ 100% સચોટ ન હોઈ શકે',
    'diagnosis.takePhoto': 'ફોટો લો',
    'diagnosis.uploadFromGallery': 'ગૅલરિમાંથી પસંદ કરો',
    'diagnosis.tipsTitle': 'સારા ફોટા માટે ટિપ્સ',
    'diagnosis.tip1': 'સારી લાઇટિંગ સુનિશ્ચિત કરો',
    'diagnosis.tip2': 'ચેપગ્રસ્ત વિસ્તાર પર ધ્યાન કેન્દ્રિત કરો',
    'diagnosis.tip3': 'પાંદડાને સ્થિર રાખો',
    'diagnosis.tip4': 'પડછાયાઓને ટાળો',
    'diagnosis.cropImageAlt': 'ચિત્રને કાપો',
    'diagnosis.remove': 'દૂર કરો',
    'diagnosis.analyzeWithAI': 'AI સાથે વિશ્લેષણ કરો',
    'diagnosis.retrying': 'પુન:પ્રયત્ન કરી રહ્યા છે',
    'diagnosis.analyzing': 'કાપવાના ચિત્રનું વિશ્લેષણ કરી રહ્યા છે...',
    'diagnosis.analyzingSubtext': 'વિસંગતતાઓ શોધવા માટે અદ્યતન વિઝન એઆઈનો ઉપયોગ કરવો.',
    'diagnosis.analysisComplete': 'વિશ્લેષણ પૂર્ણ થયેલ છે',
    'diagnosis.laymanHealthy': 'મહાન સમાચાર! તમારો {crop_name} પાક સ્વસ્થ લાગે છે. તેને આ રીતે રાખવા માટે, યોગ્ય પાણીની ખાતરી કરો અને ભવિષ્યની કોઈપણ સમસ્યાઓ માટે મોનિટર કરો.',
    'diagnosis.laymanDiseased': 'એવું લાગે છે કે તમારું {crop_name} {disease_name}થી પીડાય છે. કેટલાક સામાન્ય લક્ષણો તમે જોયા હશે {લક્ષણો}. આની સારવાર કરવા માટે, તમે {treatment_organic} જેવા કાર્બનિક ઉકેલો અથવા {treatment_chemical} જેવા રાસાયણિક વિકલ્પોનો ઉપયોગ કરી શકો છો. ભવિષ્યમાં નિવારણ માટે, {નિવારણ}.',
    'cropRecommendation.title': 'પાક સલાહકાર',
    'cropRecommendation.description': 'તમારી જમીન અને હવામાનના આધારે એઆઈ ભલામણો મેળવો',
    'cropRecommendation.loamy': 'લોમી',
    'cropRecommendation.clay': 'માટી',
    'cropRecommendation.sandy': 'સેન્ડી',
    'cropRecommendation.silt': 'કાંપ',
    'cropRecommendation.redSoil': 'લાલ માટી',
    'cropRecommendation.blackSoil': 'કાળી માટી',
    'cropRecommendation.alluvial': 'કાંપવાળું',
    'cropRecommendation.location': 'સ્થાન',
    'cropRecommendation.locationPlaceholder': 'શહેર અથવા વિસ્તારને દાખલ કરો',
    'cropRecommendation.season': 'મોસમ',
    'cropRecommendation.kharif': 'ખરીફ',
    'cropRecommendation.rabi': 'રબી',
    'cropRecommendation.zaid': 'ઝાઈદ',
    'cropRecommendation.waterAvailability': 'પાણીની ઉપલબ્ધતા[ફેરફાર કરો]',
    'cropRecommendation.abundant': 'વિપુલ પ્રમાણમાં',
    'cropRecommendation.moderate': 'મધ્યમ',
    'cropRecommendation.limited': 'મર્યાદિત',
    'cropRecommendation.rainDependent': 'વરસાદ પર આધારિત',
    'cropRecommendation.fillRequiredFields': 'મહેરબાની કરીને બધા જરૂરી ક્ષેત્રો ભરો.',
    'cropRecommendation.generateRecommendations': 'ભલામણો બનાવો',
    'cropRecommendation.analyzing': 'વિશ્લેષણ કરી રહ્યા છે...',
    'cropRecommendation.gettingRecommendations': 'તમારા પ્રદેશ માટે શ્રેષ્ઠ પાક શોધવો...',
    'cropRecommendation.recommendationsReady': 'ભલામણો તૈયાર!',
    'cropRecommendation.yieldLabel': 'અપેક્ષિત ઉપજ:',
    'cropRecommendation.waterLabel': 'વોટર રિક્યુ:',
    'cropRecommendation.marketLabel': 'બજાર કિંમત:',
    'cropRecommendation.durationLabel': 'સમયગાળો:',
    'cropRecommendation.conditionsLabel': 'શરતો:',
    'cropRecommendation.investmentLabel': 'રોકાણ:',
    'cropRecommendation.newSearch': 'નવી શોધ',
    'cropRecommendation.shareTitle': 'પાક ભલામણો',
    'cropRecommendation.share': 'વહેંચો',
    'cropRecommendation.errorMessage': 'ભલામણને ઉત્પન્ન કરી રહ્યા હોય ત્યારે ભૂલ',
    'cropRecommendation.soilType': 'માટીનો પ્રકાર',
  },
  kn: {
    'crops.marketPrices': 'ಲೈವ್ ಮಂಡಿ ಬೆಲೆಗಳು',
    'crops.searchCrops': 'ಬೆಳೆಗಳನ್ನು ಹುಡುಕಿ...',
    'market.highpriceincrease': 'ಹೆಚ್ಚಿನ ಬೆಲೆ ಹೆಚ್ಚಳ',
    'market.pricesdecline': 'ಬೆಲೆ ಇಳಿಕೆ',
    'market.stableprices': 'ಮಾರುಕಟ್ಟೆ ಸ್ಥಿರವಾಗಿದೆ',
    'crops.shopDetails': 'ಅಂಗಡಿ ವಿವರಗಳು',
    'crops.getDirections': 'ನಿರ್ದೇಶನಗಳನ್ನು ಪಡೆಯಿರಿ',
    'crops.callNow': 'ಈಗಲೇ ಕರೆ ಮಾಡಿ',
    'crops.availableItems': 'ಲಭ್ಯವಿರುವ ಐಟಂಗಳು',
    'crops.distance': 'ದೂರ',
    'inputFinder.title': 'ಇನ್ ಪುಟ್ ಫೈಂಡರ್',
    'inputFinder.description': 'ಹತ್ತಿರದ ಅಂಗಡಿಗಳನ್ನು ಹುಡುಕಿ',
    'inputFinder.searchPlaceholder': 'ಇನ್ ಪುಟ್ ಗಳನ್ನು ಹುಡುಕಿ...',
    'inputFinder.allShops': 'ಎಲ್ಲಾ ಅಂಗಡಿಗಳು',
    'inputFinder.pmkskCenters': 'ಪಿಎಂಕೆಎಸ್ ಕೆ ಕೇಂದ್ರಗಳು',
    'inputFinder.privateShops': 'ಖಾಸಗಿ ಅಂಗಡಿಗಳು',
    'inputFinder.kmAway': 'ಕಿ.ಮೀ ದೂರ',
    'inputFinder.currentPrices': 'ಪ್ರಸ್ತುತ ಬೆಲೆಗಳು',
    'inputFinder.callNow': 'ಈಗಲೇ ಕರೆ ಮಾಡಿ',
    'inputFinder.call': 'ಕರೆ',
    'inputFinder.getDirections': 'ನಿರ್ದೇಶನಗಳು',
    'dashboard.cropDiagnosis.title': 'ಬೆಳೆ ರೋಗನಿರ್ಣಯ (ಎಐ)',
    'dashboard.cropDiagnosis.description': 'ನಿಮ್ಮ ರೋಗಗ್ರಸ್ತ ಬೆಳೆಯ ಫೋಟೋ ತೆಗೆಯಿರಿ...',
    'dashboard.cropDiagnosis.imageTooLarge': 'ಚಿತ್ರವು ತುಂಬಾ ದೊಡ್ಡದಾಗಿದೆ. ದಯವಿಟ್ಟು 5MB ಗಿಂತ ಚಿಕ್ಕದಾದ ಚಿತ್ರವನ್ನು ಬಳಸಿ.',
    'dashboard.cropDiagnosis.invalidFileType': 'ದಯವಿಟ್ಟು ಮಾನ್ಯ ಇಮೇಜ್ ಫೈಲ್ ಅನ್ನು ಅಪ್ ಲೋಡ್ ಮಾಡಿ.',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'ಇಮೇಜ್ ವಿಶ್ಲೇಷಿಸಲು ವಿಫಲವಾಗಿದೆ. ಫೋಟೋ ಸ್ಪಷ್ಟವಾಗಿದೆ ಎಂದು ದಯವಿಟ್ಟು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.',
    'dashboard.cropDiagnosis.note': 'AI ವಿಶ್ಲೇಷಣೆಯು 100% ನಿಖರವಾಗಿರುವುದಿಲ್ಲ',
    'diagnosis.takePhoto': 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    'diagnosis.uploadFromGallery': 'ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆಮಾಡಿ',
    'diagnosis.tipsTitle': 'ಉತ್ತಮ ಫೋಟೋಗಳಿಗೆ ಸಲಹೆಗಳು',
    'diagnosis.tip1': 'ಉತ್ತಮ ಬೆಳಕನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ',
    'diagnosis.tip2': 'ಸೋಂಕಿತ ಪ್ರದೇಶದ ಮೇಲೆ ಗಮನ ಕೇಂದ್ರೀಕರಿಸಿ',
    'diagnosis.tip3': 'ಎಲೆಯನ್ನು ಸ್ಥಿರವಾಗಿರಿಸಿಕೊಳ್ಳಿ',
    'diagnosis.tip4': 'ನೆರಳುಗಳನ್ನು ತಪ್ಪಿಸಿ',
    'diagnosis.cropImageAlt': 'ಇಮೇಜ್ ಕತ್ತರಿಸಿ',
    'diagnosis.remove': 'ತೆಗೆದುಹಾಕಿ',
    'diagnosis.analyzeWithAI': 'AI ನೊಂದಿಗೆ ವಿಶ್ಲೇಷಿಸಿ',
    'diagnosis.retrying': 'ಪುನಃ ಪ್ರಯತ್ನಿಸುವುದು',
    'diagnosis.analyzing': 'ಕ್ರಾಪ್ ಇಮೇಜ್ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    'diagnosis.analyzingSubtext': 'ವೈಪರೀತ್ಯಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಲು ಸುಧಾರಿತ ವಿಷನ್ ಎಐ ಅನ್ನು ಬಳಸುವುದು.',
    'diagnosis.analysisComplete': 'ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ',
    'diagnosis.laymanHealthy': 'ಉತ್ತಮ ಸುದ್ದಿ! ನಿಮ್ಮ {crop_name} ಬೆಳೆ ಆರೋಗ್ಯಕರವಾಗಿ ಕಾಣುತ್ತದೆ. ಇದನ್ನು ಈ ರೀತಿ ಇರಿಸಲು, ಸರಿಯಾದ ನೀರುಣಿಸುವುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ ಮತ್ತು ಭವಿಷ್ಯದ ಯಾವುದೇ ಸಮಸ್ಯೆಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ.',
    'diagnosis.laymanDiseased': 'ನಿಮ್ಮ {crop_name} {disease_name} ನಿಂದ ಬಳಲುತ್ತಿದ್ದಾರೆ ಎಂದು ತೋರುತ್ತಿದೆ. ನೀವು ಗಮನಿಸಿರಬಹುದಾದ ಕೆಲವು ಸಾಮಾನ್ಯ ರೋಗಲಕ್ಷಣಗಳೆಂದರೆ {ರೋಗಲಕ್ಷಣಗಳು}. ಇದಕ್ಕೆ ಚಿಕಿತ್ಸೆ ನೀಡಲು, ನೀವು {treatment_organic} ನಂತಹ ಸಾವಯವ ದ್ರಾವಣಗಳನ್ನು ಅಥವಾ {treatment_chemical} ನಂತಹ ರಾಸಾಯನಿಕ ಆಯ್ಕೆಗಳನ್ನು ಬಳಸಬಹುದು. ಭವಿಷ್ಯದಲ್ಲಿ ತಡೆಗಟ್ಟುವಿಕೆಗಾಗಿ, {ತಡೆಗಟ್ಟುವಿಕೆ}.',
    'cropRecommendation.title': 'ಬೆಳೆ ಸಲಹೆಗಾರ',
    'cropRecommendation.description': 'ನಿಮ್ಮ ಮಣ್ಣು ಮತ್ತು ಹವಾಮಾನದ ಆಧಾರದ ಮೇಲೆ AI ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ',
    'cropRecommendation.loamy': 'ಲೋಮಿ',
    'cropRecommendation.clay': 'ಜೇಡಿಮಣ್ಣು',
    'cropRecommendation.sandy': 'ಸ್ಯಾಂಡಿ',
    'cropRecommendation.silt': 'ಹೂಳು',
    'cropRecommendation.redSoil': 'ಕೆಂಪು ಮಣ್ಣು',
    'cropRecommendation.blackSoil': 'ಕಪ್ಪು ಮಣ್ಣು',
    'cropRecommendation.alluvial': 'ಮೆಕ್ಕಲು',
    'cropRecommendation.location': 'ಸ್ಥಾನ',
    'cropRecommendation.locationPlaceholder': 'ನಗರ ಅಥವಾ ಪ್ರದೇಶವನ್ನು ನಮೂದಿಸಿ',
    'cropRecommendation.season': 'ಋತುಮಾನ',
    'cropRecommendation.kharif': 'ಖಾರಿಫ್ .',
    'cropRecommendation.rabi': 'ರಬಿ',
    'cropRecommendation.zaid': 'ಝೈದ್',
    'cropRecommendation.waterAvailability': 'ನೀರಿನ ಲಭ್ಯತೆ',
    'cropRecommendation.abundant': 'ಹೇರಳ',
    'cropRecommendation.moderate': 'ಮಧ್ಯಮ',
    'cropRecommendation.limited': 'ಲಿಮಿಟೆಡ್',
    'cropRecommendation.rainDependent': 'ಮಳೆ ಅವಲಂಬಿತ',
    'cropRecommendation.fillRequiredFields': 'ದಯವಿಟ್ಟು ಅಗತ್ಯವಿರುವ ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.',
    'cropRecommendation.generateRecommendations': 'ಶಿಫಾರಸುಗಳನ್ನು ರಚಿಸಿ',
    'cropRecommendation.analyzing': 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    'cropRecommendation.gettingRecommendations': 'ನಿಮ್ಮ ಪ್ರದೇಶಕ್ಕೆ ಉತ್ತಮ ಬೆಳೆಗಳನ್ನು ಹುಡುಕುವುದು...',
    'cropRecommendation.recommendationsReady': 'ಶಿಫಾರಸುಗಳು ಸಿದ್ಧವಾಗಿವೆ!',
    'cropRecommendation.yieldLabel': 'ನಿರೀಕ್ಷಿತ ಇಳುವರಿ:',
    'cropRecommendation.waterLabel': 'ವಾಟರ್ ರೆಕ್ಯೂ:',
    'cropRecommendation.marketLabel': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ:',
    'cropRecommendation.durationLabel': 'ಅವಧಿ:',
    'cropRecommendation.conditionsLabel': 'ಷರತ್ತುಗಳು:',
    'cropRecommendation.investmentLabel': 'ಹೂಡಿಕೆ:',
    'cropRecommendation.newSearch': 'ಹೊಸ ಹುಡುಕಾಟ',
    'cropRecommendation.shareTitle': 'ಬೆಳೆ ಶಿಫಾರಸುಗಳು',
    'cropRecommendation.share': 'ಹಂಚಿಕೊಳ್ಳಿ',
    'cropRecommendation.errorMessage': 'ಶಿಫಾರಸು ರಚಿಸುವಲ್ಲಿ ದೋಷ',
    'cropRecommendation.soilType': 'ಮಣ್ಣಿನ ವಿಧ',
  },
  ml: {
    'crops.marketPrices': 'തത്സമയ മണ്ഡി വില',
    'crops.searchCrops': 'വിളകൾ തിരയുക...',
    'market.highpriceincrease': 'ഉയർന്ന വില വർദ്ധനവ്',
    'market.pricesdecline': 'വില കുറയുന്നു',
    'market.stableprices': 'വിപണി സ്ഥിരത',
    'crops.shopDetails': 'ഷോപ്പ് വിശദാംശങ്ങൾ',
    'crops.getDirections': 'ദിശകൾ നേടുക',
    'crops.callNow': 'ഇപ്പോൾ വിളിക്കുക',
    'crops.availableItems': 'ലഭ്യമായ ഇനങ്ങൾ',
    'crops.distance': 'ദൂരം',
    'inputFinder.title': 'ഇൻപുട്ട് ഫൈൻഡർ',
    'inputFinder.description': 'അടുത്തുള്ള കടകൾ കണ്ടെത്തുക',
    'inputFinder.searchPlaceholder': 'ഇൻപുട്ടുകൾ തിരയുക...',
    'inputFinder.allShops': 'എല്ലാ കടകളും',
    'inputFinder.pmkskCenters': 'പി.എം.കെ.എസ്.കെ കേന്ദ്രങ്ങൾ',
    'inputFinder.privateShops': 'സ്വകാര്യ കടകൾ',
    'inputFinder.kmAway': 'കിലോമീറ്റർ അകലെ.',
    'inputFinder.currentPrices': 'നിലവിലെ വിലകൾ',
    'inputFinder.callNow': 'ഇപ്പോൾ വിളിക്കുക',
    'inputFinder.call': 'വിളിക്കുക',
    'inputFinder.getDirections': 'ദിശകൾ',
    'dashboard.cropDiagnosis.title': 'വിള രോഗനിർണയം (AI)',
    'dashboard.cropDiagnosis.description': 'രോഗം ബാധിച്ച വിളയുടെ ഫോട്ടോ എടുക്കുക...',
    'dashboard.cropDiagnosis.imageTooLarge': 'ചിത്രം വളരെ വലുതാണ്. 5MB-നേക്കാൾ ചെറിയ ഒരു ഇമേജ് ഉപയോഗിക്കുക.',
    'dashboard.cropDiagnosis.invalidFileType': 'സാധുതയുള്ള ഒരു ഇമേജ് ഫയൽ അപ് ലോഡ് ചെയ്യുക.',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'ഇമേജ് വിശകലനം ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു. ഫോട്ടോ വ്യക്തമാണെന്ന് ഉറപ്പാക്കുക.',
    'dashboard.cropDiagnosis.note': 'AI വിശകലനം 100% കൃത്യമായിരിക്കില്ല',
    'diagnosis.takePhoto': 'ഫോട്ടോ എടുക്കുക',
    'diagnosis.uploadFromGallery': 'ഗാലറിയിൽ നിന്ന് തിരഞ്ഞെടുക്കുക',
    'diagnosis.tipsTitle': 'നല്ല ഫോട്ടോകൾക്കുള്ള നുറുങ്ങുകൾ',
    'diagnosis.tip1': 'നല്ല വെളിച്ചം ഉറപ്പാക്കുക',
    'diagnosis.tip2': 'രോഗബാധിത പ്രദേശത്ത് ശ്രദ്ധ കേന്ദ്രീകരിക്കുക',
    'diagnosis.tip3': 'ഇല സ്ഥിരമായി സൂക്ഷിക്കുക',
    'diagnosis.tip4': 'നിഴലുകൾ ഒഴിവാക്കുക',
    'diagnosis.cropImageAlt': 'ക്രോപ്പ് ഇമേജ്',
    'diagnosis.remove': 'നീക്കം ചെയ്യുക',
    'diagnosis.analyzeWithAI': 'AI ഉപയോഗിച്ച് വിശകലനം ചെയ്യുക',
    'diagnosis.retrying': 'വീണ്ടും ശ്രമിക്കുക',
    'diagnosis.analyzing': 'ക്രോപ്പ് ഇമേജ് വിശകലനം ചെയ്യുന്നു...',
    'diagnosis.analyzingSubtext': 'അപാകതകൾ കണ്ടെത്താൻ നൂതന വിഷൻ AI ഉപയോഗിക്കുന്നു.',
    'diagnosis.analysisComplete': 'വിശകലനം പൂർത്തിയായി',
    'diagnosis.laymanHealthy': 'നല്ല വാർത്ത! നിങ്ങളുടെ {crop_name} വിള ആരോഗ്യകരമായി കാണപ്പെടുന്നു. ഇത് ഈ രീതിയിൽ നിലനിർത്തുന്നതിന്, ശരിയായ നനയ്ക്കൽ ഉറപ്പാക്കുകയും ഭാവിയിലെ ഏതെങ്കിലും പ്രശ്നങ്ങൾ നിരീക്ഷിക്കുകയും ചെയ്യുക.',
    'diagnosis.laymanDiseased': 'നിങ്ങളുടെ {crop_name} {disease_name} രോഗം ബാധിച്ചതായി തോന്നുന്നു. നിങ്ങൾ ശ്രദ്ധിച്ചേക്കാവുന്ന ചില പൊതുവായ രോഗലക്ഷണങ്ങൾ {രോഗലക്ഷണങ്ങൾ} ആണ്. ഇത് ചികിത്സിക്കുന്നതിന്, നിങ്ങൾക്ക് {treatment_organic} പോലുള്ള ഓർഗാനിക് ലായനികൾ അല്ലെങ്കിൽ {treatment_chemical} പോലുള്ള കെമിക്കൽ ഓപ്ഷനുകൾ ഉപയോഗിക്കാം. ഭാവിയിൽ പ്രതിരോധത്തിനായി, {പ്രതിരോധം}.',
    'cropRecommendation.title': 'വിള ഉപദേഷ്ടാവ്',
    'cropRecommendation.description': 'നിങ്ങളുടെ മണ്ണിനെയും കാലാവസ്ഥയെയും അടിസ്ഥാനമാക്കി AI ശുപാർശകൾ നേടുക',
    'cropRecommendation.loamy': 'ലോമി',
    'cropRecommendation.clay': 'കളിമണ്ണ്',
    'cropRecommendation.sandy': 'സാൻഡി',
    'cropRecommendation.silt': 'എക്കൽ',
    'cropRecommendation.redSoil': 'ചുവന്ന മണ്ണ്',
    'cropRecommendation.blackSoil': 'കറുത്ത മണ്ണ്',
    'cropRecommendation.alluvial': 'എക്കൽ .',
    'cropRecommendation.location': 'സ്ഥാനം',
    'cropRecommendation.locationPlaceholder': 'നഗരമോ പ്രദേശമോ നൽകുക',
    'cropRecommendation.season': 'സീസൺ',
    'cropRecommendation.kharif': 'ഖാരിഫ്',
    'cropRecommendation.rabi': 'റാബി',
    'cropRecommendation.zaid': 'സെയ്ദ്',
    'cropRecommendation.waterAvailability': 'ജലലഭ്യത',
    'cropRecommendation.abundant': 'ധാരാളം[തിരുത്തുക]',
    'cropRecommendation.moderate': 'മിതമായ',
    'cropRecommendation.limited': 'ലിമിറ്റഡ്',
    'cropRecommendation.rainDependent': 'മഴയെ ആശ്രയിച്ച്[തിരുത്തുക]',
    'cropRecommendation.fillRequiredFields': 'ആവശ്യമായ എല്ലാ ഫീൽഡുകളും പൂരിപ്പിക്കുക.',
    'cropRecommendation.generateRecommendations': 'ശുപാർശകൾ സൃഷ്ടിക്കുക',
    'cropRecommendation.analyzing': 'വിശകലനം ചെയ്യുന്നു...',
    'cropRecommendation.gettingRecommendations': 'നിങ്ങളുടെ പ്രദേശത്തിന് ഏറ്റവും മികച്ച വിളകൾ കണ്ടെത്തുക...',
    'cropRecommendation.recommendationsReady': 'ശുപാർശകൾ തയ്യാറാണ്!',
    'cropRecommendation.yieldLabel': 'പ്രതീക്ഷിക്കുന്ന വിളവ്:',
    'cropRecommendation.waterLabel': 'വാട്ടർ റെക്യു:',
    'cropRecommendation.marketLabel': 'വിപണി വില:',
    'cropRecommendation.durationLabel': 'ദൈർഘ്യം:',
    'cropRecommendation.conditionsLabel': 'നിബന്ധനകൾ:',
    'cropRecommendation.investmentLabel': 'നിക്ഷേപം:',
    'cropRecommendation.newSearch': 'പുതിയ തിരയൽ',
    'cropRecommendation.shareTitle': 'വിള ശുപാർശകൾ',
    'cropRecommendation.share': 'പങ്കിടുക',
    'cropRecommendation.errorMessage': 'ശുപാർശ സൃഷ്ടിക്കുന്നതിൽ പിശക്',
    'cropRecommendation.soilType': 'മണ്ണിന്റെ തരം[തിരുത്തുക]',
  },
  pa: {
    'crops.marketPrices': 'ਲਾਈਵ ਮੰਡੀ ਦੀਆਂ ਕੀਮਤਾਂ',
    'crops.searchCrops': 'ਫਸਲਾਂ ਦੀ ਖੋਜ ਕਰੋ...',
    'market.highpriceincrease': 'ਉੱਚ ਕੀਮਤਾਂ ਵਿੱਚ ਵਾਧਾ',
    'market.pricesdecline': 'ਕੀਮਤਾਂ ਘਟ ਰਹੀਆਂ ਹਨ',
    'market.stableprices': 'ਬਾਜ਼ਾਰ ਸਥਿਰ ਹੈ',
    'crops.shopDetails': 'ਦੁਕਾਨ ਦੇ ਵੇਰਵੇ',
    'crops.getDirections': 'ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ',
    'crops.callNow': 'ਹੁਣੇ ਕਾਲ ਕਰੋ',
    'crops.availableItems': 'ਉਪਲੱਬਧ ਆਈਟਮਾਂ',
    'crops.distance': 'ਦੂਰੀ',
    'inputFinder.title': 'ਇਨਪੁੱਟ ਫਾਈਂਡਰ',
    'inputFinder.description': 'ਨੇੜਲੀਆਂ ਦੁਕਾਨਾਂ ਲੱਭੋ',
    'inputFinder.searchPlaceholder': 'ਖੋਜ ਇਨਪੁੱਟ...',
    'inputFinder.allShops': 'ਸਾਰੀਆਂ ਦੁਕਾਨਾਂ',
    'inputFinder.pmkskCenters': 'ਪੀਐੱਮਕੇਐੱਸਕੇ ਕੇਂਦਰ',
    'inputFinder.privateShops': 'ਨਿੱਜੀ ਦੁਕਾਨਾਂ',
    'inputFinder.kmAway': 'ਕਿਲੋਮੀਟਰ ਦੂਰ',
    'inputFinder.currentPrices': 'ਮੌਜੂਦਾ ਕੀਮਤਾਂ',
    'inputFinder.callNow': 'ਹੁਣੇ ਕਾਲ ਕਰੋ',
    'inputFinder.call': 'ਕਾਲ ਕਰੋ',
    'inputFinder.getDirections': 'ਦਿਸ਼ਾਵਾਂ[ਸੋਧੋ]',
    'dashboard.cropDiagnosis.title': 'ਫਸਲ ਦੀ ਜਾਂਚ (ਏਆਈ)',
    'dashboard.cropDiagnosis.description': 'ਆਪਣੀ ਰੋਗੀ ਫਸਲ ਦੀ ਫੋਟੋ ਲਓ...',
    'dashboard.cropDiagnosis.imageTooLarge': 'ਚਿੱਤਰ ਬਹੁਤ ਵੱਡਾ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ 5MB ਤੋਂ ਛੋਟੇ ਚਿੱਤਰ ਦੀ ਵਰਤੋਂ ਕਰੋ।',
    'dashboard.cropDiagnosis.invalidFileType': 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ ਚਿੱਤਰ ਫ਼ਾਈਲ ਅੱਪਲੋਡ ਕਰੋ।',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'ਚਿੱਤਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਨਾ ਅਸਫਲ ਰਿਹਾ। ਕਿਰਪਾ ਕਰਕੇ ਯਕੀਨੀ ਬਣਾਓ ਕਿ ਫ਼ੋਟੋ ਸਪੱਸ਼ਟ ਹੈ।',
    'dashboard.cropDiagnosis.note': 'AI ਵਿਸ਼ਲੇਸ਼ਣ 100٪ ਸਟੀਕ ਨਹੀਂ ਹੋ ਸਕਦਾ',
    'diagnosis.takePhoto': 'ਫ਼ੋਟੋ ਲਓ',
    'diagnosis.uploadFromGallery': 'ਗੈਲਰੀ ਵਿੱਚੋਂ ਚੁਣੋ',
    'diagnosis.tipsTitle': 'ਚੰਗੀਆਂ ਫੋਟੋਆਂ ਲਈ ਸੁਝਾਅ',
    'diagnosis.tip1': 'ਚੰਗੀ ਰੋਸ਼ਨੀ ਨੂੰ ਯਕੀਨੀ ਬਣਾਓ',
    'diagnosis.tip2': 'ਸੰਕ੍ਰਮਿਤ ਖੇਤਰ \'ਤੇ ਧਿਆਨ ਕੇਂਦ੍ਰਿਤ ਕਰੋ',
    'diagnosis.tip3': 'ਪੱਤੇ ਨੂੰ ਸਥਿਰ ਰੱਖੋ',
    'diagnosis.tip4': 'ਪਰਛਾਵੇਂ ਤੋਂ ਪਰਹੇਜ਼ ਕਰੋ',
    'diagnosis.cropImageAlt': 'ਕੱਟਣ ਦਾ ਚਿੱਤਰ',
    'diagnosis.remove': 'ਹਟਾਓ',
    'diagnosis.analyzeWithAI': 'AI ਨਾਲ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    'diagnosis.retrying': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰਨਾ',
    'diagnosis.analyzing': 'ਫ਼ਸਲ ਚਿੱਤਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    'diagnosis.analyzingSubtext': 'ਵਿਗਾੜਾਂ ਦਾ ਪਤਾ ਲਗਾਉਣ ਲਈ ਐਡਵਾਂਸਡ ਵਿਜ਼ਨ AI ਦੀ ਵਰਤੋਂ ਕਰਨਾ।',
    'diagnosis.analysisComplete': 'ਵਿਸ਼ਲੇਸ਼ਣ ਪੂਰਾ ਹੋਇਆ',
    'diagnosis.laymanHealthy': 'ਬਹੁਤ ਵਧੀਆ ਖ਼ਬਰ! ਤੁਹਾਡੀ {crop_name} ਫਸਲ ਸਿਹਤਮੰਦ ਲੱਗ ਰਹੀ ਹੈ। ਇਸ ਨੂੰ ਇਸ ਤਰ੍ਹਾਂ ਰੱਖਣ ਲਈ, ਸਹੀ ਪਾਣੀ ਨੂੰ ਯਕੀਨੀ ਬਣਾਓ ਅਤੇ ਭਵਿੱਖ ਦੇ ਕਿਸੇ ਵੀ ਮੁੱਦਿਆਂ ਦੀ ਨਿਗਰਾਨੀ ਕਰੋ.',
    'diagnosis.laymanDiseased': 'ਇੰਝ ਜਾਪਦਾ ਹੈ ਕਿ ਤੁਹਾਡਾ {crop_name} {disease_name} ਤੋਂ ਪੀੜਤ ਹੈ। ਕੁਝ ਆਮ ਲੱਛਣ ਜੋ ਤੁਸੀਂ ਦੇਖੇ ਹੋ ਸਕਦੇ ਹੋ ਉਹ ਹਨ {ਲੱਛਣ}। ਇਸਦਾ ਇਲਾਜ ਕਰਨ ਲਈ, ਤੁਸੀਂ ਜੈਵਿਕ ਘੋਲਾਂ ਜਿਵੇਂ ਕਿ {treatment_organic} ਜਾਂ {treatment_chemical} ਵਰਗੇ ਰਾਸਾਇਣਕ ਵਿਕਲਪਾਂ ਦੀ ਵਰਤੋਂ ਕਰ ਸਕਦੇ ਹੋ। ਭਵਿੱਖ ਵਿੱਚ ਰੋਕਥਾਮ ਲਈ, {ਰੋਕਥਾਮ}.',
    'cropRecommendation.title': 'ਫਸਲ ਸਲਾਹਕਾਰ',
    'cropRecommendation.description': 'ਆਪਣੀ ਮਿੱਟੀ ਅਤੇ ਮੌਸਮ ਦੇ ਆਧਾਰ \'ਤੇ AI ਸਿਫ਼ਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ',
    'cropRecommendation.loamy': 'ਲੋਮੀ',
    'cropRecommendation.clay': 'ਮਿੱਟੀ',
    'cropRecommendation.sandy': 'ਸੈਂਡੀ',
    'cropRecommendation.silt': 'ਗਾਰ',
    'cropRecommendation.redSoil': 'ਲਾਲ ਮਿੱਟੀ',
    'cropRecommendation.blackSoil': 'ਕਾਲੀ ਮਿੱਟੀ',
    'cropRecommendation.alluvial': 'ਜਲੋਢ',
    'cropRecommendation.location': 'ਟਿਕਾਣਾ',
    'cropRecommendation.locationPlaceholder': 'ਸ਼ਹਿਰ ਜਾਂ ਖੇਤਰ ਦਾਖਲ ਕਰੋ',
    'cropRecommendation.season': 'ਸੀਜ਼ਨ',
    'cropRecommendation.kharif': 'ਖਰੀਫ',
    'cropRecommendation.rabi': 'ਰਬੀ',
    'cropRecommendation.zaid': 'ਜ਼ੈਦ',
    'cropRecommendation.waterAvailability': 'ਪਾਣੀ ਦੀ ਉਪਲਬਧਤਾ',
    'cropRecommendation.abundant': 'ਬਹੁਤਾਤ',
    'cropRecommendation.moderate': 'ਦਰਮਿਆਨੀ',
    'cropRecommendation.limited': 'ਲਿਮਟਿਡ',
    'cropRecommendation.rainDependent': 'ਮੀਂਹ \'ਤੇ ਨਿਰਭਰ',
    'cropRecommendation.fillRequiredFields': 'ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਲੋੜੀਂਦੇ ਖੇਤਰਾਂ ਨੂੰ ਭਰੋ।',
    'cropRecommendation.generateRecommendations': 'ਸਿਫਾਰਸ਼ਾਂ ਤਿਆਰ ਕਰੋ',
    'cropRecommendation.analyzing': 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ...',
    'cropRecommendation.gettingRecommendations': 'ਆਪਣੇ ਖੇਤਰ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ ਫਸਲਾਂ ਲੱਭਣਾ...',
    'cropRecommendation.recommendationsReady': 'ਸਿਫਾਰਸ਼ਾਂ ਤਿਆਰ!',
    'cropRecommendation.yieldLabel': 'ਅਨੁਮਾਨਤ ਝਾੜ:',
    'cropRecommendation.waterLabel': 'ਵਾਟਰ ਰੀਕ:',
    'cropRecommendation.marketLabel': 'ਮਾਰਕੀਟ ਕੀਮਤ:',
    'cropRecommendation.durationLabel': 'ਮਿਆਦ:',
    'cropRecommendation.conditionsLabel': 'ਸ਼ਰਤਾਂ:',
    'cropRecommendation.investmentLabel': 'ਨਿਵੇਸ਼:',
    'cropRecommendation.newSearch': 'ਨਵੀਂ ਖੋਜ',
    'cropRecommendation.shareTitle': 'ਫਸਲ ਦੀਆਂ ਸਿਫਾਰਸ਼ਾਂ',
    'cropRecommendation.share': 'ਸਾਂਝਾ ਕਰੋ',
    'cropRecommendation.errorMessage': 'ਸਿਫ਼ਾਰਸ਼ ਤਿਆਰ ਕਰਨ ਵਿੱਚ ਗਲਤੀ',
    'cropRecommendation.soilType': 'ਮਿੱਟੀ ਦੀ ਕਿਸਮ',
  },
  or: {
    'crops.marketPrices': 'ଲାଇଭ୍ ମଣ୍ଡି ମୂଲ୍ୟ',
    'crops.searchCrops': 'ଫସଲ ସନ୍ଧାନ କରନ୍ତୁ...',
    'market.highpriceincrease': 'ପାଇଁ ଅଧିକ ମୂଲ୍ୟ ବୃଦ୍ଧି',
    'market.pricesdecline': 'ଦର ହ୍ରାସ ପାଉଛି',
    'market.stableprices': 'ବଜାର ପାଇଁ ସ୍ଥିର ଅଛି',
    'crops.shopDetails': 'ଦୋକାନ ବିବରଣୀ',
    'crops.getDirections': 'ଦିଗ ପାଆନ୍ତୁ',
    'crops.callNow': 'ବର୍ତ୍ତମାନ କଲ୍ କରନ୍ତୁ',
    'crops.availableItems': 'ଉପଲବ୍ଧ ଆଇଟମଗୁଡିକ',
    'crops.distance': 'ଦୂରତା',
    'inputFinder.title': 'ଇନପୁଟ୍ ଫାଇଣ୍ଡର',
    'inputFinder.description': 'ନିକଟବର୍ତ୍ତୀ ଦୋକାନଗୁଡିକ ଖୋଜନ୍ତୁ',
    'inputFinder.searchPlaceholder': 'ଇନପୁଟ୍ ସନ୍ଧାନ କରନ୍ତୁ...',
    'inputFinder.allShops': 'ସମସ୍ତ ଦୋକାନ',
    'inputFinder.pmkskCenters': 'ପିଏମକେଏସକେ କେନ୍ଦ୍ର',
    'inputFinder.privateShops': 'ଘରୋଇ ଦୋକାନ',
    'inputFinder.kmAway': 'କି.ମି. ଦୂରରେ',
    'inputFinder.currentPrices': 'ସାମ୍ପ୍ରତିକ ମୂଲ୍ୟ',
    'inputFinder.callNow': 'ବର୍ତ୍ତମାନ କଲ୍ କରନ୍ତୁ',
    'inputFinder.call': 'କଲ୍ କରନ୍ତୁ',
    'inputFinder.getDirections': 'ଦିଗ[ସମ୍ପାଦନା]',
    'dashboard.cropDiagnosis.title': 'ଫସଲ ନିଦାନ (AI)',
    'dashboard.cropDiagnosis.description': 'ଆପଣଙ୍କ ରୋଗଗ୍ରସ୍ତ ଫସଲର ଫଟୋ ଉଠାନ୍ତୁ...',
    'dashboard.cropDiagnosis.imageTooLarge': 'ଫଟୋ ବହୁତ ବଡ ଅଟେ। ଦୟାକରି 5MBରୁ ଛୋଟ ଫଟୋ ବ୍ୟବହାର କରନ୍ତୁ।',
    'dashboard.cropDiagnosis.invalidFileType': 'ଦୟାକରି ଏକ ବୈଧ ଫଟୋ ଫାଇଲ୍ ଅପଲୋଡ୍ କରନ୍ତୁ।',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'ଫଟୋ ବିଶ୍ଲେଷଣ କରିବାକୁ ବିଫଳ ହୋଇଛି। ଦୟାକରି ନିଶ୍ଚିତ କରନ୍ତୁ ଯେ ଫଟୋ ଖାଲି ଅଛି।',
    'dashboard.cropDiagnosis.note': 'AI ସମୀକ୍ଷା 100% ସଠିକ୍ ହୋଇନପାରେ',
    'diagnosis.takePhoto': 'ଫଟୋ ଉଠାନ୍ତୁ',
    'diagnosis.uploadFromGallery': 'ଗ୍ୟାଲେରୀରୁ ବାଛନ୍ତୁ',
    'diagnosis.tipsTitle': 'ଭଲ ଫଟୋଗୁଡିକ ପାଇଁ ଟିପ୍ପଣୀ',
    'diagnosis.tip1': 'ଭଲ ଆଲୋକ ସୁନିଶ୍ଚିତ କରନ୍ତୁ',
    'diagnosis.tip2': 'ସଂକ୍ରମିତ ଅଞ୍ଚଳ ଉପରେ ଧ୍ୟାନ ଦିଅନ୍ତୁ',
    'diagnosis.tip3': 'ପତ୍ରକୁ ସ୍ଥିର ରଖନ୍ତୁ',
    'diagnosis.tip4': 'ଛାୟାରୁ ଦୂରେଇ ରୁହନ୍ତୁ',
    'diagnosis.cropImageAlt': 'କ୍ରପ୍ ପ୍ରତିଛବି',
    'diagnosis.remove': 'ଅପସାରଣ କରନ୍ତୁ',
    'diagnosis.analyzeWithAI': 'AI ସହ ବିଶ୍ଲେଷଣ କରନ୍ତୁ',
    'diagnosis.retrying': 'ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ',
    'diagnosis.analyzing': 'କ୍ରପ୍ ଫଟୋ ବିଶ୍ଲେଷଣ ହେଉଛି...',
    'diagnosis.analyzingSubtext': 'ଅସଙ୍ଗତିଗୁଡିକ ଚିହ୍ନଟ କରିବାକୁ ଅଗ୍ରୀମ ଭିଜନ AI ବ୍ୟବହାର କରନ୍ତୁ।',
    'diagnosis.analysisComplete': 'ବିଶ୍ଳେଷଣ ସମ୍ପୂର୍ଣ୍ଣ',
    'diagnosis.laymanHealthy': 'ଭଲ ଖବର! ଆପଣଙ୍କ {crop_name} ଫସଲ ସ୍ୱାସ୍ଥକର ଦେଖାଯାଉଛି। ଏହାକୁ ଏହିପରି ରଖିବା ପାଇଁ, ଉପଯୁକ୍ତ ଜଳସେଚନ ନିଶ୍ଚିତ କରନ୍ତୁ ଏବଂ ଭବିଷ୍ୟତର କୌଣସି ସମସ୍ୟା ପାଇଁ ନିରୀକ୍ଷଣ କରନ୍ତୁ ।',
    'diagnosis.laymanDiseased': 'ଏପରି ଲାଗୁଛି ଯେ ଆପଣଙ୍କ {crop_name} {disease_name} ରେ ପୀଡିତ ଅଛି। କିଛି ସାଧାରଣ ଲକ୍ଷଣଗୁଡିକ ଯାହା ଆପଣ ଲକ୍ଷ୍ୟ କରିପାରନ୍ତି ତାହା ହେଉଛି {ଲକ୍ଷଣ }। ଏହାର ଚିକିତ୍ସା ପାଇଁ, ଆପଣ {treatment_organic} ପରି ଜୈବିକ ଦ୍ରବଣ କିମ୍ବା {treatment_chemical} ପରି ରାସାୟନିକ ବିକଳ୍ପ ବ୍ୟବହାର କରିପାରିବେ। ଭବିଷ୍ୟତରେ ପ୍ରତିରୋଧ ପାଇଁ, {prevent}।',
    'cropRecommendation.title': 'ଫସଲ ପରାମର୍ଶଦାତା',
    'cropRecommendation.description': 'ଆପଣଙ୍କ ମାଟି ଏବଂ ପାଣିପାଗ ଉପରେ ଆଧାର କରି AI ସୁପାରିଶକରଣଗୁଡିକ ପ୍ରାପ୍ତ କରନ୍ତୁ',
    'cropRecommendation.loamy': 'ଲୋମି',
    'cropRecommendation.clay': 'ମାଟି',
    'cropRecommendation.sandy': 'ସ୍ୟାଣ୍ଡି',
    'cropRecommendation.silt': 'ପଟୁ',
    'cropRecommendation.redSoil': 'ଲାଲ ମାଟି',
    'cropRecommendation.blackSoil': 'କଳା ମାଟି',
    'cropRecommendation.alluvial': 'ଆଲୁଭିଆଲ୍',
    'cropRecommendation.location': 'ଅବସ୍ଥାନ',
    'cropRecommendation.locationPlaceholder': 'ସହର କିମ୍ୱା ଅଞ୍ଚଳ ପ୍ରବେଶ କରନ୍ତୁ',
    'cropRecommendation.season': 'ଋତୁ',
    'cropRecommendation.kharif': 'ଖରିଫ',
    'cropRecommendation.rabi': 'ରବି',
    'cropRecommendation.zaid': 'ଜାଇଦ୍',
    'cropRecommendation.waterAvailability': 'ଜଳ ଉପଲବ୍ଧତା',
    'cropRecommendation.abundant': 'ପ୍ରଚୁର ପରିମାଣରେ',
    'cropRecommendation.moderate': 'ମଧ୍ୟମ ଧରଣର',
    'cropRecommendation.limited': 'ସୀମିତ',
    'cropRecommendation.rainDependent': 'ବର୍ଷା ଉପରେ ନିର୍ଭରଶୀଳ',
    'cropRecommendation.fillRequiredFields': 'ଦୟାକରି ସମସ୍ତ ଆବଶ୍ୟକୀୟ ଫିଲ୍ଡ ପୂର୍ଣ୍ଣ କରନ୍ତୁ।',
    'cropRecommendation.generateRecommendations': 'ସୁପାରିଶକରଣଗୁଡିକ ସୃଷ୍ଟି କରନ୍ତୁ',
    'cropRecommendation.analyzing': 'ବିଶ୍ଳେଷଣ ...',
    'cropRecommendation.gettingRecommendations': 'ଆପଣଙ୍କ ଅଞ୍ଚଳ ପାଇଁ ସର୍ବୋତ୍ତମ ଫସଲ ସନ୍ଧାନ କରିବା...',
    'cropRecommendation.recommendationsReady': 'ସୁପାରିଶ ପ୍ରସ୍ତୁତ!',
    'cropRecommendation.yieldLabel': 'ଆଶା କରାଯାଉଥିବା ଅମଳ:',
    'cropRecommendation.waterLabel': 'ୱାଟର ରିକ୍ୟୁ:',
    'cropRecommendation.marketLabel': 'ବଜାର ମୂଲ୍ୟ:',
    'cropRecommendation.durationLabel': 'ଅବଧି:',
    'cropRecommendation.conditionsLabel': 'ସର୍ତ୍ତାବଳୀ:',
    'cropRecommendation.investmentLabel': 'ବିନିଯୋଗ:',
    'cropRecommendation.newSearch': 'ନୂତନ ସନ୍ଧାନ',
    'cropRecommendation.shareTitle': 'ଫସଲ ସୁପାରିଶ',
    'cropRecommendation.share': 'ଅଂଶୀଦାର କରନ୍ତୁ',
    'cropRecommendation.errorMessage': 'ସୁପାରିଶକରଣ ସୃଷ୍ଟି କରିବାରେ ତ୍ରୁଟି',
    'cropRecommendation.soilType': 'ମୃତ୍ତିକାର ପ୍ରକାର[ସମ୍ପାଦନା]',
  },
  as: {
    'crops.marketPrices': 'লাইভ মাণ্ডিৰ মূল্য',
    'crops.searchCrops': 'শস্যসমূহ সন্ধান কৰক...',
    'market.highpriceincrease': 'উচ্চ মূল্য বৃদ্ধি[সম্পাদনা কৰক]',
    'market.pricesdecline': 'মূল্য হ্ৰাস পাইছে',
    'market.stableprices': 'বজাৰ সুস্থিৰ',
    'crops.shopDetails': 'দোকানৰ বিৱৰণ',
    'crops.getDirections': 'দিশ প্ৰাপ্ত কৰক',
    'crops.callNow': 'এতিয়াই কল কৰক',
    'crops.availableItems': 'উপলব্ধ বস্তুসমূহ',
    'crops.distance': 'দূৰত্ব',
    'inputFinder.title': 'ইনপুট ফাইণ্ডাৰ',
    'inputFinder.description': 'ওচৰৰ দোকান বিচাৰক',
    'inputFinder.searchPlaceholder': 'ইনপুটসমূহ সন্ধান কৰক...',
    'inputFinder.allShops': 'সকলো দোকান',
    'inputFinder.pmkskCenters': 'পি.এম.কে.এছ.কে. কেন্দ্ৰসমূহ',
    'inputFinder.privateShops': 'ব্যক্তিগত দোকান',
    'inputFinder.kmAway': 'কিমি দূৰত',
    'inputFinder.currentPrices': 'বৰ্তমানৰ মূল্য',
    'inputFinder.callNow': 'এতিয়াই কল কৰক',
    'inputFinder.call': 'কল কৰক',
    'inputFinder.getDirections': 'দিশসমূহ',
    'dashboard.cropDiagnosis.title': 'শস্য নিৰ্ণয় (AI)',
    'dashboard.cropDiagnosis.description': 'আপোনাৰ ৰোগগ্ৰস্ত শস্যৰ ফটো এখন লওঁক...',
    'dashboard.cropDiagnosis.imageTooLarge': 'ছবি অত্যাধিক ডাঙৰ। অনুগ্ৰহ কৰি 5MBতকৈ সৰু এখন প্ৰতিচ্ছবি ব্যৱহাৰ কৰক।',
    'dashboard.cropDiagnosis.invalidFileType': 'অনুগ্ৰহ কৰি এটা বৈধ প্ৰতিচ্ছবি ফাইল আপল\'ড কৰক।',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'প্ৰতিচ্ছবি বিশ্লেষণ কৰিবলে ব্যৰ্থ। অনুগ্ৰহ কৰি ফটোখন পৰিষ্কাৰ হোৱাটো নিশ্চিত কৰক।',
    'dashboard.cropDiagnosis.note': 'AI বিশ্লেষণ 100% শুদ্ধ নহ\'বও পাৰে',
    'diagnosis.takePhoto': 'ফ\'টো লওক',
    'diagnosis.uploadFromGallery': 'গেলেৰীৰ পৰা বাছক',
    'diagnosis.tipsTitle': 'ভাল ফ\'টোসমূহৰ বাবে আভাস',
    'diagnosis.tip1': 'ভাল পোহৰ নিশ্চিত কৰক',
    'diagnosis.tip2': 'সংক্ৰমিত এলেকাৰ ওপৰত গুৰুত্ব দিয়ক',
    'diagnosis.tip3': 'পাত স্থিৰ কৰি ৰাখিব',
    'diagnosis.tip4': 'ছাঁ পৰিহাৰ কৰক',
    'diagnosis.cropImageAlt': 'ছবি ক্ৰপ কৰক',
    'diagnosis.remove': 'আতৰাওক',
    'diagnosis.analyzeWithAI': 'AI ৰ সৈতে বিশ্লেষণ কৰক',
    'diagnosis.retrying': 'পুনৰ চেষ্টা কৰা হৈছে',
    'diagnosis.analyzing': 'ক্ৰপ ছবি বিশ্লেষণ কৰা হৈছে...',
    'diagnosis.analyzingSubtext': 'বিসংগতিবোৰ চিনাক্ত কৰিবলৈ উন্নত ভিছন এএল ব্যৱহাৰ কৰা।',
    'diagnosis.analysisComplete': 'বিশ্লেষণ সম্পূৰ্ণ হৈছে',
    'diagnosis.laymanHealthy': 'ভাল খবৰ! আপোনাৰ {crop_name} টা শস্য স্বাস্থ্যৱান যেন লাগিছে। ইয়াক এনেদৰে ৰাখিবলৈ, সঠিক পানী দিয়াটো নিশ্চিত কৰক আৰু ভৱিষ্যতে যিকোনো সমস্যাৰ বাবে নিৰীক্ষণ কৰক।',
    'diagnosis.laymanDiseased': 'এনেকুৱা লাগিছে যে আপোনাৰ {crop_name} {disease_name}ৰ দ্বাৰা ভুগি আছে। আপুনি লক্ষ্য কৰিব পৰা কিছুমান সচৰাচৰ লক্ষণ হ\'ল {লক্ষণ}। ইয়াৰ চিকিৎসাৰ বাবে, আপুনি {treatment_organic}ৰ দৰে জৈৱিক দ্ৰৱণ বা {treatment_chemical}ৰ দৰে ৰাসায়নিক বিকল্প ব্যৱহাৰ কৰিব পাৰে। ভৱিষ্যতে প্ৰতিৰোধৰ বাবে, {প্ৰতিৰোধ}।',
    'cropRecommendation.title': 'শস্য উপদেষ্টা',
    'cropRecommendation.description': 'আপোনাৰ মাটি আৰু বতৰৰ ওপৰত ভিত্তি কৰি AI অনুমোদনসমূহ প্ৰাপ্ত কৰক',
    'cropRecommendation.loamy': 'লোমি',
    'cropRecommendation.clay': 'ক্লে',
    'cropRecommendation.sandy': 'চেণ্ডি',
    'cropRecommendation.silt': 'পলস',
    'cropRecommendation.redSoil': 'ৰঙা মাটি',
    'cropRecommendation.blackSoil': 'ক\'লা মাটি',
    'cropRecommendation.alluvial': 'পলসুৱা',
    'cropRecommendation.location': 'অৱস্থান',
    'cropRecommendation.locationPlaceholder': 'চহৰ অথবা অঞ্চল সুমুৱাওক',
    'cropRecommendation.season': 'ঋতু',
    'cropRecommendation.kharif': 'খাৰিফ',
    'cropRecommendation.rabi': 'ৰবি',
    'cropRecommendation.zaid': 'জাইদ',
    'cropRecommendation.waterAvailability': 'পানীৰ উপলব্ধতা[সম্পাদনা কৰক]',
    'cropRecommendation.abundant': 'প্ৰচুৰ পৰিমাণে',
    'cropRecommendation.moderate': 'মধ্যমীয়া',
    'cropRecommendation.limited': 'সীমিত',
    'cropRecommendation.rainDependent': 'বৰষুণ নিৰ্ভৰশীল',
    'cropRecommendation.fillRequiredFields': 'অনুগ্ৰহ কৰি সকলো প্ৰয়োজনীয় ফিল্ড পূৰণ কৰক।',
    'cropRecommendation.generateRecommendations': 'অনুমোদনসমূহ সৃজন কৰক',
    'cropRecommendation.analyzing': 'বিশ্লেষণ কৰা হৈছে...',
    'cropRecommendation.gettingRecommendations': 'আপোনাৰ অঞ্চলৰ বাবে সৰ্বশ্ৰেষ্ঠ শস্য বিচাৰি উলিওৱা...',
    'cropRecommendation.recommendationsReady': 'পৰামৰ্শ সাজু!',
    'cropRecommendation.yieldLabel': 'প্ৰত্যাশিত উৎপাদন:',
    'cropRecommendation.waterLabel': 'পানীৰ ৰেকিউ:',
    'cropRecommendation.marketLabel': 'বজাৰ মূল্য:',
    'cropRecommendation.durationLabel': 'অৱধি:',
    'cropRecommendation.conditionsLabel': 'চৰ্তসমূহ:',
    'cropRecommendation.investmentLabel': 'বিনিয়োগ:',
    'cropRecommendation.newSearch': 'নতুন সন্ধান',
    'cropRecommendation.shareTitle': 'শস্যৰ পৰামৰ্শ[সম্পাদনা কৰক]',
    'cropRecommendation.share': 'অংশীদাৰী',
    'cropRecommendation.errorMessage': 'অনুমোদন সৃজন কৰোতে ত্ৰুটি',
    'cropRecommendation.soilType': 'মাটিৰ প্ৰকাৰ',
  },
  ur: {
    'crops.marketPrices': 'لائیو منڈی قیمتیں',
    'crops.searchCrops': 'فصلوں کی تلاش...',
    'market.highpriceincrease': 'قیمتوں میں زیادہ اضافہ',
    'market.pricesdecline': 'قیمتیں کم ہو رہی ہیں',
    'market.stableprices': 'مارکیٹ مستحکم ہے',
    'crops.shopDetails': 'دکان کی تفصیلات',
    'crops.getDirections': 'ہدایات حاصل کریں',
    'crops.callNow': 'ابھی کال کریں',
    'crops.availableItems': 'دستیاب اشیاء',
    'crops.distance': 'فاصلہ',
    'inputFinder.title': 'ان پٹ فائنڈر',
    'inputFinder.description': 'قریبی دکانیں تلاش کریں',
    'inputFinder.searchPlaceholder': 'سرچ ان پٹس...',
    'inputFinder.allShops': 'تمام دکانیں',
    'inputFinder.pmkskCenters': 'PMKSK سینٹرز',
    'inputFinder.privateShops': 'نجی دکانیں',
    'inputFinder.kmAway': 'کلومیٹر دور',
    'inputFinder.currentPrices': 'موجودہ قیمتیں',
    'inputFinder.callNow': 'ابھی کال کریں',
    'inputFinder.call': 'کال',
    'inputFinder.getDirections': 'ہدایات',
    'dashboard.cropDiagnosis.title': 'فصل کی تشخیص (AI)',
    'dashboard.cropDiagnosis.description': 'اپنی بیمار فصل کی تصویر لو...',
    'dashboard.cropDiagnosis.imageTooLarge': 'تصویر بہت بڑی ہے۔ براہ کرم 5MB سے چھوٹی تصویر استعمال کریں۔',
    'dashboard.cropDiagnosis.invalidFileType': 'براہ کرم ایک درست امیج فائل اپلوڈ کریں۔',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'تصویر کا تجزیہ کرنے میں ناکام رہا۔ براہ کرم اس بات کو یقینی بنائیں کہ تصویر صاف ہو۔',
    'dashboard.cropDiagnosis.note': 'AI تجزیہ 100٪ درست نہیں ہو سکتا',
    'diagnosis.takePhoto': 'تصویر لیں',
    'diagnosis.uploadFromGallery': 'گیلری سے انتخاب کریں',
    'diagnosis.tipsTitle': 'اچھی تصاویر کے لیے تجاویز',
    'diagnosis.tip1': 'اچھی روشنی کو یقینی بنائیں',
    'diagnosis.tip2': 'متاثرہ علاقے پر توجہ مرکوز کریں',
    'diagnosis.tip3': 'پتہ کو مستحکم رکھیں',
    'diagnosis.tip4': 'سائے سے بچیں',
    'diagnosis.cropImageAlt': 'کراپ امیج',
    'diagnosis.remove': 'ہٹا دیا جائے',
    'diagnosis.analyzeWithAI': 'AI کے ساتھ تجزیہ کریں',
    'diagnosis.retrying': 'دوبارہ کوشش',
    'diagnosis.analyzing': 'کراپ امیج کا تجزیہ کر رہا ہوں...',
    'diagnosis.analyzingSubtext': 'غیر معمولی چیزوں کا پتہ لگانے کے لیے جدید وژن AI استعمال کرنا۔',
    'diagnosis.analysisComplete': 'تجزیہ مکمل',
    'diagnosis.laymanHealthy': 'زبردست خبر! آپ کی {crop_name} فصل صحت مند نظر آتی ہے۔ اس حالت کو برقرار رکھنے کے لیے، مناسب پانی دیں اور مستقبل کے مسائل کی نگرانی کریں۔',
    'diagnosis.laymanDiseased': 'ایسا لگتا ہے کہ آپ کا {crop_name} {disease_name} کا شکار ہے۔ کچھ عام علامات جو آپ نے محسوس کی ہوں گی وہ ہیں {علامات}۔ اس کے علاج کے لیے، آپ نامیاتی محلول جیسے {treatment_organic} یا کیمیکل آپشنز جیسے {treatment_chemical} استعمال کر سکتے ہیں۔ مستقبل میں روک تھام کے لیے، {روک تھام}۔',
    'cropRecommendation.title': 'فصلوں کے مشیر',
    'cropRecommendation.description': 'اپنی مٹی اور موسم کی بنیاد پر AI کی سفارشات حاصل کریں',
    'cropRecommendation.loamy': 'لوئمی',
    'cropRecommendation.clay': 'کلی',
    'cropRecommendation.sandy': 'سینڈی',
    'cropRecommendation.silt': 'مٹی',
    'cropRecommendation.redSoil': 'سرخ مٹی',
    'cropRecommendation.blackSoil': 'بلیک سوائل',
    'cropRecommendation.alluvial': 'الویول',
    'cropRecommendation.location': 'مقام',
    'cropRecommendation.locationPlaceholder': 'شہر یا علاقہ داخل کریں',
    'cropRecommendation.season': 'سیزن',
    'cropRecommendation.kharif': 'خریف',
    'cropRecommendation.rabi': 'رابی',
    'cropRecommendation.zaid': 'زید',
    'cropRecommendation.waterAvailability': 'پانی کی دستیابی',
    'cropRecommendation.abundant': 'وافر',
    'cropRecommendation.moderate': 'درمیانے درجے کا',
    'cropRecommendation.limited': 'محدود',
    'cropRecommendation.rainDependent': 'بارش پر منحصر',
    'cropRecommendation.fillRequiredFields': 'براہ کرم تمام ضروری فیلڈز پر کریں۔',
    'cropRecommendation.generateRecommendations': 'سفارشات تیار کریں',
    'cropRecommendation.analyzing': 'تجزیہ کر رہا ہوں...',
    'cropRecommendation.gettingRecommendations': 'اپنے علاقے کے لیے بہترین فصلیں تلاش کرنا...',
    'cropRecommendation.recommendationsReady': 'سفارشات تیار ہیں!',
    'cropRecommendation.yieldLabel': 'متوقع پیداوار:',
    'cropRecommendation.waterLabel': 'پانی کی ضرورت:',
    'cropRecommendation.marketLabel': 'مارکیٹ قیمت:',
    'cropRecommendation.durationLabel': 'دورانیہ:',
    'cropRecommendation.conditionsLabel': 'شرائط:',
    'cropRecommendation.investmentLabel': 'سرمایہ کاری:',
    'cropRecommendation.newSearch': 'نیو سرچ',
    'cropRecommendation.shareTitle': 'فصلوں کی سفارشات',
    'cropRecommendation.share': 'شیئر کریں',
    'cropRecommendation.errorMessage': 'ایرر جنریٹڈ سفارش',
    'cropRecommendation.soilType': 'مٹی کی قسم',
  },
  ne: {
    'crops.marketPrices': 'जिउँदो मन्डीको मूल्य',
    'crops.searchCrops': 'बालीहरू खोजी गर्नुहोस्...',
    'market.highpriceincrease': 'उच्च मूल्य वृद्धि[सम्पादन गर्ने]',
    'market.pricesdecline': 'मूल्य घट्दै गएको छ ।',
    'market.stableprices': 'बजार स्थिर छ',
    'crops.shopDetails': 'विवरण किन्नुहोस्',
    'crops.getDirections': 'दिशाहरू प्राप्त गर्नुहोस्',
    'crops.callNow': 'अहिले कल गर्नुहोस्',
    'crops.availableItems': 'उपलब्ध वस्तुहरू',
    'crops.distance': 'दूरी',
    'inputFinder.title': 'आगत खोजी',
    'inputFinder.description': 'नजिकैको पसलहरू फेला पार्नुहोस्',
    'inputFinder.searchPlaceholder': 'आगतहरू खोजी गर्नुहोस्...',
    'inputFinder.allShops': 'सबै पसलहरू',
    'inputFinder.pmkskCenters': 'पीएमकेएसके केन्द्रहरू',
    'inputFinder.privateShops': 'निजी पसलहरू[सम्पादन गर्ने]',
    'inputFinder.kmAway': 'कि.मि. टाढा',
    'inputFinder.currentPrices': 'हालको मूल्य[सम्पादन गर्ने]',
    'inputFinder.callNow': 'अहिले कल गर्नुहोस्',
    'inputFinder.call': 'कल गर्नुहोस्',
    'inputFinder.getDirections': 'दिशाहरू',
    'dashboard.cropDiagnosis.title': 'बाली निदान (एआई)',
    'dashboard.cropDiagnosis.description': 'तपाईंको रोगग्रस्त बालीको फोटो लिनुहोस् ...',
    'dashboard.cropDiagnosis.imageTooLarge': 'छवि धेरै ठूलो छ । कृपया 5MB भन्दा सानो छवि प्रयोग गर्नुहोस्।',
    'dashboard.cropDiagnosis.invalidFileType': 'कृपया वैध छवि फाइल अपलोड गर्नुहोस् ।',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'छवि विश्लेषण गर्न असफल भयो । कृपया फोटो स्पष्ट छ सुनिश्चित गर्नुहोस्।',
    'dashboard.cropDiagnosis.note': 'एआई विश्लेषण १००% सही नहुन सक्छ',
    'diagnosis.takePhoto': 'फोटो लिनुहोस्',
    'diagnosis.uploadFromGallery': 'ग्यालरीबाट रोज्नुहोस्',
    'diagnosis.tipsTitle': 'राम्रो फोटोको लागि सुझावहरू',
    'diagnosis.tip1': 'राम्रो प्रकाश सुनिश्चित गर्नुहोस्',
    'diagnosis.tip2': 'संक्रमित क्षेत्रमा ध्यान दिनुहोस्',
    'diagnosis.tip3': 'पातलाई स्थिर राख्नुहोस्',
    'diagnosis.tip4': 'छायाँ परित्याग गर्नुहोस्',
    'diagnosis.cropImageAlt': 'छवि काँटछाँट गर्नुहोस्',
    'diagnosis.remove': 'हटाउनुहोस्',
    'diagnosis.analyzeWithAI': 'AI सँग विश्लेषण गर्नुहोस्',
    'diagnosis.retrying': 'पुन: प्रयास गर्दै',
    'diagnosis.analyzing': 'काँटछाँट छवि विश्लेषण गर्दैछ...',
    'diagnosis.analyzingSubtext': 'विसंगतिहरू पत्ता लगाउन उन्नत भिजन एआई प्रयोग गर्दै।',
    'diagnosis.analysisComplete': 'विश्लेषण पूरा भयो',
    'diagnosis.laymanHealthy': 'शुभ समाचार! तपाईंको crop_name बाली स्वस्थ देखिन्छ। यसलाई यसरी राख्नको लागि, उचित पानी सुनिश्चित गर्नुहोस् र भविष्यका कुनै पनि समस्याहरूको लागि निगरानी गर्नुहोस्।',
    'diagnosis.laymanDiseased': 'यस्तो देखिन्छ कि तपाईंको {crop_name} {disease_name} बाट पीडित छ। तपाईंले देख्नुभएका केही सामान्य लक्षणहरू {लक्षणहरू} हुन्। यसको उपचार गर्न, तपाईं {treatment_organic} जस्ता जैविक समाधानहरू वा {treatment_chemical} जस्ता रासायनिक विकल्पहरू प्रयोग गर्न सक्नुहुनेछ। भविष्यमा रोकथामको लागि, {रोकथाम}।',
    'cropRecommendation.title': 'बाली सल्लाहकार',
    'cropRecommendation.description': 'तपाईंको माटो र मौसममा आधारित एआई सिफारिसहरू प्राप्त गर्नुहोस्',
    'cropRecommendation.loamy': 'दोमट',
    'cropRecommendation.clay': 'माटो',
    'cropRecommendation.sandy': 'स्यान्डी',
    'cropRecommendation.silt': 'सिल्ट',
    'cropRecommendation.redSoil': 'रातो माटो',
    'cropRecommendation.blackSoil': 'कालो माटो',
    'cropRecommendation.alluvial': 'जलोढ',
    'cropRecommendation.location': 'स्थान',
    'cropRecommendation.locationPlaceholder': 'शहर वा क्षेत्र प्रविष्ट गर्नुहोस्',
    'cropRecommendation.season': 'सिजन',
    'cropRecommendation.kharif': 'खरिफ खरिद[सम्पादन',
    'cropRecommendation.rabi': 'रबि',
    'cropRecommendation.zaid': 'जैद',
    'cropRecommendation.waterAvailability': 'पानीको उपलब्धता',
    'cropRecommendation.abundant': 'प्रशस्त मात्रामा',
    'cropRecommendation.moderate': 'मध्यम',
    'cropRecommendation.limited': 'सिमित',
    'cropRecommendation.rainDependent': 'वर्षा निर्भर',
    'cropRecommendation.fillRequiredFields': 'कृपया सबै आवश्यक फाँटहरू भर्नुहोस् ।',
    'cropRecommendation.generateRecommendations': 'सिफारिसहरू उत्पन्न गर्नुहोस्',
    'cropRecommendation.analyzing': 'विश्लेषण गर्दै...',
    'cropRecommendation.gettingRecommendations': 'तपाईंको क्षेत्रको लागि उत्तम बालीहरू फेला पार्दै...',
    'cropRecommendation.recommendationsReady': 'सिफारिसहरू तयार छन्!',
    'cropRecommendation.yieldLabel': 'अपेक्षित उपज:',
    'cropRecommendation.waterLabel': 'पानीको प्रश्न:',
    'cropRecommendation.marketLabel': 'बजार मूल्य[सम्पादन गर्ने]',
    'cropRecommendation.durationLabel': 'अवधि:',
    'cropRecommendation.conditionsLabel': 'सर्तहरू:',
    'cropRecommendation.investmentLabel': 'लगानी:',
    'cropRecommendation.newSearch': 'नयाँ खोजी',
    'cropRecommendation.shareTitle': 'बाली सिफारिसहरू',
    'cropRecommendation.share': 'बाँडफाँड गर्नुहोस्',
    'cropRecommendation.errorMessage': 'सिफारिस सिर्जना गर्दा त्रुटि',
    'cropRecommendation.soilType': 'माटोको प्रकार',
  },
  mai: {
    'crops.marketPrices': 'लाइव मंडीक दाम',
    'crops.searchCrops': 'फसलसभकेँ खोजू...',
    'market.highpriceincrease': 'लेल बेसी दाम वृद्धि',
    'market.pricesdecline': 'दाम घटि रहल अछि',
    'market.stableprices': 'बाजार के लेल स्थिर अछि',
    'crops.shopDetails': 'भंडारक विवरण',
    'crops.getDirections': 'दिशा पाबू',
    'crops.callNow': 'आब कॉल करू',
    'crops.availableItems': 'मोजुद मद',
    'crops.distance': 'दूरी',
    'inputFinder.title': 'इनपुट खोजकएनिहार',
    'inputFinder.description': 'लगपासक दोकान ताकू',
    'inputFinder.searchPlaceholder': 'अनुसन्धान इनपुट...',
    'inputFinder.allShops': 'सभटा दोकान',
    'inputFinder.pmkskCenters': 'पीएमकेएसके केंद्र',
    'inputFinder.privateShops': 'निजी दोकानसभ',
    'inputFinder.kmAway': 'किमी दूर',
    'inputFinder.currentPrices': 'मोजुदा दाम',
    'inputFinder.callNow': 'आब कॉल करू',
    'inputFinder.call': 'कॉल',
    'inputFinder.getDirections': 'दिशा',
    'dashboard.cropDiagnosis.title': 'फसल निदान (AI)',
    'dashboard.cropDiagnosis.description': 'अपन रोगग्रस्त फसलक फोटो लिअ...',
    'dashboard.cropDiagnosis.imageTooLarge': 'चित्र बहुत पैघ अछि। कृपया 5MB सँ छोट चित्रक प्रयोग करू।',
    'dashboard.cropDiagnosis.invalidFileType': 'कृप्या एकटा मान्य चित्र फाइल अपलोड करू.',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'बिंब विश्लेषण मे विफल. कृपया फोटो साफ होएबाक सुनिश्चित करू।',
    'dashboard.cropDiagnosis.note': 'एआई विश्लेषण १००% सटीक नहि भऽ सकैत अछि',
    'diagnosis.takePhoto': 'फोटो खिचू',
    'diagnosis.uploadFromGallery': 'गेलरीसँ चुनू',
    'diagnosis.tipsTitle': 'नीक फोटोक लेल टिप्स',
    'diagnosis.tip1': 'नीक प्रकाश सुनिश्चित करू',
    'diagnosis.tip2': 'संक्रमित क्षेत्र पर केन्द्रित करू',
    'diagnosis.tip3': 'पत्ता के स्थिर राखू।',
    'diagnosis.tip4': 'छायासँ परहेज करू',
    'diagnosis.cropImageAlt': 'चित्र काटू',
    'diagnosis.remove': 'हटाबू (v)',
    'diagnosis.analyzeWithAI': 'AI क\' सँग विश्लेषण करू',
    'diagnosis.retrying': 'फिनु कोसिस कए रहल अछि',
    'diagnosis.analyzing': 'काटू चित्र विश्लेषण कए रहल अछि',
    'diagnosis.analyzingSubtext': 'विसंगतिसभक पता लगएबाक लेल उन्नत दृष्टि AI केर उपयोग करब।',
    'diagnosis.analysisComplete': 'विश्लेषण पूर्ण भेल',
    'diagnosis.laymanHealthy': 'नीक खबर! अहाँक {crop_name} फसल स्वस्थ देखाइत अछि। एकरा एहि तरहें रखबाक लेल, उचित पानि सुनिश्चित करू आ भविष्यमे कोनो समस्याक लेल निगरानी करू।',
    'diagnosis.laymanDiseased': 'एहन लगैत अछि जे अहाँक {crop_name} {disease_name} सँ पीड़ित अछि। किछु सामान्य लक्षण जे अहाँ देखने होएब ओ अछि {लक्षण}। एकर इलाज कें लेल अहां जैविक घोल जेना {treatment_organic} या रासायनिक विकल्प जेना {treatment_chemical} कें उपयोग क\' सकय छी. भविष्यमे रोकथामक लेल, {रोकथाम}.',
    'cropRecommendation.title': 'फसल सलाहकार',
    'cropRecommendation.description': 'अपन माटि आ मौसमक आधार पर AI अनुशंसासभ प्राप्त करू',
    'cropRecommendation.loamy': 'दोम',
    'cropRecommendation.clay': 'माटि',
    'cropRecommendation.sandy': 'सैंडी',
    'cropRecommendation.silt': 'गाद',
    'cropRecommendation.redSoil': 'लाल माइट',
    'cropRecommendation.blackSoil': 'करिया माटि',
    'cropRecommendation.alluvial': 'जलोढ़',
    'cropRecommendation.location': 'कनेक्शनसभ',
    'cropRecommendation.locationPlaceholder': 'नगर अथवा क्षेत्र दाखिल करू',
    'cropRecommendation.season': 'मौसम',
    'cropRecommendation.kharif': 'खरीफ',
    'cropRecommendation.rabi': 'रबि',
    'cropRecommendation.zaid': 'जाइद',
    'cropRecommendation.waterAvailability': 'पानिक उपलब्धता',
    'cropRecommendation.abundant': 'प्रचुर मात्रा मे',
    'cropRecommendation.moderate': 'मध्यम',
    'cropRecommendation.limited': 'सीमित',
    'cropRecommendation.rainDependent': 'पाइन निर्भर',
    'cropRecommendation.fillRequiredFields': 'कृप्या सभटा आवश्यक क्षेत्र भरू.',
    'cropRecommendation.generateRecommendations': 'अनुशंसासभ उत्पन्न करू',
    'cropRecommendation.analyzing': 'विश्लेषण कए रहल अछि...',
    'cropRecommendation.gettingRecommendations': 'अपन क्षेत्रक लेल सबसँ नीक फसल ताकब ...',
    'cropRecommendation.recommendationsReady': 'अनुशंसासभ तैयार!',
    'cropRecommendation.yieldLabel': 'अपेक्षित उपज:',
    'cropRecommendation.waterLabel': 'जल अनुरोध:',
    'cropRecommendation.marketLabel': 'बाजार मूल्य:',
    'cropRecommendation.durationLabel': 'अवधि:',
    'cropRecommendation.conditionsLabel': 'शर्तसभ:',
    'cropRecommendation.investmentLabel': 'निवेश:',
    'cropRecommendation.newSearch': 'नब खोज',
    'cropRecommendation.shareTitle': 'काटू सुझाव',
    'cropRecommendation.share': 'बाँटू',
    'cropRecommendation.errorMessage': 'सिफारिश उत्पन्न करबामे त्रुटि',
    'cropRecommendation.soilType': 'माटिक प्रकार',
  },
  mni: {
    'crops.marketPrices': 'ꯂꯥꯏꯕ ꯃꯟꯗꯤꯒꯤ ꯃꯃꯜꯁꯤꯡ',
    'crops.searchCrops': 'ꯃꯍꯩ ꯃꯔꯣꯡꯁꯤꯡ ꯊꯤꯌꯨ...',
    'market.highpriceincrease': 'ꯃꯃꯜ ꯋꯥꯡꯅ ꯍꯦꯟꯒꯠꯂꯛꯄ',
    'market.pricesdecline': 'ꯃꯃꯜꯁꯤꯡ ꯍꯟꯊꯔꯛꯂꯤ',
    'market.stableprices': 'ꯀꯩꯊꯦꯜ ꯑꯁꯤ ꯂꯦꯡꯗꯅ ꯂꯩ',
    'crops.shopDetails': 'ꯗꯨꯀꯥꯟꯒꯤ ꯑꯀꯨꯞꯄ ꯃꯔꯣꯜ',
    'crops.getDirections': 'ꯃꯥꯏꯀꯩ ꯂꯧꯔꯛꯎ',
    'crops.callNow': 'ꯍꯧꯖꯤꯛ ꯐꯣꯟ ꯇꯧ',
    'crops.availableItems': 'ꯐꯪꯂꯤꯕ ꯄꯣꯠꯂꯝꯁꯤꯡ',
    'crops.distance': 'ꯑꯔꯥꯞꯄ',
    'inputFinder.title': 'ꯏꯟꯄꯨꯠ ꯐꯥꯏꯟꯗꯔ',
    'inputFinder.description': 'ꯃꯅꯥꯛ ꯅꯛꯄ ꯗꯨꯀꯥꯟꯁꯤꯡ ꯊꯤꯔꯛꯎ',
    'inputFinder.searchPlaceholder': 'ꯏꯟꯄꯨꯠꯁꯤꯡ ꯊꯤꯌꯨ...',
    'inputFinder.allShops': 'ꯗꯨꯀꯥꯟ ꯄꯨꯝꯅꯃꯛ',
    'inputFinder.pmkskCenters': 'ꯄꯤ.ꯑꯦꯝ.ꯀꯦ.ꯑꯦꯁ.ꯀꯦ. ꯁꯦꯟꯇꯔꯁꯤꯡ',
    'inputFinder.privateShops': 'ꯂꯅꯥꯏꯒꯤ ꯗꯨꯀꯥꯟꯁꯤꯡ',
    'inputFinder.kmAway': 'ꯀꯤꯂꯣꯃꯤꯇꯔ ꯂꯥꯞꯅ',
    'inputFinder.currentPrices': 'ꯍꯧꯖꯤꯛꯀꯤ ꯃꯃꯜꯁꯤꯡ',
    'inputFinder.callNow': 'ꯍꯧꯖꯤꯛ ꯐꯣꯟ ꯇꯧ',
    'inputFinder.call': 'ꯀꯣꯜ ꯇꯧ',
    'inputFinder.getDirections': 'ꯃꯥꯏꯀꯩꯁꯤꯡ',
    'dashboard.cropDiagnosis.title': 'ꯃꯍꯩ ꯃꯔꯣꯡꯒꯤ ꯃꯁꯛ ꯈꯪꯗꯣꯛꯄ (ꯑꯦꯑꯏ)',
    'dashboard.cropDiagnosis.description': 'ꯅꯍꯥꯛꯀꯤ ꯂꯩꯅꯥ ꯂꯩꯔꯕ ꯃꯍꯩ ꯃꯔꯣꯡꯒꯤ ꯐꯣꯇꯣ ꯑꯃ ꯂꯧꯕꯤꯌꯨ...',
    'dashboard.cropDiagnosis.imageTooLarge': 'ꯃꯃꯤ ꯌꯥꯝꯅ ꯆꯥꯎꯋꯤ꯫ ꯆꯥꯟꯕꯤꯗꯨꯅ ꯵ꯑꯦꯝꯕꯤꯗꯒꯤ ꯍꯦꯟꯅ ꯄꯤꯛꯄ ꯃꯃꯤ ꯑꯃ ꯁꯤꯖꯤꯟꯅꯕꯤꯌꯨ꯫',
    'dashboard.cropDiagnosis.invalidFileType': 'ꯆꯥꯟꯕꯤꯗꯨꯅ ꯆꯠꯅꯕ ꯌꯥꯕ ꯏꯃꯦꯖ ꯐꯥꯏꯜ ꯑꯃ ꯑꯞꯂꯣꯗ ꯇꯧꯕꯤꯌꯨ꯫',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'ꯃꯃꯤ ꯑꯗꯨ ꯅꯩꯅꯕ ꯉꯝꯈꯤꯗꯦ꯫ ꯆꯥꯟꯕꯤꯗꯨꯅ ꯐꯣꯇꯣ ꯑꯗꯨ ꯃꯌꯦꯛ ꯁꯦꯡꯅ ꯈꯪꯍꯟꯕꯤꯌꯨ꯫',
    'dashboard.cropDiagnosis.note': 'ꯑꯦꯑꯏꯒꯤ ꯅꯩꯅꯕ ꯑꯁꯤ ꯆꯥꯗ ꯱꯰꯰% ꯆꯞ ꯆꯥꯕ ꯑꯣꯏꯗꯕ ꯌꯥꯏ',
    'diagnosis.takePhoto': 'ꯐꯣꯇꯣ ꯂꯧꯎ',
    'diagnosis.uploadFromGallery': 'ꯒꯦꯂꯔꯤꯗꯒꯤ ꯈꯜꯂꯨ',
    'diagnosis.tipsTitle': 'ꯑꯐꯕ ꯐꯣꯇꯣꯁꯤꯡꯒꯤ ꯇꯤꯞꯁꯤꯡ',
    'diagnosis.tip1': 'ꯃꯉꯥꯜ ꯐꯖꯅ ꯐꯪꯍꯟꯒꯗꯕꯅꯤ',
    'diagnosis.tip2': 'ꯂꯥꯏꯅꯥ ꯂꯩꯔꯕ ꯃꯐꯝꯗ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯃꯨ',
    'diagnosis.tip3': 'ꯃꯅꯥ ꯑꯗꯨ ꯂꯦꯡꯗꯅ ꯊꯝꯃꯨ',
    'diagnosis.tip4': 'ꯑꯀꯨꯞꯄ ꯃꯀꯨ ꯂꯩꯍꯟꯒꯅꯨ',
    'diagnosis.cropImageAlt': 'ꯀ꯭ꯔꯣꯞ ꯏꯃꯦꯖ',
    'diagnosis.remove': 'ꯂꯧꯊꯣꯛꯎ',
    'diagnosis.analyzeWithAI': 'ꯑꯦꯑꯏꯒ ꯂꯣꯏꯅꯅ ꯅꯩꯅꯕ',
    'diagnosis.retrying': 'ꯑꯃꯨꯛ ꯍꯟꯅ ꯍꯣꯠꯅꯕ',
    'diagnosis.analyzing': 'ꯃꯍꯩ ꯃꯔꯣꯡꯒꯤ ꯃꯃꯤ ꯑꯗꯨ ꯅꯩꯅꯕ...',
    'diagnosis.analyzingSubtext': 'ꯈꯦꯟꯅꯕꯁꯤꯡ ꯈꯪꯗꯣꯛꯅꯕ ꯍꯦꯟꯅ ꯐꯒꯠꯂꯕ ꯚꯤꯖꯟ ꯑꯦꯑꯥꯏ ꯁꯤꯖꯤꯟꯅꯕ꯫',
    'diagnosis.analysisComplete': 'ꯅꯩꯅꯕ ꯃꯄꯨꯡ ꯐꯥꯔꯦ',
    'diagnosis.laymanHealthy': 'ꯑꯐꯕ ꯄꯥꯎ! ꯅꯍꯥꯛꯀꯤ {crop_name} ꯃꯍꯩ ꯃꯔꯣꯡ ꯑꯗꯨ ꯍꯛꯆꯥꯡ ꯐꯕ ꯃꯥꯜꯂꯤ꯫ ꯃꯁꯤ ꯑꯁꯨꯝꯅ ꯊꯝꯅꯕꯒꯤꯗꯃꯛ, ꯇꯨꯡꯗ ꯊꯣꯛꯂꯛꯄ ꯈꯨꯗꯣꯡꯊꯤꯅꯤꯡꯉꯥꯏ ꯑꯣꯏꯔꯕꯗꯤ ꯃꯇꯤꯛ ꯆꯥꯅ ꯏꯁꯤꯡ ꯄꯤꯒꯗꯧꯕ ꯑꯃꯁꯨꯡ ꯌꯦꯡꯁꯤꯟꯕꯤꯌꯨ꯫',
    'diagnosis.laymanDiseased': 'ꯅꯍꯥꯛꯀꯤ {crop_name} ꯑꯁꯤ {disease_name} ꯅ ꯅꯥꯕꯒꯨꯝ ꯇꯧꯋꯤ꯫ ꯅꯍꯥꯛꯅ ꯎꯔꯛꯄ ꯌꯥꯕ ꯇꯣꯏꯅ ꯐꯪꯕ ꯂꯥꯏꯑꯣꯡ ꯈꯔꯗꯤ {ꯂꯥꯏꯑꯣꯡ}ꯅꯤ꯫ ꯃꯁꯤ ꯂꯥꯌꯦꯡꯅꯕ, ꯅꯍꯥꯛꯅ {treatment_organic}ꯒꯨꯝꯕ ꯑꯣꯔꯒꯥꯅꯤꯛ ꯁꯣꯂꯨꯁꯟꯁꯤꯡ ꯅꯠꯇ꯭ꯔꯒ {treatment_chemical}ꯒꯨꯝꯕ ꯀꯦꯃꯤꯀꯦꯜ ꯑꯣꯞꯁꯟꯁꯤꯡ ꯁꯤꯖꯤꯟꯅꯕ ꯌꯥꯏ꯫ ꯇꯨꯡꯗ ꯉꯥꯛꯊꯣꯛꯅꯕꯒꯤꯗꯃꯛ, {prevent}.',
    'cropRecommendation.title': 'ꯀ꯭ꯔꯣꯞ ꯑꯦꯗꯚꯥꯏꯖꯔ',
    'cropRecommendation.description': 'ꯅꯍꯥꯛꯀꯤ ꯂꯩꯍꯥꯎ ꯑꯃꯁꯨꯡ ꯑꯌꯤꯡ ꯑꯁꯥꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯑꯦꯑꯏꯒꯤ ꯄꯥꯎꯇꯥꯛꯁꯤꯡ ꯂꯧꯕꯤꯌꯨ',
    'cropRecommendation.loamy': 'ꯂꯣꯃꯤ',
    'cropRecommendation.clay': 'ꯀ꯭ꯂꯦ',
    'cropRecommendation.sandy': 'ꯁꯦꯟꯗꯤ',
    'cropRecommendation.silt': 'ꯂꯩꯈꯣꯝ-ꯂꯩꯈꯣꯝ',
    'cropRecommendation.redSoil': 'ꯑꯉꯥꯡꯕ ꯂꯩꯍꯥꯎ',
    'cropRecommendation.blackSoil': 'ꯑꯃꯨꯕ ꯂꯩꯍꯥꯎ',
    'cropRecommendation.alluvial': 'ꯑꯦꯂꯨꯚꯤꯌꯦꯜ',
    'cropRecommendation.location': 'ꯃꯐꯝ',
    'cropRecommendation.locationPlaceholder': 'ꯁꯍꯔ ꯅꯠꯇ꯭ꯔꯒ ꯂꯝꯗꯝ ꯆꯪꯉꯨ',
    'cropRecommendation.season': 'ꯁꯤꯖꯟ',
    'cropRecommendation.kharif': 'ꯈꯥꯔꯤꯐ',
    'cropRecommendation.rabi': 'ꯔꯕꯤ',
    'cropRecommendation.zaid': 'ꯖꯥꯏꯗ',
    'cropRecommendation.waterAvailability': 'ꯏꯁꯤꯡ ꯐꯪꯕ',
    'cropRecommendation.abundant': 'ꯃꯔꯥꯡ ꯀꯥꯏꯅ',
    'cropRecommendation.moderate': 'ꯃꯌꯥꯏ ꯑꯣꯏꯕ',
    'cropRecommendation.limited': 'ꯂꯤꯃꯤꯇꯦꯗ',
    'cropRecommendation.rainDependent': 'ꯅꯣꯡ ꯃꯈꯥ ꯄꯣꯟꯕ',
    'cropRecommendation.fillRequiredFields': 'ꯆꯥꯟꯕꯤꯗꯨꯅ ꯃꯊꯧ ꯇꯥꯕ ꯐꯤꯜ꯭ꯗ ꯄꯨꯝꯅꯃꯛ ꯃꯦꯟꯁꯤꯟꯕꯤꯌꯨ꯫',
    'cropRecommendation.generateRecommendations': 'ꯔꯤꯀꯃꯦꯟꯗꯦꯁꯟꯁꯤꯡ ꯁꯦꯝꯃꯨ',
    'cropRecommendation.analyzing': 'ꯅꯩꯅꯕ...',
    'cropRecommendation.gettingRecommendations': 'ꯅꯍꯥꯛꯀꯤ ꯂꯝꯗꯝꯒꯤꯗꯃꯛ ꯈ꯭ꯋꯥꯏꯗꯒꯤ ꯐꯕ ꯃꯍꯩ-ꯃꯔꯣꯡꯁꯤꯡ ꯊꯤꯕ...',
    'cropRecommendation.recommendationsReady': 'ꯔꯤꯀꯃꯦꯟꯗꯦꯁꯟꯁꯤꯡ ꯁꯦꯝ ꯁꯥꯔꯦ!',
    'cropRecommendation.yieldLabel': 'ꯑꯣꯏꯔꯛꯄ ꯌꯥꯕ ꯄꯣꯠꯊꯣꯛ:',
    'cropRecommendation.waterLabel': 'ꯏꯁꯤꯡ ꯔꯤꯛ:',
    'cropRecommendation.marketLabel': 'ꯀꯩꯊꯦꯜꯒꯤ ꯃꯃꯜ:',
    'cropRecommendation.durationLabel': 'ꯃꯇꯝ:',
    'cropRecommendation.conditionsLabel': 'ꯐꯤꯕꯝꯁꯤꯡ:',
    'cropRecommendation.investmentLabel': 'ꯁꯦꯜ ꯊꯥꯗꯕ:',
    'cropRecommendation.newSearch': 'ꯑꯅꯧꯕ ꯊꯤꯅꯕ',
    'cropRecommendation.shareTitle': 'ꯃꯍꯩ ꯃꯔꯣꯡꯒꯤ ꯄꯥꯎꯇꯥꯛ',
    'cropRecommendation.share': 'ꯁꯦꯌꯔ',
    'cropRecommendation.errorMessage': 'ꯔꯤꯀꯃꯦꯟꯗꯦꯁꯟ ꯁꯦꯝꯕꯗ ꯑꯁꯣꯏꯕ',
    'cropRecommendation.soilType': 'ꯂꯩꯍꯥꯎ ꯃꯈꯜ',
  },
  doi: {
    'crops.marketPrices': 'लाइव मंडी दियां कीमतां',
    'crops.searchCrops': 'फसलें दी खोज करो...',
    'market.highpriceincrease': 'लेई उच्चे मुल्ल च बाद्धा',
    'market.pricesdecline': 'कीमतें च गिरावट दर्ज कीती जा\'रदी ऐ।',
    'market.stableprices': 'बजार स्थिर ऐ',
    'crops.shopDetails': 'दकानें दा ब्यौरा',
    'crops.getDirections': 'दिशा-निर्देश हासल करो',
    'crops.callNow': 'हुनै काल करो',
    'crops.availableItems': 'उपलब्ध चीजां',
    'crops.distance': 'दूरी',
    'inputFinder.title': 'इनपुट खोजक',
    'inputFinder.description': 'आस्सै-पास्सै दियां हट्टियां तुप्पो',
    'inputFinder.searchPlaceholder': 'इनपुट खोजें...',
    'inputFinder.allShops': 'सब्भै हट्टियां',
    'inputFinder.pmkskCenters': 'पी.एम.के.एस.के. केंदर',
    'inputFinder.privateShops': 'निजी हट्टियां',
    'inputFinder.kmAway': 'कि.मी. दूर',
    'inputFinder.currentPrices': 'मजूदा मुल्ल',
    'inputFinder.callNow': 'हुनै काल करो',
    'inputFinder.call': 'काल',
    'inputFinder.getDirections': 'दिशा-निर्देश',
    'dashboard.cropDiagnosis.title': 'फसल दा निदान (AI)',
    'dashboard.cropDiagnosis.description': 'अपनी रोगग्रस्त फसल दा इक फोटो लैओ...',
    'dashboard.cropDiagnosis.imageTooLarge': 'छवि बड़ी बड्डी ऐ। कृपा करियै 5MB थमां लौह् की छवि दा इस्तेमाल करो।',
    'dashboard.cropDiagnosis.invalidFileType': 'कृपा करियै इक मान्य छवि फाइल अपलोड करो।',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'छवि दा विश्लेशण करने च नाकाम रेहा। कृपा करियै इस गल्लै दा ध्यान रक्खो जे फोटो साफ होऐ।',
    'dashboard.cropDiagnosis.note': 'एआई विश्लेशन 100 % सटीक नेईं होई सकदा ऐ',
    'diagnosis.takePhoto': 'फोटो खिच्चो',
    'diagnosis.uploadFromGallery': 'गैलरी चा चुनो',
    'diagnosis.tipsTitle': 'शैल फोटो लेई टिप्स',
    'diagnosis.tip1': 'अच्छी लोऽ यकीनी बनाओ',
    'diagnosis.tip2': 'संक्रमत खेतर पर ध्यान देओ',
    'diagnosis.tip3': 'पत्ती गी स्थिर रक्खो',
    'diagnosis.tip4': 'परछाई शा बचो',
    'diagnosis.cropImageAlt': 'छवि गी क्रॉप करो',
    'diagnosis.remove': 'हटाओ',
    'diagnosis.analyzeWithAI': 'एआई कन्नै विश्लेशन करो',
    'diagnosis.retrying': 'परतियै कोशश करना',
    'diagnosis.analyzing': 'फसल छवि दा विश्लेशण करना...',
    'diagnosis.analyzingSubtext': 'विसंगतियें दा पता लाने लेई उन्नत विजन एआई दा इस्तेमाल करना।',
    'diagnosis.analysisComplete': 'विश्लेशन पूरा',
    'diagnosis.laymanHealthy': 'बड़ी खुशखबरी ! तुंʼदी {crop_name} फसल सेह्तमंद दिखदी ऐ। इसगी इस चाल्ली रक्खने आस्तै, ठीक पानी देना यकीनी बनाओ ते भविक्ख च कुसै बी समस्या दी निगरानी करो।',
    'diagnosis.laymanDiseased': 'इ\'यां लगदा ऐ जे तुंʼदा {crop_name} {disease_name} बमारी कन्नै पीड़त ऐ। किश सधारण लच्छन तुसें दिक्खे होङन ओह् न {लक्षण}। एह्दे इलाज लेई तुस {treatment_organic} जनेह् जैविक घोल जां {treatment_chemical} जनेह् रसैनक विकल्पें दा इस्तेमाल करी सकदे ओ। भविक्ख च रोकथाम लेई, {रोकथाम}।',
    'cropRecommendation.title': 'फसल सलाहकार',
    'cropRecommendation.description': 'अपनी मिट्टी ते मौसम दे अधार पर एआई दियां सफारशां हासल करो',
    'cropRecommendation.loamy': 'दोमट',
    'cropRecommendation.clay': 'मिट्टी',
    'cropRecommendation.sandy': 'सैंडी',
    'cropRecommendation.silt': 'गाद',
    'cropRecommendation.redSoil': 'लाल मिट्टी',
    'cropRecommendation.blackSoil': 'काली मिट्टी',
    'cropRecommendation.alluvial': 'जलोढ़',
    'cropRecommendation.location': 'थाह् र',
    'cropRecommendation.locationPlaceholder': 'शैह् र जां खेतर दर्ज करो',
    'cropRecommendation.season': 'मौसम',
    'cropRecommendation.kharif': 'खरीफ',
    'cropRecommendation.rabi': 'रबी',
    'cropRecommendation.zaid': 'जैद',
    'cropRecommendation.waterAvailability': 'पानी दी उपलब्धता',
    'cropRecommendation.abundant': 'भरपूर मात्रा च',
    'cropRecommendation.moderate': 'दरम्याना',
    'cropRecommendation.limited': 'सीमत',
    'cropRecommendation.rainDependent': 'बरखा पर निर्भर',
    'cropRecommendation.fillRequiredFields': 'कृपा करियै सारे लोड़चदे खेत्तरें गी भरो।',
    'cropRecommendation.generateRecommendations': 'सफारशां त्यार करो',
    'cropRecommendation.analyzing': 'विश्लेशण करदे न...',
    'cropRecommendation.gettingRecommendations': 'अपने खेतर आस्तै सभनें शा अच्छी फसलें दा पता लाना...',
    'cropRecommendation.recommendationsReady': 'सफारशां त्यार !',
    'cropRecommendation.yieldLabel': 'अपेक्षित पैदावार :',
    'cropRecommendation.waterLabel': 'पानी दी जरूरत:',
    'cropRecommendation.marketLabel': 'बजार मुल्ल :',
    'cropRecommendation.durationLabel': 'अवधि :',
    'cropRecommendation.conditionsLabel': 'शर्तें:',
    'cropRecommendation.investmentLabel': 'नवेश :',
    'cropRecommendation.newSearch': 'नमीं खोज',
    'cropRecommendation.shareTitle': 'फसल दियां सफारशां',
    'cropRecommendation.share': 'सांझा करो',
    'cropRecommendation.errorMessage': 'सफारश पैदा करने च त्रुटि',
    'cropRecommendation.soilType': 'मिट्टी दी किस्म',
  },
  brx: {
    'crops.marketPrices': 'लाइभ मन्डिनि बेसेनफोर',
    'crops.searchCrops': 'मैगं-थाइगंफोरखौ नागिरो...',
    'market.highpriceincrease': 'गोबां बेसेन बांनायनि थाखाय',
    'market.pricesdecline': 'बेसेनफोरा खमायलांगासिनो दं।',
    'market.stableprices': 'हाथाया दिदोम',
    'crops.shopDetails': 'बायनायनि फोरमायथि',
    'crops.getDirections': 'दिगफोरखौ ला।',
    'crops.callNow': 'दा कल खालाम',
    'crops.availableItems': 'मोननो हानाय बेसादफोर',
    'crops.distance': 'जानथाय',
    'inputFinder.title': 'इनपुटनि नागिरग्रा',
    'inputFinder.description': 'साखाथिनि गलाफोर नागिर।',
    'inputFinder.searchPlaceholder': 'इनपुटफोरखौ नागिरो...',
    'inputFinder.allShops': 'गासैबो गलाफोर',
    'inputFinder.pmkskCenters': 'पि. एम. के. एस. के. नि मिरुफोर',
    'inputFinder.privateShops': 'गावारि गलाफोर',
    'inputFinder.kmAway': 'कि.मि.',
    'inputFinder.currentPrices': 'सोलिफुनाय बेसेनफोर।',
    'inputFinder.callNow': 'दा कल खालाम',
    'inputFinder.call': 'कल खालाम',
    'inputFinder.getDirections': 'दिगफोर',
    'dashboard.cropDiagnosis.title': 'आबाद बेराम नायनाय (AI)',
    'dashboard.cropDiagnosis.description': 'नोंथांनि बेराम जानाय फसलनि सावगारि ला...',
    'dashboard.cropDiagnosis.imageTooLarge': 'सावगारिया जोबोर गिदिर। अन्नानै 5MB निख्रुइ फिसा सावगारि बाहाय।',
    'dashboard.cropDiagnosis.invalidFileType': 'अन्नानै मोनसे मोजां सावगारि फाइल आपलद खालाम।',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'सावगारिखौ बिजिरनायाव फेलें जादों। अननानै सावगारिया रोखा होन्ना थि खालाम।',
    'dashboard.cropDiagnosis.note': 'AI बिजिरनाया 100% गेबें जाया जानो हागौ',
    'diagnosis.takePhoto': 'सावगारि ला।',
    'diagnosis.uploadFromGallery': 'गेलारिनिफ्राय सायख\'',
    'diagnosis.tipsTitle': 'मोजां सावगारिफोरनि थाखाय टिप्स',
    'diagnosis.tip1': 'मोजां सोरांखौ थि खालाम',
    'diagnosis.tip2': 'सन्देरजानाय जायगायाव नोजोर हो',
    'diagnosis.tip3': 'बिलाइखौ दिदोम लाखि',
    'diagnosis.tip4': 'सायख्लुमनिफ्राय गोजानाव था।',
    'diagnosis.cropImageAlt': 'सावगारिखौ क्रॉप खालाम',
    'diagnosis.remove': 'बोखार।',
    'diagnosis.analyzeWithAI': 'AI जों बिजिरना नाय।',
    'diagnosis.retrying': 'फिन नाजानाय',
    'diagnosis.analyzing': 'फसलनि सावगारिखौ बिजिरनाय...',
    'diagnosis.analyzingSubtext': 'बेले-बेजेखौ सिनायनो थाखाय Advanced Vision AI बाहायनाय।',
    'diagnosis.analysisComplete': 'बिजिरनाया आबुं',
    'diagnosis.laymanHealthy': 'मोजां खौरां! नोंथांनि {crop_name} आबादखौ सावस्रिनां नुदों। बेखौ बेबादिनो लाखिनो थाखाय, नांगौ रोखोम दै होनो थि खालाम आरो इयुननि जायखिजाया जेंनाफोरनि थाखाय नोजोर हो।',
    'diagnosis.laymanDiseased': 'नोंनि {crop_name} आ {disease_name} जों भुगिनांनाय बादि नुदों। माखासे सरासनस्रा लैखोनफोर जायखौ नोंथाङा नुनो मोनबाय जानो हागौ, बेफोर जाबाय {लैखोन}। बेखौ फाहामनो थाखाय नोंथाङा {treatment_organic} बायदि organic solution एबा {treatment_chemical} बायदि रासायनारि राहाफोर बाहायनो हायो। इयुनाव होबथानायनि थाखाय, {होबथानाय}।',
    'cropRecommendation.title': 'आबाद बोसोनगिरि',
    'cropRecommendation.description': 'नोंथांनि हा आरो बोथोरनि सायाव बिथा खालामनानै AI नि सुबुरुनफोरखौ ला',
    'cropRecommendation.loamy': 'हाब्रु',
    'cropRecommendation.clay': 'हाब्रु',
    'cropRecommendation.sandy': 'सेन्डि',
    'cropRecommendation.silt': 'गाद',
    'cropRecommendation.redSoil': 'गोजा हा',
    'cropRecommendation.blackSoil': 'गोसोम हा',
    'cropRecommendation.alluvial': 'फुलुं',
    'cropRecommendation.location': 'थावनि',
    'cropRecommendation.locationPlaceholder': 'नोगोर आरो ओनसोलखौ सो',
    'cropRecommendation.season': 'बोथोर',
    'cropRecommendation.kharif': 'खरीफ',
    'cropRecommendation.rabi': 'रबि',
    'cropRecommendation.zaid': 'जैद',
    'cropRecommendation.waterAvailability': 'दैनि उपलब्धता',
    'cropRecommendation.abundant': 'गोबां',
    'cropRecommendation.moderate': 'गेजेर',
    'cropRecommendation.limited': 'सिमा गोनां',
    'cropRecommendation.rainDependent': 'अखानि सायाव सोनारनाय',
    'cropRecommendation.fillRequiredFields': 'अननानै गासैबो गोनां आयदाफोरखौ आबुं खालाम।',
    'cropRecommendation.generateRecommendations': 'सुबुरुनफोर सोरजि',
    'cropRecommendation.analyzing': 'बिजिरनाय...',
    'cropRecommendation.gettingRecommendations': 'नोंथांनि ओनसोलनि थाखाय साबसिन फसलफोर नागिरनाय...',
    'cropRecommendation.recommendationsReady': 'सुबुरुनफोरा थियारि जाबाय!',
    'cropRecommendation.yieldLabel': 'आसा खालामनाय दिहुनथाय:',
    'cropRecommendation.waterLabel': 'दैनि फिनजाथाइ:',
    'cropRecommendation.marketLabel': 'हाथायनि बेसेन:',
    'cropRecommendation.durationLabel': 'सम खोन्दो :',
    'cropRecommendation.conditionsLabel': 'शर्तफोर:',
    'cropRecommendation.investmentLabel': 'रां खाथायनाय:',
    'cropRecommendation.newSearch': 'गोदान नागिरो',
    'cropRecommendation.shareTitle': 'फसलनि सुबुरुनफोर',
    'cropRecommendation.share': 'शेयार खालाम',
    'cropRecommendation.errorMessage': 'सुबुरुन सोरजिनायाव गोरोन्थि',
    'cropRecommendation.soilType': 'हानि रोखोम',
  },
  ks: {
    'crops.marketPrices': 'زندٕ منڈی قۭمت',
    'crops.searchCrops': 'تلاشی فصلہٕ...',
    'market.highpriceincrease': 'قۭمتَس منٛز زیادٕ ہُریر',
    'market.pricesdecline': 'قٕمتھ چھِ کم گَژھان۔',
    'market.stableprices': 'بازار چھُ مستحکم',
    'crops.shopDetails': 'دُکانٕچ تفصیٖل',
    'crops.getDirections': 'ہدایتَن حٲصِل کٔرِو',
    'crops.callNow': 'وۄنۍ کال کٔرِو',
    'crops.availableItems': 'دٔستِیاب چیٖز',
    'crops.distance': 'فاصلہٕ',
    'inputFinder.title': 'اِنپُٹ فاینڈر',
    'inputFinder.description': 'نزدیٖکی دُکان ژھٲنٛڑِو',
    'inputFinder.searchPlaceholder': 'تٔرِو اِنپُٹ تلاش کَرنہٕ',
    'inputFinder.allShops': 'تمام دُکان',
    'inputFinder.pmkskCenters': 'پی ایم کے ایس کے سینٹر',
    'inputFinder.privateShops': 'پرائیویٹ دُکان',
    'inputFinder.kmAway': 'کلومیٹر دور',
    'inputFinder.currentPrices': 'موجودٕ قیمتہٕ',
    'inputFinder.callNow': 'وۄنۍ کال کٔرِو',
    'inputFinder.call': 'کال کٔرِو',
    'inputFinder.getDirections': 'ہدایتیں',
    'dashboard.cropDiagnosis.title': 'فصلن ہٕنٛز تشخیص (AI)',
    'dashboard.cropDiagnosis.description': 'پننہِ بیمار فصلُک فوٹو تُلِو...',
    'dashboard.cropDiagnosis.imageTooLarge': 'تصویر واریاہ بٔڑ۔ مہربٲنی کٔرِتھ کٔرِو 5MB کھۄتہٕ لۄکٕٹ تصویر استعمال۔',
    'dashboard.cropDiagnosis.invalidFileType': 'مہربٲنی کٔرِتھ کٔرِو اَکھ جٲیز تصویٖر فایلہٕ اپلوڈ کٔر',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'تصویرُک تجزیہٕ کرنس منٛز ناکام۔ مہربٲنی کٔرِتھ کٔرِتھ کٔرِو فوٹو صاف ۔',
    'dashboard.cropDiagnosis.note': 'اے آۓ تجزیہٕ ہیکہٕ نہٕ 100٪ درست آستھ',
    'diagnosis.takePhoto': 'فوٹو تُلِو',
    'diagnosis.uploadFromGallery': 'گیلری منز ژٲر',
    'diagnosis.tipsTitle': 'اصل فوٹوَن ہٕنٛز ترکیبہٕ',
    'diagnosis.tip1': 'اصل گاش کٔرِو یقینی',
    'diagnosis.tip2': 'متاثرہ علاقن پیٹھ توجہ دِیِو',
    'diagnosis.tip3': 'پنہٕ ؤتھر تھٲیِو مستحکم',
    'diagnosis.tip4': 'ژھایہِ نِش بچِو',
    'diagnosis.cropImageAlt': 'کرٛاپ امیج',
    'diagnosis.remove': 'ہٹٲوِو',
    'diagnosis.analyzeWithAI': 'اے آۓ سۭتۍ تجزیہٕ کٔرِو',
    'diagnosis.retrying': 'دُبارٕ کوٗشِش',
    'diagnosis.analyzing': 'کرٛاپ امیجُک تجزیہٕ کَرُن...',
    'diagnosis.analyzingSubtext': 'بے ضابطگی ہُنٛد پتہ لگاونہٕ خٲطرٕ جدید وژن اے آۓ ہُنٛد استعمال کَرُن۔',
    'diagnosis.analysisComplete': 'تجزیہٕ مُکمل',
    'diagnosis.laymanHealthy': 'زبردست خبر! تُہُنٛد {crop_name} فصٕل چھُ صحت مند باسان۔ یہِ یِتھ پٲٹھۍ تھاونہٕ خٲطرٕ کٔرِو مُنٲسِب آب دِنہٕ یٔقیٖنی تہٕ یِنہٕ والہِ کُنہِ تہِ مسلَن ہٕنٛز نگرٲنی ک',
    'diagnosis.laymanDiseased': 'یہِ چھُ باسان تُہُنٛد {crop_name} چھُ {disease_name}۔ کیٚنٛہہ عام علامات یِم تۄہہِ وُچھمٕتۍ چھِو {علامات}۔ امیُک علاج کرنہٕ خٲطرٕ، ہیکِو تُہۍ نامیٲتی حل یتھ کٔنۍ {treatment_organic} یا کیمیٲیی آپشن یتھ کٔنۍ {treatment_chemical} استعمال کٔرِتھ۔ مستقبلس منز روک تھام خٲطرٕ، {روک تھام}۔',
    'cropRecommendation.title': 'فصلُک مشیر',
    'cropRecommendation.description': 'پنٛنہِ میٚژ تہٕ موسمٕچ بُنیادس پیٚٹھ حٲصِل کٔرِو اے آۓ تجویٖزٕ',
    'cropRecommendation.loamy': 'لومی',
    'cropRecommendation.clay': 'کلے',
    'cropRecommendation.sandy': 'سینڈی',
    'cropRecommendation.silt': 'سیٚمب',
    'cropRecommendation.redSoil': 'وۄزٕل میٚژ',
    'cropRecommendation.blackSoil': 'کرٛیٚہنہِ میٚژ',
    'cropRecommendation.alluvial': 'ایلوویئل',
    'cropRecommendation.location': 'مقام',
    'cropRecommendation.locationPlaceholder': 'شہر یا علاقس منٛز دٲخل گژھُن',
    'cropRecommendation.season': 'سیزن',
    'cropRecommendation.kharif': 'خریف',
    'cropRecommendation.rabi': 'ربیع',
    'cropRecommendation.zaid': 'زید',
    'cropRecommendation.waterAvailability': 'آبٕچ دستیابی',
    'cropRecommendation.abundant': 'وافر مقدار',
    'cropRecommendation.moderate': 'اعتدال پسند',
    'cropRecommendation.limited': 'محدود',
    'cropRecommendation.rainDependent': 'روٗد پیٹھ منحصر',
    'cropRecommendation.fillRequiredFields': 'مہربٲنی کٔرِتھ بٔرِو سٲری ضروُری فیلڈ۔',
    'cropRecommendation.generateRecommendations': 'تجویٖزٕ کٔرِو پٲدٕ',
    'cropRecommendation.analyzing': 'تجزیہٕ کَرُن...',
    'cropRecommendation.gettingRecommendations': 'پنٛنہِ علاقہٕ خٲطرٕ بہترین فصلہٕ ژھانڈُن...',
    'cropRecommendation.recommendationsReady': 'سفارشیں چھِ تیار!',
    'cropRecommendation.yieldLabel': 'متوقع پٲداوار:',
    'cropRecommendation.waterLabel': 'آبٕچ ضرورت:',
    'cropRecommendation.marketLabel': 'مارکیٹُک قۭمت:',
    'cropRecommendation.durationLabel': 'مدت:',
    'cropRecommendation.conditionsLabel': 'حالات:',
    'cropRecommendation.investmentLabel': 'سرمایہِ کٲری:',
    'cropRecommendation.newSearch': 'نٔو تلاش',
    'cropRecommendation.shareTitle': 'فصلن ہٕنٛز سفارشہٕ',
    'cropRecommendation.share': 'شییر کٔرِو',
    'cropRecommendation.errorMessage': 'غلطی پٲدٕ کرنٕچ سفارش۔',
    'cropRecommendation.soilType': 'میژِ ہُنٛد قٕسم',
  },
  sd: {
    'crops.marketPrices': 'لائيو منڊي قيمتون',
    'crops.searchCrops': 'فصلن جي ڳولا ڪريو...',
    'market.highpriceincrease': 'لاءِ وڏي قيمت ۾ اضافو',
    'market.pricesdecline': 'قيمتون گهٽجي رهيون آهن',
    'market.stableprices': 'مارڪيٽ لاءِ مستحڪم آهي',
    'crops.shopDetails': 'دڪان جا تفصيل',
    'crops.getDirections': 'هدايتون حاصل ڪريو',
    'crops.callNow': 'هاڻي ڪال ڪريو',
    'crops.availableItems': 'دستياب شيون',
    'crops.distance': 'فاصلو',
    'inputFinder.title': 'ان پٽ ڳوليندڙ',
    'inputFinder.description': 'ويجهي دڪان ڳوليو',
    'inputFinder.searchPlaceholder': 'ڳولا جا انپٽ...',
    'inputFinder.allShops': 'سڀ دڪان',
    'inputFinder.pmkskCenters': 'پي ايم ڪي ايس ڪي سينٽر',
    'inputFinder.privateShops': 'نجي دڪان',
    'inputFinder.kmAway': 'ڪلوميٽر پري',
    'inputFinder.currentPrices': 'موجوده قيمتون',
    'inputFinder.callNow': 'هاڻي ڪال ڪريو',
    'inputFinder.call': 'ڪال ڪريو',
    'inputFinder.getDirections': 'هدايتون',
    'dashboard.cropDiagnosis.title': 'فصلن جي تشخيص (AI)',
    'dashboard.cropDiagnosis.description': 'پنهنجي بيمار فصل جو فوٽو ڪ takeو ...',
    'dashboard.cropDiagnosis.imageTooLarge': 'تصوير تمام وڏي. مهرباني ڪري 5MB کان ننڍي تصوير استعمال ڪريو.',
    'dashboard.cropDiagnosis.invalidFileType': 'مهرباني ڪري هڪ صحيح تصويري فائل اپلوڊ ڪريو.',
    'dashboard.cropDiagnosis.analysisFailedRetry': 'تصوير جو تجزيو ڪرڻ ۾ ناڪامي. مهرباني ڪري پڪ ڪريو ته فوٽو صاف آهي.',
    'dashboard.cropDiagnosis.note': 'AI تجزيو شايد 100٪ صحيح نه هجي',
    'diagnosis.takePhoto': 'فوٽو ڪڍو',
    'diagnosis.uploadFromGallery': 'گيلري مان چونڊيو',
    'diagnosis.tipsTitle': 'سٺن تصويرن لاءِ صلاحون',
    'diagnosis.tip1': 'سٺي روشني کي يقيني بڻايو',
    'diagnosis.tip2': 'متاثر ٿيل علائقي تي ڌيان ڏيو',
    'diagnosis.tip3': 'پتي کي مستحڪم رکو',
    'diagnosis.tip4': 'پاڇن کان پاسو ڪريو',
    'diagnosis.cropImageAlt': 'تصوير ڪٽيو',
    'diagnosis.remove': 'هٽايو',
    'diagnosis.analyzeWithAI': 'AI سان تجزيو ڪريو',
    'diagnosis.retrying': 'ٻيهر ڪوشش ڪريو',
    'diagnosis.analyzing': 'فصل جي تصوير جو تجزيو ڪندي...',
    'diagnosis.analyzingSubtext': 'بي ضابطگين کي ڳولڻ لاءِ ترقي يافته ويزن اي آءِ استعمال ڪندي.',
    'diagnosis.analysisComplete': 'تجزيو مڪمل ٿيو',
    'diagnosis.laymanHealthy': 'وڏي خبر! توهان جو {crop_name} فصل صحتمند نظر اچي رهيو آهي. انهي طريقي سان رکڻ لاءِ ، مناسب پاڻي ڏيڻ کي يقيني بڻايو وڃي ۽ مستقبل جي ڪنهن به مسئلي جي نگراني ڪريو.',
    'diagnosis.laymanDiseased': 'لڳي ٿو ته توهان جو {crop_name} {disease_name} جو شڪار آهي. ڪجهه عام علامتون جيڪي توهان محسوس ڪيون آهن اهي آهن {علامات}. انهي جو علاج ڪرڻ لاءِ ، توهان نامياتي حل استعمال ڪري سگهو ٿا جهڙوڪ {treatment_organic} يا ڪيميائي آپشن جهڙوڪ {treatment_chemical}. مستقبل ۾ روڪٿام لاءِ {روڪٿام}.',
    'cropRecommendation.title': 'فصل جو صلاحڪار',
    'cropRecommendation.description': 'توهان جي مٽي ۽ موسم جي بنياد تي AI سفارشون حاصل ڪريو',
    'cropRecommendation.loamy': 'لومي',
    'cropRecommendation.clay': 'مٽي',
    'cropRecommendation.sandy': 'سينڊي',
    'cropRecommendation.silt': 'سلٽ',
    'cropRecommendation.redSoil': 'ڳاڙهي مٽي',
    'cropRecommendation.blackSoil': 'ڪاري مٽي',
    'cropRecommendation.alluvial': 'ڪلري',
    'cropRecommendation.location': 'مقام',
    'cropRecommendation.locationPlaceholder': 'شهر يا علائقو داخل ڪريو',
    'cropRecommendation.season': 'موسم',
    'cropRecommendation.kharif': 'خريف',
    'cropRecommendation.rabi': 'ربيع',
    'cropRecommendation.zaid': 'زيد',
    'cropRecommendation.waterAvailability': 'پاڻي جي دستيابي',
    'cropRecommendation.abundant': 'ڪثرت سان',
    'cropRecommendation.moderate': 'اعتدال پسند',
    'cropRecommendation.limited': 'محدود',
    'cropRecommendation.rainDependent': 'مينهن تي ڀاڙيندڙ',
    'cropRecommendation.fillRequiredFields': 'مهرباني ڪري سڀني گهربل شعبن کي ڀريو.',
    'cropRecommendation.generateRecommendations': 'سفارشون ٺاهيو',
    'cropRecommendation.analyzing': 'تجزيو ڪندي...',
    'cropRecommendation.gettingRecommendations': 'توهان جي علائقي لاءِ بهترين فصلون ڳولهڻ ...',
    'cropRecommendation.recommendationsReady': 'سفارشون تيار!',
    'cropRecommendation.yieldLabel': 'متوقع پيداوار:',
    'cropRecommendation.waterLabel': 'پاڻي جي ريڪ:',
    'cropRecommendation.marketLabel': 'مارڪيٽ جي قيمت:',
    'cropRecommendation.durationLabel': 'مدت:',
    'cropRecommendation.conditionsLabel': 'حالتون:',
    'cropRecommendation.investmentLabel': 'سيڙپڪاري:',
    'cropRecommendation.newSearch': 'نئين ڳولا',
    'cropRecommendation.shareTitle': 'فصلن جون سفارشون',
    'cropRecommendation.share': 'شيئر ڪريو',
    'cropRecommendation.errorMessage': 'سفارش پيدا ڪرڻ ۾ خرابي',
    'cropRecommendation.soilType': 'مٽي جو قسم',
  }
};

export function getTranslation(keyString: string, lang: Language): string {
  const code = lang.substring(0, 2);
  const dict = KISAN_TRANSLATIONS[code] || KISAN_TRANSLATIONS['en'];
  return dict[keyString] || KISAN_TRANSLATIONS['en'][keyString] || keyString;
}

export class GroqService {
  async analyzeCropImage(base64Data: string, prompt: string, lang: string, location?: string): Promise<string> {
    const res = await fetch('/api/kisan/diagnosis', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ imageBase64: base64Data, prompt, lang, location })
    });
    const data = await res.json();
    return data.result; 
  }

  async getCropRecommendation(soil: string, loc: string, season: string, lang: string): Promise<string> {
    const res = await fetch('/api/kisan/recommend', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ soil, location: loc, season, lang })
    });
    const data = await res.json();
    return data.result;
  }
}

export { MarketService, type MarketPrice, getUserLocationData };
