import { NextResponse } from 'next/server';
import { translateText } from '@/app/actions/gemini-ai';

type NewsItem = { title?: string; description?: string };

function buildFallbackSummary(newsArray: NewsItem[]) {
  const safeNews = Array.isArray(newsArray) ? newsArray : [];
  const headline = safeNews[0]?.title?.trim() || 'Today\'s Civic Bulletin';
  const intro =
    safeNews.length > 0
      ? `Here is your local update: ${safeNews.slice(0, 2).map((item) => item.title || 'Community update').join(' and ')}.`
      : 'No major local updates were found right now. Please check again shortly for the latest civic bulletins.';

  const bullets =
    safeNews.length > 0
      ? safeNews.slice(0, 3).map((item) => {
          const title = item.title?.trim() || 'Community update';
          const description = item.description?.trim() || '';
          return `${title}${description ? ` — ${description.slice(0, 120)}` : ''}`;
        })
      : ['Stay alert for local advisories.', 'Use Bharat Setu for service updates.', 'Follow official district notifications.'];

  return { headline, intro, bullets };
}

export async function POST(req: Request) {
  try {
    const { newsArray, targetLang = 'en-IN' } = await req.json();

    const systemPrompt = `You are an award-winning senior editor for "The Bharat Setu Daily," an esteemed local newspaper.
Your job is to read today's local community updates and write a sophisticated, highly engaging front-page news report rounding up the day's events. The tone should be authoritative yet accessible, using premium journalistic language and vivid prose.
Output strictly in this JSON format:
{
  "headline": "A powerful, commanding main headline worthy of a front-page broadsheet",
  "intro": "One beautifully crafted, engaging paragraph (3-4 sentences max) that hooks the reader and comprehensively summarizes the day's civic progress.",
  "bullets": ["Actionable, concise highlight 1", "Actionable, concise highlight 2", "Actionable, concise highlight 3"]
}
DO NOT use markdown. Output ONLY raw JSON in English.`;

    const userPrompt = `Today's News Items:\n${newsArray.map((n: { title: string; description: string }) => `- ${n.title}: ${n.description}`).join('\n')}`;

    let parsedContent: { headline: string; intro: string; bullets: string[]; labels?: Record<string, string> } = buildFallbackSummary(newsArray as NewsItem[]);

    const githubToken = process.env.GITHUB_TOKEN?.trim();
    if (githubToken) {
      try {
        const res = await fetch('https://models.inference.ai.azure.com/chat/completions', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${githubToken}`,
          },
          body: JSON.stringify({
            model: 'gpt-4o-mini',
            messages: [
              { role: 'system', content: systemPrompt },
              { role: 'user', content: userPrompt },
            ],
            temperature: 0.4,
            max_tokens: 600,
            response_format: { type: 'json_object' },
          }),
        });

        if (res.ok) {
          const data = await res.json();
          const rawJson = data?.choices?.[0]?.message?.content?.trim();
          if (rawJson) {
            const fromModel = JSON.parse(rawJson) as { headline?: string; intro?: string; bullets?: string[] };
            if (fromModel.headline && fromModel.intro && Array.isArray(fromModel.bullets)) {
              parsedContent = {
                headline: fromModel.headline,
                intro: fromModel.intro,
                bullets: fromModel.bullets,
              };
            }
          }
        }
      } catch (llmError) {
        console.warn('Summarize News LLM fallback used:', llmError);
      }
    }

    const labelsConfig = [
      { key: 'theBharatSetuDaily', english: 'The Bharat Setu Daily' },
      { key: 'volAndNo', english: 'Volume 1, Issue' },
      { key: 'localEdition', english: 'Local Edition' },
      { key: 'todaysKeyHighlights', english: 'Today\'s Key Highlights:' },
      { key: 'newsBriefs', english: 'News Briefs' },
      { key: 'officialAITranslationProtocol', english: 'Official AI Translation Protocol' },
      { key: 'generatedByBharatSetuIntelligence', english: 'Generated by Bharat Setu Intelligence' },
    ];

    parsedContent.labels = {};

    const shortLang = targetLang.split('-')[0];
    if (shortLang && shortLang !== 'en') {
      try {
        // Run all translations in parallel for maximum speed
        const [transHeadline, transIntro, transBullets, ...transLabels] = await Promise.all([
          translateText(parsedContent.headline, shortLang),
          translateText(parsedContent.intro, shortLang),
          Promise.all(parsedContent.bullets.map((b: string) => translateText(b, shortLang))),
          ...labelsConfig.map(l => translateText(l.english, shortLang))
        ]);

        parsedContent.headline = transHeadline;
        parsedContent.intro = transIntro;
        parsedContent.bullets = transBullets;
        
        labelsConfig.forEach((l, idx) => {
          if (parsedContent.labels) {
            parsedContent.labels[l.key] = transLabels[idx];
          }
        });
      } catch (transErr) {
        console.error('Translation failed:', transErr);
      }
    } else {
      // If English, just use the fallback values
      labelsConfig.forEach((l) => {
        if (parsedContent.labels) {
          parsedContent.labels[l.key] = l.english;
        }
      });
    }

    return NextResponse.json({ summary: parsedContent, fallbackUsed: !process.env.GITHUB_TOKEN?.trim() });
  } catch (error: unknown) {
    console.error('Summarize News error:', error);
    return NextResponse.json({ error: error instanceof Error ? error.message : 'Unknown error' }, { status: 500 });
  }
}
