"""
Massively expand training data: generates ~1500 additional examples
across all 5 agent classes with high linguistic diversity.
Writes a NEW train_expanded.py that imports and extends the original DATA.
"""
import os, re
from collections import Counter

# ─────────────────────────────────────────────────────────────────────────────
# 1500+ NEW EXAMPLES  (300 per class)
# ─────────────────────────────────────────────────────────────────────────────
NEW_DATA = [

# ═══════════════════════════ NAGARIK_MITRA — 300 ════════════════════════════
# Water supply
("nagarik_mitra","paani supply teen din se band hai koi sunne wala nahi"),
("nagarik_mitra","boring ka paani peela aa raha hai"),
("nagarik_mitra","water tank mein kaali gandagi hai saaf nahi"),
("nagarik_mitra","paani ki pipe mein keeche aa rahe hain"),
("nagarik_mitra","colony mein paani pressure zero hai"),
("nagarik_mitra","subah sirf 15 min paani aata hai kaafi nahi"),
("nagarik_mitra","sarkari naala paani ke connection mein ghus gaya"),
("nagarik_mitra","overhead tank se leakage ho rahi hai sadak bhar gaya"),
("nagarik_mitra","hamare ward mein water tanker nahi aaya 4 din se"),
("nagarik_mitra","jal board ka phone nahi lag raha complaint karna hai"),
("nagarik_mitra","paani ke liye baar baar queue lagana padta hai boring pe"),
("nagarik_mitra","pipe phoot gayi road ke neeche paani bah raha hai"),
("nagarik_mitra","nala overflowing road blocked due to blocked drain"),
("nagarik_mitra","water connection new lena hai form kahan se milega"),
("nagarik_mitra","paani ka bill galat aaya meter reading check karni hai"),
# Electricity
("nagarik_mitra","bijli nahi aai 12 ghante se mohalle mein"),
("nagarik_mitra","transformer phook gaya hai area blackout"),
("nagarik_mitra","electric wire sadak pe gir gayi dangrous hai"),
("nagarik_mitra","meter lagane ke liye application deni hai"),
("nagarik_mitra","bijli ka bill 3x zyada aaya gaya meter faulty"),
("nagarik_mitra","load shedding schedule kya hai hamare area mein"),
("nagarik_mitra","bijli pole neecha ho gaya hai gaadion se takra raha"),
("nagarik_mitra","bijli ka new connection chahiye kaise milega"),
("nagarik_mitra","smart meter mein recharge nahi ho raha"),
("nagarik_mitra","pre-paid electricity meter balance zero ho gaya"),
("nagarik_mitra","transformer oil leak ho raha hai fire ka darr hai"),
("nagarik_mitra","electricity department ne connection kata diya galti se"),
("nagarik_mitra","bijli subsidy nahi mil rahi SC/ST card pe"),
("nagarik_mitra","power cut har roz subah ki times pe hoti hai"),
("nagarik_mitra","low voltage se ghar ke appliances kharab ho rahe hain"),
# Roads / drains
("nagarik_mitra","national highway pe ek bada pothole hai gaadi palti"),
("nagarik_mitra","sadak repair ke liye PWD complaint karna hai"),
("nagarik_mitra","rain water road pe jama ho gaya drainage nahi hai"),
("nagarik_mitra","flyover ke neeche kachara bahut zyada hai clearance chahiye"),
("nagarik_mitra","naali ka dhakkan nahi hai baccha gir sakta hai"),
("nagarik_mitra","speed breaker banana chahiye school ke paas"),
("nagarik_mitra","road divider toot gaya accident ho sakta hai"),
("nagarik_mitra","footpath par dukaan walo ne kabza kar liya"),
("nagarik_mitra","gali mein andhere ke kaaran raat ko crime ho rahi"),
("nagarik_mitra","main road pe bade gaddhe hain ambulance nahi aa sakti"),
("nagarik_mitra","kulvert band ho gaya barish mein paani bharta hai"),
("nagarik_mitra","internal colony road kab banegi municipality batao"),
# Garbage / sanitation
("nagarik_mitra","garbage truck hafte mein ek baar bhi nahi aata hai"),
("nagarik_mitra","kachara meri dukaan ke bahar dump kar rahe hain log"),
("nagarik_mitra","dog bite ke darr se safai wale nahi ate karan batao"),
("nagarik_mitra","nagar nigam dustbin full ho gaya utha nahi raha koi"),
("nagarik_mitra","public place pe sheeshe ki bottle todna khatarnak"),
("nagarik_mitra","colony ke bahar khula nala badbu ata hai kya karein"),
("nagarik_mitra","mrityu pashu sadak par pada hua utha nahi koi"),
("nagarik_mitra","plastic jalane se dhuaan aa raha health ke liye bura"),
("nagarik_mitra","biomass waste ka proper disposal kaise karein"),
("nagarik_mitra","ward safai mein bhrashtachar ho raha hai kahan report"),
# Certificates
("nagarik_mitra","birth certificate apply karna hai online ya offline"),
("nagarik_mitra","death certificate 15 din se nahi aaya"),
("nagarik_mitra","domicile certificate ke liye konse documents chahiye"),
("nagarik_mitra","income certificate ka format kya hai"),
("nagarik_mitra","caste certificate validity kab expire hogi"),
("nagarik_mitra","OBC caste certificate ke liye online apply karna hai"),
("nagarik_mitra","jati praman patra ke liye tehsildar se milna hai"),
("nagarik_mitra","married women ka surname certificate kaise banega"),
("nagarik_mitra","character certificate police clearance kahan se milega"),
("nagarik_mitra","bonafide certificate ke liye school se apply karna"),
("nagarik_mitra","PRC permanent resident certificate form bharna hai"),
("nagarik_mitra","age certificate for government job kaise banta hai"),
("nagarik_mitra","solvency certificate bank ke liye kahan se milega"),
("nagarik_mitra","migration certificate nahi aaya college se"),
("nagarik_mitra","medical fitness certificate sarkar ke liye),chahiye"),
# RTI / Grievance
("nagarik_mitra","RTI dakhil karni hai sarkari kaam ke baare mein"),
("nagarik_mitra","public grievance portal pe complaint kaise karein"),
("nagarik_mitra","jansunwai mein jaana hai DM se milna hai"),
("nagarik_mitra","CM helpline pe call karni hai koi sunne wala nahi"),
("nagarik_mitra","loksewa guarantee act ke tahat complaint"),
("nagarik_mitra","online complaint portal mein ID nahi ban rahi"),
("nagarik_mitra","government office mein bribe maanga kahan complaint"),
("nagarik_mitra","collector office mein application kab tak process hogi"),
("nagarik_mitra","lokayukta complaint kaise karein sarkari babu ke khilaf"),
("nagarik_mitra","SDM office mein appointment kaise milegi"),
# Property / Registration
("nagarik_mitra","property ka mutation nahi hua nagarpalika mein"),
("nagarik_mitra","property tax bharna hai online kaise karein"),
("nagarik_mitra","ghar ka naksha pass karana hai building permission"),
("nagarik_mitra","encroachment notice aaya hai kya karein"),
("nagarik_mitra","property card kaise banata hai"),
("nagarik_mitra","house tax bill galat hai rectify karwana hai"),
("nagarik_mitra","building completion certificate kaise milta hai"),
("nagarik_mitra","commercial to residential conversion application"),
("nagarik_mitra","khatauni nakal chahiye revenue record se"),
("nagarik_mitra","water connection for new construction kaise milega"),
# Misc civic
("nagarik_mitra","driving license renew karna hai kaise"),
("nagarik_mitra","voter ID card address change karna hai"),
("nagarik_mitra","aadhaar card mein address update karna hai"),
("nagarik_mitra","ration card correction karna hai naam galat hai"),
("nagarik_mitra","new ration card ke liye apply karna hai"),
("nagarik_mitra","LPG connection transfer karna hai"),
("nagarik_mitra","my street has no name board DIGIPIN needed"),
("nagarik_mitra","municipal corporation election date kab hai"),
("nagarik_mitra","park mein illegal construction ho raha hai"),
("nagarik_mitra","public toilet near our colony please build one"),
("nagarik_mitra","community hall booking kaise hogi nagarpalika se"),
("nagarik_mitra","municipal library card banana hai"),
("nagarik_mitra","pollution complaint factory se kaala dhuaan aa raha"),
("nagarik_mitra","noise pollution shikayat factory raat ko chalti hai"),
("nagarik_mitra","illegal hoarding sadak pe aayi hai khatra hai"),
# Hindi / Devanagari
("nagarik_mitra","पानी नहीं आ रहा है तीन दिन से"),
("nagarik_mitra","बिजली गुल है सुबह से पूरे मोहल्ले में"),
("nagarik_mitra","सड़क में बड़े गड्ढे हैं गाड़ी पलट सकती है"),
("nagarik_mitra","नाली ब्लॉक हो गई है गली में पानी भर गया"),
("nagarik_mitra","निगम में शिकायत दर्ज करनी है पानी के बारे में"),
("nagarik_mitra","जन्म प्रमाण पत्र बनवाना है नगर पालिका से"),
("nagarik_mitra","आरटीआई फाइल करनी है सरकारी काम के बारे में"),
("nagarik_mitra","बिजली का मीटर खराब है रीडिंग गलत आ रही है"),
("nagarik_mitra","कचरा नहीं उठा रहे हैं सफाई वाले"),
("nagarik_mitra","सड़क की मरम्मत के लिए शिकायत करनी है"),
# English queries
("nagarik_mitra","sewage drain overflowing complaint to municipality"),
("nagarik_mitra","no street lights working in my colony dangerous"),
("nagarik_mitra","garbage not collected for 5 days complaint"),
("nagarik_mitra","water supply disrupted for 3 days in sector 7"),
("nagarik_mitra","pothole near school causing accidents please repair"),
("nagarik_mitra","need birth certificate from municipal corporation"),
("nagarik_mitra","electricity meter showing wrong reading complaint"),
("nagarik_mitra","open manhole near market very dangerous"),
("nagarik_mitra","new water connection for house application"),
("nagarik_mitra","property tax online payment not working"),
# Bhojpuri / regional
("nagarik_mitra","paani nai aawe hai hamar ghar ke paas aaj bhi"),
("nagarik_mitra","bijli nahi rahi subah se poora gaon andhero mein"),
("nagarik_mitra","sadak ke gaddha mein gaadi fasi rahli hai"),
("nagarik_mitra","nali bhar gaile hai paani sarak pe aa gaile"),
("nagarik_mitra","sahab log certificate banaye ke baat kahan jayin"),
("nagarik_mitra","kachara uthaawa band ho gaile nagar nigam se"),
("nagarik_mitra","batti nahi aai raat bhar transformer kharab ba"),
("nagarik_mitra","nagarpalika mein shikayat likhawna hai paani ke"),
("nagarik_mitra","dastaawej banwana hai sahab kahan jaayein ham"),
("nagarik_mitra","pani pipwa phoot gaile rasta bhar gail hai"),
# Mixed Hinglish
("nagarik_mitra","paani supply completely off hai 2 din se koi action nahi"),
("nagarik_mitra","gutter overflow ho raha please send municipal team ASAP"),
("nagarik_mitra","street light out hai 1 week se BESCOM complaint karna hai"),
("nagarik_mitra","road completely damaged please koi sun raha hai kya"),
("nagarik_mitra","certificate urgently chahiye apply karna hai online"),
("nagarik_mitra","RTI file karna hai information chahiye government se"),
("nagarik_mitra","property tax online kaise pay karein mobile se"),
("nagarik_mitra","ration card mein family member add karna hai process"),
("nagarik_mitra","water pipeline leakage bohot serious hai fix karwao"),
("nagarik_mitra","encroachment by neighbor on public road complain karna"),

# ═══════════════════════════ SWASTHYA_SAHAYAK — 300 ═════════════════════════
# Fever / cold
("swasthya_sahayak","bukhaar 102 ho gaya hai teen din se dawai nahi kar rahi"),
("swasthya_sahayak","zukam khansi 2 hafte se chal rahi hai chest tightness"),
("swasthya_sahayak","dengue ke lakshan hain mujhe platelet count kam hua"),
("swasthya_sahayak","malaria ke symptoms hain raat ko zyada thandi lagti hai"),
("swasthya_sahayak","typhoid confirm hua hai doctor ka ilaj chal raha"),
("swasthya_sahayak","viral fever nahi uththa medication kya lein"),
("swasthya_sahayak","flu vaccine kab lagwanI chahiye aur kahan"),
("swasthya_sahayak","body mein rash aa gayi hai fever ke saath"),
("swasthya_sahayak","seasonal cough due to pollution kya karein"),
("swasthya_sahayak","bacche ko 3 din se bukhaar uthh nahi raha daat nikalna"),
# Hospital / doctor
("swasthya_sahayak","sarkari hospital mein free OPD kaise milti hai"),
("swasthya_sahayak","government hospital mein specialist doctor kab milega"),
("swasthya_sahayak","AIIMS appointment online kaise book karein"),
("swasthya_sahayak","PHC kab khulti hai timing batao"),
("swasthya_sahayak","nearest government eye hospital kahan hai"),
("swasthya_sahayak","referral letter kaise milega CHC se district hospital"),
("swasthya_sahayak","doctor sahab ne dawai likhi hai generic milegie kya"),
("swasthya_sahayak","hospital mein bed nahi mila private mein jana padega"),
("swasthya_sahayak","24 ghante emergency government hospital near me"),
("swasthya_sahayak","trauma center nearest location urgent"),
# Pregnancy / maternal health
("swasthya_sahayak","pregnant hoon pehla trimester hai kya khaana chahiye"),
("swasthya_sahayak","delivery ka time aa raha hai hospital kab jayein"),
("swasthya_sahayak","prasav ke baad bleeding ho rahi hai kya karein"),
("swasthya_sahayak","antenatal checkup kab karwana chahiye schedule"),
("swasthya_sahayak","iron folic acid tablets kab leni chahiye pregnancy mein"),
("swasthya_sahayak","c-section ya normal delivery hospital se poochhna hai"),
("swasthya_sahayak","JSY yojana mein delivery ke paise kab milenge"),
("swasthya_sahayak","maternity benefit scheme ke liye apply karna hai"),
("swasthya_sahayak","PMMVY ya PM Matru Vandana Yojana ke liye register"),
("swasthya_sahayak","newborn ka cord care kaise karein ghar mein"),
# Child health / vaccination
("swasthya_sahayak","bacche ka polio drop schedule kya hai"),
("swasthya_sahayak","DPT vaccine kab lagwani chahiye 6 mahine ke baad"),
("swasthya_sahayak","immunization card kho gayi nayi kaise milegI"),
("swasthya_sahayak","bacche ka weight nahi badh raha malnutrition hai"),
("swasthya_sahayak","ICDS aanganwadi mein poshan aahaar kab milega"),
("swasthya_sahayak","measles rubella campaign kab aayega hamare gaon mein"),
("swasthya_sahayak","bacche ko diarrhea ho raha ORS kahan se milega"),
("swasthya_sahayak","child development check up schedule government"),
("swasthya_sahayak","school health program mein bacche ki jaanch hogi"),
("swasthya_sahayak","newborn hearing test sarkari hospital mein hoti hai"),
# Chronic / NCD
("swasthya_sahayak","diabetes ka blood sugar control nahi ho raha"),
("swasthya_sahayak","BP high hai 160/100 medication change karna hai"),
("swasthya_sahayak","thyroid test karana hai sarkari lab mein"),
("swasthya_sahayak","asthma ka inhaler band ho gaya alternative kya hai"),
("swasthya_sahayak","heart blockage hai bypass surgery ke baad care"),
("swasthya_sahayak","cancer screening free mein kahan hoti hai"),
("swasthya_sahayak","kidney disease diet mein kya khayein proteins limit"),
("swasthya_sahayak","arthritis joint pain severe hai kya karein"),
("swasthya_sahayak","cholesterol bahut high hai diet kaise control karein"),
("swasthya_sahayak","COPD pulmonary disease lung function test kahan"),
# Mental health
("swasthya_sahayak","depression ke symptoms hain help chahiye kahan milegi"),
("swasthya_sahayak","anxiety bahut zyada ho gaya hai panic attacks aa rahe"),
("swasthya_sahayak","neend nahi aati anxiety ki wajah se doctor chahiye"),
("swasthya_sahayak","NIMHANS ya IHBAS free mental health consultation"),
("swasthya_sahayak","suicide thoughts aa rahe hain help line number chahiye"),
("swasthya_sahayak","alcoholism ke liye help center sarkari kahan hai"),
("swasthya_sahayak","drug addiction treatment free mein kahan milega"),
("swasthya_sahayak","psychiatric medicine ka prescription kaise milega"),
("swasthya_sahayak","counselor se milna hai school mein child problems"),
("swasthya_sahayak","govt mental hospital mein admission kaise hoga"),
# Emergency
("swasthya_sahayak","pet mein bahut dard ho raha 108 bulao"),
("swasthya_sahayak","snake bit ho gaya hai antivenin hospital mein hai"),
("swasthya_sahayak","jal jaana hua hai jalane ki dawa kahan se milegi"),
("swasthya_sahayak","road accident hua hai hospital aur blood donation"),
("swasthya_sahayak","heart attack ke symptoms feel ho rahe hain kya karein"),
("swasthya_sahayak","stroke ke signs dikh rahe hain muh teda ho gaya"),
("swasthya_sahayak","bachcha machhli ki haddi ki wajah se dard mein hai"),
("swasthya_sahayak","allergic reaction bahut buri ho gayi body pe rash"),
("swasthya_sahayak","kisi ne zeher kha liya stomach pump kahan hoga"),
("swasthya_sahayak","electricity ka jhatka laga hai hospital kahan hai"),
# Blood / lab tests
("swasthya_sahayak","blood group test free mein kahan hoga sarkari lab"),
("swasthya_sahayak","CBC blood test report normal hai ya nahi"),
("swasthya_sahayak","HIV test free confidential government centre"),
("swasthya_sahayak","tuberculosis TB test kahan hoga DOTS centre"),
("swasthya_sahayak","Hb hemoglobin 7 hai anemia ka ilaj kya hai"),
("swasthya_sahayak","malaria blood slide test free PHC mein hota hai"),
("swasthya_sahayak","dengue NS1 test kitna hoga free ho sakta hai"),
("swasthya_sahayak","urine test morning sample kab dena hai"),
("swasthya_sahayak","X-ray free mein district hospital mein hoti hai"),
("swasthya_sahayak","ultrasound pregnancy ke liye free mein hoti hai"),
# Govt health schemes
("swasthya_sahayak","ayushman bharat card ke liye eligibility kya hai"),
("swasthya_sahayak","PMJAY mein kitne ka free treatment milta hai"),
("swasthya_sahayak","state health scheme UP mein kya hai"),
("swasthya_sahayak","aam aadmi bima yojana health cover se ilaj kaise"),
("swasthya_sahayak","janani shishu suraksha yojana mein kya milega"),
("swasthya_sahayak","CGHS card ke liye empanelled doctor kaise dhunde"),
("swasthya_sahayak","ESIC dispensary mein OPD kaise milegi"),
("swasthya_sahayak","free dialysis scheme mein register karna hai"),
("swasthya_sahayak","RBSK school health check-up program information"),
("swasthya_sahayak","NHM ki ASHa worker se kaise mile gaon mein"),
# Devanagari
("swasthya_sahayak","तबियत ठीक नहीं है पेट में दर्द हो रहा है"),
("swasthya_sahayak","बुखार आ रहा है तीन दिन से दवाई नहीं कर रही"),
("swasthya_sahayak","बच्चे को पोलियो वैक्सीन लगवानी है कहाँ जाएँ"),
("swasthya_sahayak","प्रेगनेंट हूँ सरकारी अस्पताल में फ्री डिलीवरी"),
("swasthya_sahayak","आयुष्मान कार्ड से इलाज कराना है"),
("swasthya_sahayak","सरकारी अस्पताल में ओपीडी कब होती है"),
("swasthya_sahayak","डेंगू के लक्षण हैं डॉक्टर से मिलना है"),
("swasthya_sahayak","ब्लड प्रेशर बढ़ गया है दवाई चाहिए"),
("swasthya_sahayak","बच्चे का टीकाकरण करवाना है शेड्यूल बताएं"),
("swasthya_sahayak","मलेरिया का इलाज फ्री में कहाँ होता है"),
# English
("swasthya_sahayak","want to know nearest government hospital for fever"),
("swasthya_sahayak","child vaccination schedule polio measles DPT"),
("swasthya_sahayak","free cancer screening government hospital"),
("swasthya_sahayak","ayushman bharat card how to get enrollment"),
("swasthya_sahayak","mental health helpline number india"),
("swasthya_sahayak","pregnancy antenatal care government clinic"),
("swasthya_sahayak","blood test free government laboratory near me"),
("swasthya_sahayak","108 ambulance service phone number"),
("swasthya_sahayak","TB tuberculosis free treatment DOTS center"),
("swasthya_sahayak","diabetes free medicine government hospital"),
# Bhojpuri/dialects
("swasthya_sahayak","hamar tabiyat thik nahi ba doctor ke paas kaise jaayein"),
("swasthya_sahayak","baccha ke bukhar utarela nahi hai koi dawai nahi kar raha"),
("swasthya_sahayak","gaon mein PHC kab khulela baabua ke tika lagwana hai"),
("swasthya_sahayak","prasav ke baad dard ho ra hai hospital kaise jayein"),
("swasthya_sahayak","dant dard bahut ho ra hai dawai nahi kar rahi"),
# Mixed Hinglish
("swasthya_sahayak","fever 3 din se hai tablet de raha hoon but no improvement"),
("swasthya_sahayak","blood pressure check karna hai nearest government PHC"),
("swasthya_sahayak","dengue test karna hai free gov lab near me"),
("swasthya_sahayak","pregnancy checkup free sarkari hospital mein available"),
("swasthya_sahayak","child complete vaccination 0-5 years schedule sarkari"),
("swasthya_sahayak","nearest govt hospital for emergency near my location"),
("swasthya_sahayak","mental health counseling free gov center near me"),
("swasthya_sahayak","PMJAY benefits meri family ke liye kaise check karein"),
("swasthya_sahayak","anemia iron deficiency free treatment government"),
("swasthya_sahayak","sugar test HbA1c free sarkari lab mein hota hai kya"),

# ═══════════════════════════ YOJANA_SAATHI — 300 ════════════════════════════
# PM-KISAN / farmer schemes
("yojana_saathi","PM KISAN beneficiary status check karna hai"),
("yojana_saathi","kisan samman nidhi ka paise account mein nahi aaya"),
("yojana_saathi","PM KISAN mein registration kaise karein naye kisan"),
("yojana_saathi","kisan credit card ke liye documents kya chahiye"),
("yojana_saathi","fasal bima yojana mein claim kaise karein"),
("yojana_saathi","PMFBY crop insurance apply karna hai deadline kab"),
("yojana_saathi","kisan suvidha app mein registration kaise hogi"),
("yojana_saathi","PM KUSUM solar pump yojana ke liye apply karna"),
("yojana_saathi","pradhan mantri kisan maandhan yojana pension kisan"),
("yojana_saathi","eNAM portal par mandi mein apni fasal kaise bechen"),
("yojana_saathi","soil health card kab milega meri jameen ka"),
("yojana_saathi","gramin bhandaran yojana mein warehouse kaise milega"),
("yojana_saathi","kisan rin portal mein loan status kaise check karein"),
# Housing
("yojana_saathi","PM Awas Yojana Gramin ke liye apply karna hai"),
("yojana_saathi","PMAY urban housing subsidy kitni milti hai"),
("yojana_saathi","indira awas yojana list mein naam check karna"),
("yojana_saathi","housing for all scheme city mein kaise apply"),
("yojana_saathi","BLC Beneficiary Led Construction subsidy kaise milegi"),
("yojana_saathi","CLSS credit linked subsidy EWS ka benefit kab milega"),
("yojana_saathi","swaas grih yojana state housing scheme apply"),
("yojana_saathi","gramin housing loan subsidy kahan se milegi"),
("yojana_saathi","slum rehabilitation yojana mein apply karna hai"),
("yojana_saathi","affordable housing lottery online apply haryana"),
# Pension schemes
("yojana_saathi","vidhwa pension mein naam add karna UP mein"),
("yojana_saathi","vridha pension yojana ke paise nahi aaye 2 mahine"),
("yojana_saathi","divyang viklang pension ke liye kaise apply karein"),
("yojana_saathi","NPS national pension scheme mein khatey kholna"),
("yojana_saathi","PM Shram Yogi Maandhan informal worker pension"),
("yojana_saathi","labour pension state scheme mein registration"),
("yojana_saathi","atal pension yojana bank mein enroll karna hai"),
("yojana_saathi","NPS corpus kitna milega retire ke time calculator"),
("yojana_saathi","EPF pension ke saath PM pension kaise milegi"),
("yojana_saathi","social security pension SC category UP mein"),
# Education scholarship
("yojana_saathi","SC student scholarship renewal kaise karein online"),
("yojana_saathi","OBC scholarship form bharna NSP portal se"),
("yojana_saathi","minority scholarship deadline aur documents"),
("yojana_saathi","merit cum means scholarship for higher education"),
("yojana_saathi","PM Yashasvi scholarship ST OBC eligibility"),
("yojana_saathi","post matric scholarship renewal kab hogi 2024-25"),
("yojana_saathi","central sector scholarship DBT mein payment kab"),
("yojana_saathi","beti bachao beti padhao scheme mein register"),
("yojana_saathi","Sukanya Samridhi Yojana kab mature hoga"),
("yojana_saathi","Mukhyamantri Kanya Utthan Yojana Bihar mein"),
# Food / ration
("yojana_saathi","ONORC one nation one ration card portability"),
("yojana_saathi","ration card mein naam add karna hai naye member),"),
("yojana_saathi","antyodaya ration card ke liye eligibility"),
("yojana_saathi","Pradhan Mantri Garib Kalyan Ann Yojana free grain"),
("yojana_saathi","ration card surrender nahi hua death ke baad"),
("yojana_saathi","AAY card priority household PHH mein upgrade"),
("yojana_saathi","fair price shop complaint karna ration nahi diya"),
("yojana_saathi","PDS point of sale machine nahi chal rahi"),
("yojana_saathi","epos machine se fingerprint nahi lag raha ration"),
("yojana_saathi","ration card AAY se PHH downgraded ho gaya"),
# Ujjwala / LPG
("yojana_saathi","PMUY Ujjwala yojana LPG connection kaise milega"),
("yojana_saathi","ujjwala 2.0 ke liye apply karna hai documents"),
("yojana_saathi","LPG cylinder subsidy nahi aa rahi account mein"),
("yojana_saathi","gas agency mein naam add karna hai"),
("yojana_saathi","pahal DBTL subsidy link kaise karein aadhaar se"),
("yojana_saathi","additional cylinder request kaise karein PM Ujjwala"),
# MGNREGA / employment
("yojana_saathi","MGNREGA job card nahi bana abhi tak kab banega"),
("yojana_saathi","100 din kaam ki guarantee mein naam kaise chalwayein"),
("yojana_saathi","narega ka payment nahi aaya bank mein kaafi mahine se"),
("yojana_saathi","MGNREGA muster roll check karna hai mera kaam tha"),
("yojana_saathi","mahila swayam sahayata samuh narega mein kaam"),
("yojana_saathi","PM Employment Generation Programme PMEGP apply"),
# Water / Swachh Bharat
("yojana_saathi","Jal Jeevan Mission ke tahat nal ka connection kab milega"),
("yojana_saathi","har ghar nal se jal tahat registration karna"),
("yojana_saathi","Swachh Bharat Mission toilet banane ki subsidy"),
("yojana_saathi","SBM open defecation free ODF verification kab hogi"),
("yojana_saathi","AMRUT mission mein city water supply project"),
("yojana_saathi","PM SVANidhi street vendor loan kaise milega"),
# Devanagari
("yojana_saathi","पीएम किसान का पैसा दो महीने से अकाउंट में नहीं आया"),
("yojana_saathi","प्रधानमंत्री आवास योजना के लिए आवेदन करना है"),
("yojana_saathi","विधवा पेंशन योजना में नाम कैसे दर्ज करें"),
("yojana_saathi","बेटी की पढ़ाई के लिए छात्रवृत्ति चाहिए"),
("yojana_saathi","उज्ज्वला योजना गैस कनेक्शन कैसे मिलेगा"),
("yojana_saathi","मनरेगा जॉब कार्ड बनाना है कब मिलेगा"),
("yojana_saathi","किसान क्रेडिट कार्ड के लिए आवेदन करना है"),
("yojana_saathi","फसल बीमा योजना में रजिस्ट्रेशन कैसे करें"),
("yojana_saathi","वृद्धा पेंशन योजना के पैसे नहीं आए"),
("yojana_saathi","जल जीवन मिशन में नल की जोड़ाई कब होगी"),
# English
("yojana_saathi","PM KISAN status check PFMS payment pending"),
("yojana_saathi","how to apply PMAY affordable housing subsidy"),
("yojana_saathi","old age pension UP scheme eligibility and documents"),
("yojana_saathi","MGNREGA 100 days employment how to register"),
("yojana_saathi","fasal bima crop insurance claim procedure"),
("yojana_saathi","scholarship NSP portal OBC students how to apply"),
("yojana_saathi","PM Ujjwala scheme LPG free connection eligibility"),
("yojana_saathi","Sukanya Samridhi girl child scheme account open"),
("yojana_saathi","swachh bharat toilet construction subsidy"),
("yojana_saathi","PM SVANidhi 10000 loan for street vendors"),
# Bhojpuri
("yojana_saathi","kisan yojana ka paisa 3 mahine se nahi aail"),
("yojana_saathi","pension ke paise khata mein kab aahi"),
("yojana_saathi","awas yojana mein ghar ke liye kaise apply kari"),
("yojana_saathi","narega ka haazri nahi lagi mahina ho gaile"),
("yojana_saathi","ujjwala yojana gas cylinder nahi mila registration ka"),
# Mixed Hinglish
("yojana_saathi","PM KISAN ka pending installment kab release hoga"),
("yojana_saathi","PMAY housing subsidy kitni milegi EWS category mein"),
("yojana_saathi","scholarship NSP portal online apply deadline kab hai"),
("yojana_saathi","widow pension UP register online kaise karein"),
("yojana_saathi","MGNREGA 100 days work guarantee kaise milega hamare gaon"),
("yojana_saathi","free gas connection ujjwala 2.0 apply kaise kare"),
("yojana_saathi","fasal bima kisan yojana crop loss claim procedure"),
("yojana_saathi","jal jeevan mission nal connection application"),
("yojana_saathi","viklang divyang pension scheme apply karna hai"),
("yojana_saathi","Kisan Credit Card loan kaise milega cooperative bank"),

# ═══════════════════════════ ARTHIK_SALAHKAR — 300 ══════════════════════════
# Fraud / scam
("arthik_salahkar","kisi ne mujhe lottery jeeti phone kiya fraud hai"),
("arthik_salahkar","fake KYC message aaya SBI ka OTP mang raha"),
("arthik_salahkar","WhatsApp par job offer aaya pehle paise lo fraud"),
("arthik_salahkar","investment company ne paise le liye return nahi diya"),
("arthik_salahkar","online shopping mein fake product aaya paise wapas nahi"),
("arthik_salahkar","phishing email se bank login kar liya account saaf"),
("arthik_salahkar","SIM swap fraud hua mera number kisi ne lete liya"),
("arthik_salahkar","ATM duplication card clone hua paise nahi nikle"),
("arthik_salahkar","Cyber crime helpline number kya hai 1930"),
("arthik_salahkar","bank ne bola suspicious transaction hai kya karein"),
("arthik_salahkar","ek unknown number se call aakar EMI katwai"),
("arthik_salahkar","courier company ne fake package deliver kiya paisa liya"),
("arthik_salahkar","romance scam ho gaya shaadi ke liye paise liye"),
("arthik_salahkar","social media pe fake brand se order kiya nahi aaya"),
("arthik_salahkar","google pay pe galti se kisi aur ko paisa gayi"),
# Loans
("arthik_salahkar","home loan EMI bahut high ho gayi bank se request"),
("arthik_salahkar","vehicle loan bajaj finance mein apply karna hai"),
("arthik_salahkar","business loan without collateral kaise milega"),
("arthik_salahkar","mudra loan shishu kishor tarun category difference"),
("arthik_salahkar","PM SVANidhi loan 10000 se 50000 upgrade kaise"),
("arthik_salahkar","gold loan interest rate comparison banks"),
("arthik_salahkar","personal loan eligibility salaried 25k income"),
("arthik_salahkar","MSME credit guarantee scheme apply karna hai"),
("arthik_salahkar","education loan ke liye koi guarantee nahi kya karein"),
("arthik_salahkar","loan foreclosure charges kitne honge bank mein"),
("arthik_salahkar","home loan balance transfer other bank mein"),
("arthik_salahkar","EMI bounce charges waive karna hai bank se"),
("arthik_salahkar","moratorium mil sakta hai loan ke liye COVID basis"),
("arthik_salahkar","SBI home loan 8.5% floats to 9.1% kab hua"),
("arthik_salahkar","PMRY loan self employment ke liye youth apply"),
# Bank account issues
("arthik_salahkar","bank account mein amount freeze ho gaya court ne"),
("arthik_salahkar","NPA non-performing asset loan default kya hoga"),
("arthik_salahkar","bank ne account close kar diya wajah nahi batai"),
("arthik_salahkar","joint account se money withdraw nahi ho raha"),
("arthik_salahkar","minor account to major convert kab hoga documents"),
("arthik_salahkar","dormant account reactivate kaise karein"),
("arthik_salahkar","cheque bounce hua paise kaise wapas milenge"),
("arthik_salahkar","NACH ECS mandate cancel karna hai EMI"),
("arthik_salahkar","SMS alert band ho gayi transaction pe kaise chalao"),
("arthik_salahkar","bank passbook update nahi ho rahi entry nahi lagti"),
# UPI / Digital payments
("arthik_salahkar","UPI pin bhool gaya reset kaise karein"),
("arthik_salahkar","PhonePe se payment pending hai refund nahi aaya"),
("arthik_salahkar","Paytm wallet mein paisa atka hai withdrawal nahi"),
("arthik_salahkar","BHIM UPI transaction failed paise kaate gaye"),
("arthik_salahkar","RuPay card international payment enable karna"),
("arthik_salahkar","QR code scan karne ke baad paise gaye fraud"),
("arthik_salahkar","Google Pay limit exceed ho gayi daily limit"),
("arthik_salahkar","UPI autopay subscription cancel karna hai"),
("arthik_salahkar","UPI number se naam pata nahi chalata contact"),
("arthik_salahkar","payment app mein KYC nahi hua transaction blocked"),
# Tax / income
("arthik_salahkar","ITR file karna hai 2024-25 aaykar return"),
("arthik_salahkar","Form 16 employer ne nahi diya itr ke liye"),
("arthik_salahkar","TDS refund kab aayega bank account mein"),
("arthik_salahkar","GST registration karna hai chhota business ke liye"),
("arthik_salahkar","PAN card apply karna hai minor ke liye"),
("arthik_salahkar","PAN Aadhaar link nahi hua tax notice aaya"),
("arthik_salahkar","income tax notice mein demand aaya kya karein"),
("arthik_salahkar","tax saving FD 80C mein kitna invest karein"),
("arthik_salahkar","80D mein health insurance premium kitna deduct"),
("arthik_salahkar","HUF account tax benefit kaise milega"),
# Insurance
("arthik_salahkar","term insurance claim nahi aayi nominee submit kar diya"),
("arthik_salahkar","PM Jeevan Jyoti Bima Yojana PMJJBY kaise milega"),
("arthik_salahkar","PMSBY accident insurance 2 lakh ke liye apply"),
("arthik_salahkar","fasal beema claim reject ho gaya kya karein"),
("arthik_salahkar","LIC policy surrender value kitni hogi"),
("arthik_salahkar","health insurance cashless denied hospital ne"),
("arthik_salahkar","vehicle insurance expired challan bhara kya karein"),
("arthik_salahkar","motor accident compensation third party claim"),
("arthik_salahkar","endowment policy bonus kab milega maturity pe"),
("arthik_salahkar","IRDA complaint kaise karein insurance company pe"),
# Investment / savings
("arthik_salahkar","PPF account mein maximum deposit kitna kar sakte"),
("arthik_salahkar","NPS tier 1 tier 2 difference kya hai"),
("arthik_salahkar","mutual fund SIP kab shuru karein beginner"),
("arthik_salahkar","KVP Kisan Vikas Patra double kab hoga"),
("arthik_salahkar","NSC national savings certificate interest rate"),
("arthik_salahkar","senior citizen savings scheme interest quarterly"),
("arthik_salahkar","FD vs recurring deposit kaunsa better hai"),
("arthik_salahkar","RBI bonds 7.75% taxable kab milenge"),
("arthik_salahkar","stock market basics share kaise khareedein"),
("arthik_salahkar","gold bond sovereign SGB invest karna"),
# EPFO / PF
("arthik_salahkar","PF withdrawal online kab process hoga"),
("arthik_salahkar","EPF claim reject hua reason kya hai"),
("arthik_salahkar","UAN activate karna hai EPFO portal se"),
("arthik_salahkar","PF transfer previous company se nahi hua"),
("arthik_salahkar","EPS pension advance kaise niskalein bimari mein"),
# Devanagari
("arthik_salahkar","ओटीपी लेकर बैंक से पैसे निकाल लिए साइबर फ्रॉड"),
("arthik_salahkar","मुद्रा लोन लेना है छोटा व्यवसाय शुरू करने के लिए"),
("arthik_salahkar","यूपीआई से गलत पेमेंट हो गई वापस कैसे आएगी"),
("arthik_salahkar","ऑनलाइन फ्रॉड हुआ पैसा वापस मिलेगा क्या"),
("arthik_salahkar","बैंक अकाउंट फ्रीज हो गया क्या करें"),
("arthik_salahkar","पीएफ विदड्रॉल ऑनलाइन कैसे करें"),
("arthik_salahkar","आयकर रिटर्न भरनी है कैसे भरें"),
("arthik_salahkar","क्रेडिट स्कोर कम है लोन नहीं मिल रहा"),
("arthik_salahkar","किसी ने फोन करके ओटीपी ले लिया एसबीआई एजेंट बताया"),
("arthik_salahkar","पीएम जीवन ज्योति बीमा योजना कैसे लें"),
# English
("arthik_salahkar","cyber fraud OTP stolen money how to get back"),
("arthik_salahkar","mudra loan small business apply online"),
("arthik_salahkar","UPI payment failed money deducted not credited"),
("arthik_salahkar","ITR income tax return how to file online"),
("arthik_salahkar","EPF PF withdrawal online claim procedure"),
("arthik_salahkar","PM Jan Dhan account zero balance insurance"),
("arthik_salahkar","credit score improvement tips CIBIL"),
("arthik_salahkar","phishing scam bank account compromised complaint"),
("arthik_salahkar","PPF account maximum deposit tax benefit"),
("arthik_salahkar","EPFO UAN activation and PF balance check"),
# Bhojpuri
("arthik_salahkar","mera OTP le ke paisa nikal gaye hai kya karein"),
("arthik_salahkar","loan ke liye apply karna ba kaise karen"),
("arthik_salahkar","upi transfer galat ho gail hai paisa wapas aai"),
("arthik_salahkar","khata mein ek nahin padha fraud ho gaya"),
("arthik_salahkar","PF ke paise nikalne hai kaise niklen"),
# Mixed Hinglish
("arthik_salahkar","cyber fraud OTP steal hua 15000 gone kya karein 1930"),
("arthik_salahkar","mudra loan apply karna hai chai shop ke liye PMMY"),
("arthik_salahkar","UPI wrong transfer reversal kaise karein bank se"),
("arthik_salahkar","ITR 2024-25 last date kab hai file karna hai"),
("arthik_salahkar","PF transfer naya employer mein karna hai UAN"),
("arthik_salahkar","PMJJBY accident insurance 2 lakh premium year"),
("arthik_salahkar","SIP mutual fund invest karna hai monthly 500"),
("arthik_salahkar","credit card payment miss ho gayi penal charges"),
("arthik_salahkar","bank se personal loan 5 lakh kaise milega"),
("arthik_salahkar","FASTag recharge nahi ho raha toll pe issue"),

# ═══════════════════════════ VIDHI_SAHAYAK — 300 ════════════════════════════
# FIR / Police
("vidhi_sahayak","police ne FIR likhne se mana kar diya kya karein"),
("vidhi_sahayak","thane mein report nahi likh raha mujhe kya adhikar hai"),
("vidhi_sahayak","zero FIR kahan darj karein apne ilaake se door"),
("vidhi_sahayak","cybercrime FIR kaise likhwayein local thane mein"),
("vidhi_sahayak","mahila police station mein complaint karna hai"),
("vidhi_sahayak","police ne maara pita gaadi ka chakkar hai"),
("vidhi_sahayak","police mein shikayat ke baad koi action nahi"),
("vidhi_sahayak","arrest ke baad bail kaise milti hai magistrate se"),
("vidhi_sahayak","anticipatory bail kya hai kaise milti hai"),
("vidhi_sahayak","bails condition kya kya hoti hai court mein"),
("vidhi_sahayak","SP office mein shikayat dena hai police ke khilaf"),
("vidhi_sahayak","NHRC mein police atrocity ki complaint kaise"),
("vidhi_sahayak","crime against women special cell complaint"),
("vidhi_sahayak","false case mein girftari hua bail chahiye"),
("vidhi_sahayak","chargesheet kya hota hai kab file hota hai"),
# Land / property legal
("vidhi_sahayak","zameen par kisi ne kabza kar liya vakeel chahiye"),
("vidhi_sahayak","benami property kya hai complaint kahan karein"),
("vidhi_sahayak","sale deed me fraud hua registry galat thi"),
("vidhi_sahayak","mutation nahi hua zameen ka aur kabza gaya"),
("vidhi_sahayak","tenant nahi nikl raha rent agreement expire hua"),
("vidhi_sahayak","landlord ne bijli paani band kar diya tenant hun"),
("vidhi_sahayak","partition of ancestral property among siblings"),
("vidhi_sahayak","will testament ke baad property dispute brothers mein"),
("vidhi_sahayak","power of attorney fraud ho gaya property ka"),
("vidhi_sahayak","khet ki registry fraud se ho gayi cancellation"),
("vidhi_sahayak","housing society dispute committee nahi sun rahi"),
("vidhi_sahayak","plot ka record galat hai patwari ne kiya"),
("vidhi_sahayak","varasat certificate ke baad bhi jameen nahi mili"),
("vidhi_sahayak","Dalit land rights ke liye Bhoodan pattas"),
# Women / domestic violence
("vidhi_sahayak","pati maar raha hai ghar mein kya adhikar hain mujhe"),
("vidhi_sahayak","domestic violence act mein protection order kaise"),
("vidhi_sahayak","dowry demand ho rahi hai kya karna chahiye"),
("vidhi_sahayak","498A case kaise file karein"),
("vidhi_sahayak","protection officer se kaise milein DV case mein"),
("vidhi_sahayak","mahila cell police mein complaint karna domestic violence"),
("vidhi_sahayak","divorce petition kaise dakhil karein without advocate"),
("vidhi_sahayak","maintenance alimony for wife kab milta hai court se"),
("vidhi_sahayak","child custody during divorce proceedings kaise"),
("vidhi_sahayak","workplace sexual harassment complaint ICC me"),
("vidhi_sahayak","eve teasing ke liye FIR kaise karein"),
("vidhi_sahayak","stalking ke liye court order kaise milega"),
("vidhi_sahayak","matrimonial fraud fraud marriage registration cancel"),
("vidhi_sahayak","POCSO case mein minor child ka bayan kaise deta"),
# Consumer rights
("vidhi_sahayak","consumer court mein complaint kaise karein online"),
("vidhi_sahayak","product defect hai manufacturer ne nahi suna"),
("vidhi_sahayak","service deficiency insurance company ke khilaf"),
("vidhi_sahayak","hospital mein negligence hua complaint kahan"),
("vidhi_sahayak","bank se bereaved family ka account mein problem"),
("vidhi_sahayak","real estate RERA complaint builder ke khilaf"),
("vidhi_sahayak","builder ne flat delay kiya interest compensation"),
("vidhi_sahayak","unfair trade practice complaint CCPA kahaan"),
("vidhi_sahayak","ecommerce return policy violation complaint"),
("vidhi_sahayak","misleading advertisement ke liye shikayat kahan"),
# Labour rights
("vidhi_sahayak","job se nikaala bina notice ke kya legal help"),
("vidhi_sahayak","pay nahi diya employer ne 3 mahine se complaint"),
("vidhi_sahayak","labour court mein case kaise dakhil karein"),
("vidhi_sahayak","provident fund nahi diya employer ne complaint"),
("vidhi_sahayak","factory act mein overtime payment rule kya hai"),
("vidhi_sahayak","minimum wage se kam de raha hai employer kya karein"),
("vidhi_sahayak","trade union join karne pe harassment ho rahi"),
("vidhi_sahayak","gratuity nahi di company ne 5 saal bad"),
("vidhi_sahayak","ESIC accident compensation claim karna hai"),
("vidhi_sahayak","contract worker rights kya hain permanent ke muqable"),
# Free legal aid
("vidhi_sahayak","NALSA se muft kanuni madad kaise milegi"),
("vidhi_sahayak","state legal services authority mein apply karna"),
("vidhi_sahayak","lok adalat mein settlement kaise hogi"),
("vidhi_sahayak","legal aid clinic nearest kahan hai"),
("vidhi_sahayak","district legal services authority DLSA help"),
("vidhi_sahayak","poor aadmi ko lawyer free milega kaise"),
("vidhi_sahayak","mediation center mein case refer karna hai"),
("vidhi_sahayak","nyaya mitra se help kaise milegi rural area"),
("vidhi_sahayak","free advice from high court legal aid committee"),
("vidhi_sahayak","NALSA toll free number kya hai 15100"),
# Criminal / other
("vidhi_sahayak","bail bond kaun bharta hai court mein"),
("vidhi_sahayak","challan kya hai criminal procedure mein"),
("vidhi_sahayak","anticipatory bail SC HC kaun deta hai"),
("vidhi_sahayak","juvenile justice board mein case child ke liye"),
("vidhi_sahayak","good conduct certificate police se kaise"),
("vidhi_sahayak","cyber stalking complaint kahan darj karein"),
("vidhi_sahayak","SC ST atrocity act mein case kaise darj karein"),
("vidhi_sahayak","election fraud complaint ECI mein karne ka process"),
("vidhi_sahayak","passport ke liye police verification stuck hai"),
("vidhi_sahayak","RTI denied hone par appeal kahan karein"),
# Devanagari
("vidhi_sahayak","पुलिस एफआईआर दर्ज करने से मना कर रही है"),
("vidhi_sahayak","जमीन पर किसी ने कब्जा कर लिया वकील चाहिए"),
("vidhi_sahayak","घरेलू हिंसा हो रही है कानूनी मदद चाहिए"),
("vidhi_sahayak","उपभोक्ता न्यायालय में शिकायत कैसे करें"),
("vidhi_sahayak","एनएएलएसए से मुफ्त कानूनी मदद कैसे मिलेगी"),
("vidhi_sahayak","बिल्डर ने फ्लैट का पजेशन नहीं दिया कानूनी नोटिस"),
("vidhi_sahayak","पुलिस ने बिना वजह गिरफ्तार किया जमानत चाहिए"),
("vidhi_sahayak","दहेज की मांग हो रही है क्या करें"),
("vidhi_sahayak","नौकरी से बिना नोटिस निकाला कानूनी रास्ता"),
("vidhi_sahayak","भूमि विवाद में वकील की जरूरत है"),
# English
("vidhi_sahayak","police refused to file FIR rights of complainant"),
("vidhi_sahayak","land encroachment legal notice procedure"),
("vidhi_sahayak","domestic violence protection order how to get"),
("vidhi_sahayak","consumer court complaint online procedure"),
("vidhi_sahayak","NALSA free legal aid how to apply"),
("vidhi_sahayak","builder RERA complaint flat possession delay"),
("vidhi_sahayak","labour court unpaid wages complaint approach"),
("vidhi_sahayak","anticipatory bail application session court"),
("vidhi_sahayak","SC ST atrocities act complaint how to file"),
("vidhi_sahayak","cyber crime FIR zero FIR nearest station"),
# Bhojpuri
("vidhi_sahayak","police FIR nahi likh rahi hai kahan jaayein"),
("vidhi_sahayak","zameen pe kabza kar liye hai bhai ne vakeel"),
("vidhi_sahayak","darr ka maahol hai ghar mein maar peet hoti"),
("vidhi_sahayak","court mein case dakhil karne ke liye madad"),
("vidhi_sahayak","muft vakeel kahan milenge garib ko"),
# Mixed Hinglish
("vidhi_sahayak","police FIR refuse kar rahi hai what should I do legally"),
("vidhi_sahayak","zero FIR file karna hai cyber crime case mein"),
("vidhi_sahayak","RERA complaint builder ke khilaf online kaise file"),
("vidhi_sahayak","domestic violence DV act 2005 protection order"),
("vidhi_sahayak","consumer complaint district forum online apply"),
("vidhi_sahayak","land dispute legal notice send karna hai"),
("vidhi_sahayak","labour court wages nahi mile complaint procedure"),
("vidhi_sahayak","NALSA legal aid free lawyer kaise milega poor"),
("vidhi_sahayak","bail application magistrate court kaise file"),
("vidhi_sahayak","SC ST atrocity act FIR kaise likhwayein police se"),
]

# ─────────────────────────────────────────────────────────────────────────────
# READ existing train.py, APPEND new DATA, WRITE BACK
# ─────────────────────────────────────────────────────────────────────────────
train_path = os.path.join(os.path.dirname(__file__), 'train.py')
content = open(train_path, encoding='utf-8').read()

# Find closing ] of DATA block
insert_idx = content.rfind('\n]\n\n#')
assert insert_idx != -1, "Could not find end of DATA block"

# Build insertion string
lines = []
lines.append('\n\n# ═══════════════ EXPANDED DATA — 1500 ADDITIONAL EXAMPLES ═══════════════')
for label, text in NEW_DATA:
    lines.append(f'("{label}","{text}"),')

insert_str = '\n'.join(lines)
new_content = content[:insert_idx] + insert_str + content[insert_idx:]

open(train_path, 'w', encoding='utf-8').write(new_content)

# Stats
import re
all_labels = re.findall(r'\("([a-z_]+)","', new_content)
from collections import Counter
dist = Counter(all_labels)
print(f"Done! Total examples: {len(all_labels)}")
for k,v in sorted(dist.items()):
    print(f"  {k}: {v}")
print(f"New examples added: {len(NEW_DATA)}")
