'use client';

import { useEffect, useState } from 'react';
import { getHotspots, getTrendInsights, getPredictions, getAllTrustScores, getAllClusters } from '@/lib/intelligence';
import { useTranslation } from '@/lib/i18n/useTranslation';

type TwinWarning = {
  id: string;
  title: string;
  zone: string;
  category: string;
  severity: 'critical' | 'high' | 'medium';
  riskScore: number;
  confidence: number;
  eta: string;
  reason: string;
  recommendedAction: string;
  citizenNudge: string;
};

type CivicTwinGraphResponse = {
  meta: {
    model: string;
    source: 'cosmos' | 'simulated';
  };
  earlyWarnings: TwinWarning[];
  copilotHighlights: Array<{
    title: string;
    body: string;
    impact: string;
  }>;
  citizenAssistant: {
    style: 'subtle';
    nudges: string[];
  };
};

export default function CivicDigitalTwin() {
  const { t } = useTranslation();
  const [notifiedDepts, setNotifiedDepts] = useState<Set<number>>(new Set());
  const [broadcastsSent, setBroadcastsSent] = useState<Set<number>>(new Set());
  const [copilotDrafts, setCopilotDrafts] = useState<Set<string>>(new Set());
  const [copilotDraftTexts, setCopilotDraftTexts] = useState<Record<string, string>>({});
  const [generatingDrafts, setGeneratingDrafts] = useState<Set<string>>(new Set());
  const [copiedDrafts, setCopiedDrafts] = useState<Set<string>>(new Set());
  const [graphData, setGraphData] = useState<CivicTwinGraphResponse | null>(null);
  const [graphLoading, setGraphLoading] = useState(true);

  const handleNotifyDept = (idx: number) => {
    setNotifiedDepts(prev => new Set(prev).add(idx));
  };

  const handleBroadcast = (idx: number) => {
    setBroadcastsSent(prev => new Set(prev).add(idx));
  };

  const buildCopilotDraft = (warning: TwinWarning): string => {
    return [
      `Subject: URGENT PREVENTIVE ACTION - ${warning.title}`,
      `Zone: ${warning.zone} | Category: ${warning.category}`,
      `Risk Score: ${warning.riskScore} | Confidence: ${warning.confidence}% | ETA: ${warning.eta}`,
      '',
      'Situation Summary:',
      warning.reason,
      '',
      'Recommended Immediate Action:',
      warning.recommendedAction,
      '',
      'Citizen Communication Nudge:',
      warning.citizenNudge,
      '',
      'Requested Response Window: 2 hours',
      'Owner: Ward operations + utility field unit',
      'Generated by Civic Twin Copilot',
    ].join('\n');
  };

  const handleCopilotDraft = (warning: TwinWarning) => {
    if (generatingDrafts.has(warning.id)) return;

    setGeneratingDrafts((prev) => new Set(prev).add(warning.id));
    window.setTimeout(() => {
      const draft = buildCopilotDraft(warning);
      setCopilotDraftTexts((prev) => ({ ...prev, [warning.id]: draft }));
      setCopilotDrafts((prev) => new Set(prev).add(warning.id));
      setGeneratingDrafts((prev) => {
        const next = new Set(prev);
        next.delete(warning.id);
        return next;
      });
    }, 350);
  };

  const handleCopyDraft = async (warningId: string) => {
    const draft = copilotDraftTexts[warningId];
    if (!draft) return;

    try {
      await navigator.clipboard.writeText(draft);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = draft;
      textarea.style.position = 'fixed';
      textarea.style.left = '-9999px';
      document.body.appendChild(textarea);
      textarea.focus();
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    }

    setCopiedDrafts((prev) => new Set(prev).add(warningId));
    window.setTimeout(() => {
      setCopiedDrafts((prev) => {
        const next = new Set(prev);
        next.delete(warningId);
        return next;
      });
    }, 1800);
  };

  useEffect(() => {
    let mounted = true;
    const controller = new AbortController();

    const loadTwinGraph = async () => {
      try {
        const response = await fetch('/api/backend/civic-twin-graph?topK=3', { signal: controller.signal });
        if (!response.ok) {
          throw new Error('Failed to load civic twin graph');
        }

        const data = (await response.json()) as CivicTwinGraphResponse;
        if (mounted) {
          setGraphData(data);
        }
      } catch {
        if (mounted) {
          setGraphData(null);
        }
      } finally {
        if (mounted) {
          setGraphLoading(false);
        }
      }
    };

    loadTwinGraph();

    return () => {
      mounted = false;
      controller.abort();
    };
  }, []);

  const hotspots = getHotspots();
  const trends = getTrendInsights();
  const predictions = getPredictions();
  const trustScores = getAllTrustScores();
  const clusters = getAllClusters();
  const earlyWarnings = graphData?.earlyWarnings || [];
  const copilotHighlights = graphData?.copilotHighlights || [];
  const subtleNudge = graphData?.citizenAssistant?.nudges?.[0];

  return (
    <div className="flex flex-col h-full text-slate-900 dark:text-white overflow-y-auto pb-6 no-scrollbar">
      <div className="p-4 space-y-4">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-sm font-black uppercase tracking-wider flex items-center gap-1.5">
              <span className="material-symbols-outlined text-base text-[#8B5CF6]">hub</span>
              {t('civicDigitalTwin', 'Civic Digital Twin')}
            </h3>
            <p className="text-[10px] text-slate-500 dark:text-gray-400 mt-0.5">{t('aiPatternDetectionAndPredictions', 'AI-powered pattern detection & predictions')}</p>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-[9px] font-bold text-[#8B5CF6] bg-[#8B5CF6]/10 px-2 py-1 rounded-full">AI-POWERED</span>
            <span className="text-[9px] font-bold text-green-500 flex items-center gap-1 bg-green-500/10 px-2 py-1 rounded-full">
              <span className="w-1.5 h-1.5 bg-green-500 rounded-full animate-pulse" /> {t('live', 'LIVE')}
            </span>
          </div>
        </div>

        {/* ═══ HOTSPOT MAP ═══ */}
        <div className="bg-white dark:bg-white/[0.03] border border-black/5 dark:border-white/5 rounded-2xl p-4 shadow-sm dark:shadow-none">
          <h4 className="text-[10px] font-bold text-slate-500 dark:text-gray-400 uppercase tracking-widest mb-3 flex items-center gap-1.5">
            <span className="material-symbols-outlined text-[14px] text-red-400">location_on</span>
            {t('issueHotspots', 'Issue Hotspots')}
          </h4>
          <div className="space-y-2">
            {hotspots.map((h, i) => (
              <div key={i} className={`flex items-center gap-3 p-3 rounded-xl border transition-all ${
                h.severity === 'critical' ? 'bg-red-500/5 border-red-500/20' :
                h.severity === 'high' ? 'bg-orange-500/5 border-orange-500/20' :
                'bg-amber-500/5 border-amber-500/20'
              }`}>
                <div className="flex flex-col items-center shrink-0">
                  <span className={`text-lg font-black ${
                    h.severity === 'critical' ? 'text-red-500' : h.severity === 'high' ? 'text-orange-500' : 'text-amber-500'
                  }`}>{h.count}</span>
                  <span className="text-[7px] text-slate-400 dark:text-gray-500 uppercase">{t('cases', 'cases')}</span>
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-[11px] font-bold">{t(h.category, h.category)}</p>
                  <p className="text-[9px] text-slate-500 dark:text-gray-400">{t(h.location, h.location)} · {t(h.ward, h.ward)}</p>
                </div>
                <div className="text-right shrink-0">
                  <span className={`text-[8px] font-bold px-1.5 py-0.5 rounded ${
                    h.trend === 'rising' ? 'text-red-500 bg-red-500/10' :
                    h.trend === 'declining' ? 'text-green-500 bg-green-500/10' :
                    'text-slate-500 dark:text-gray-400 bg-black/5 dark:bg-white/5'
                  }`}>
                    {h.trend === 'rising' ? t('risingTrend', '↑ Rising') : h.trend === 'declining' ? t('decliningTrend', '↓ Declining') : t('stableTrend', '→ Stable')}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* ═══ TREND INSIGHTS ═══ */}
        <div className="bg-white dark:bg-white/[0.03] border border-black/5 dark:border-white/5 rounded-2xl p-4 shadow-sm dark:shadow-none">
          <h4 className="text-[10px] font-bold text-slate-500 dark:text-gray-400 uppercase tracking-widest mb-3 flex items-center gap-1.5">
            <span className="material-symbols-outlined text-[14px] text-[#3B82F6]">trending_up</span>
            {t('trendAnalysis', 'Trend Analysis')}
          </h4>
          <div className="space-y-3">
            {trends.map((trend, i) => (
              <div key={i} className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-xl flex items-center justify-center shrink-0" style={{ backgroundColor: trend.color + '15' }}>
                  <span className="material-symbols-outlined text-[16px]" style={{ color: trend.color }}>{trend.icon}</span>
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-0.5">
                    <span className="text-[11px] font-bold">{t(trend.category, trend.category)}</span>
                    <span className={`text-[9px] font-black px-1.5 py-0.5 rounded ${
                      trend.direction === 'up' ? 'text-red-500 bg-red-500/10' :
                      trend.direction === 'down' ? 'text-green-500 bg-green-500/10' :
                      'text-slate-500 bg-black/5 dark:bg-white/5'
                    }`}>
                      {trend.direction === 'up' ? `↑ ${trend.change}%` : trend.direction === 'down' ? `↓ ${Math.abs(trend.change)}%` : `→ ${trend.change}%`}
                    </span>
                  </div>
                  <p className="text-[9px] text-slate-500 dark:text-gray-400 leading-snug">{t(trend.description, trend.description)}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* ═══ AI EARLY WARNING PREDICTOR ═══ */}
        <div className="bg-gradient-to-br from-red-500/5 to-orange-500/10 border border-red-500/15 rounded-2xl p-4">
          <h4 className="text-[10px] font-bold text-red-500 uppercase tracking-widest mb-3 flex items-center gap-1.5">
            <span className="material-symbols-outlined text-[14px]">crisis_alert</span>
            AI-Powered Early Warning Predictor
            <span className="ml-auto text-[8px] font-bold text-slate-400 dark:text-gray-500 bg-black/5 dark:bg-white/5 px-1.5 py-0.5 rounded">
              {graphLoading ? 'Syncing...' : graphData?.meta.model || 'Civic Twin Graph'}
            </span>
          </h4>

          <div className="space-y-2.5">
            {earlyWarnings.length > 0 ? earlyWarnings.map((warning) => (
              <div key={warning.id} className="bg-white/70 dark:bg-white/[0.03] rounded-xl p-3 border border-black/5 dark:border-white/5">
                <div className="flex items-start justify-between gap-3 mb-1.5">
                  <div className="min-w-0 flex-1">
                    <p className="text-[11px] font-bold leading-tight">{warning.title}</p>
                    <p className="text-[9px] text-slate-500 dark:text-gray-400">Zone {warning.zone} · {warning.category}</p>
                  </div>
                  <div className="text-right shrink-0">
                    <p className="text-lg font-black text-red-500">{warning.riskScore}</p>
                    <p className="text-[8px] text-slate-400 dark:text-gray-500">risk score</p>
                  </div>
                </div>

                <div className="flex items-center gap-2 mb-2">
                  <span className={`text-[8px] font-bold px-1.5 py-0.5 rounded ${
                    warning.severity === 'critical' ? 'text-red-500 bg-red-500/10' :
                    warning.severity === 'high' ? 'text-orange-500 bg-orange-500/10' :
                    'text-amber-500 bg-amber-500/10'
                  }`}>
                    {warning.severity.toUpperCase()}
                  </span>
                  <span className="text-[8px] font-bold text-[#8B5CF6] bg-[#8B5CF6]/10 px-1.5 py-0.5 rounded">AI confidence {warning.confidence}%</span>
                  <span className="text-[8px] text-slate-500 dark:text-gray-400">ETA {warning.eta}</span>
                </div>

                <p className="text-[9px] text-slate-500 dark:text-gray-400 leading-snug mb-1">{warning.reason}</p>
                <p className="text-[9px] text-[#8B5CF6] dark:text-[#A78BFA] leading-snug mb-2">{warning.recommendedAction}</p>

                <div className="flex items-center justify-between border-t border-black/5 dark:border-white/5 pt-2 mt-2 gap-2">
                  <button
                    onClick={() => handleCopilotDraft(warning)}
                    disabled={generatingDrafts.has(warning.id)}
                    className={`flex-1 flex items-center justify-center gap-1.5 py-1.5 rounded-lg text-[9px] font-bold transition-all ${
                      generatingDrafts.has(warning.id)
                        ? 'bg-[#8B5CF6]/10 text-[#8B5CF6] opacity-80 cursor-wait'
                        : 'bg-[#8B5CF6]/10 text-[#8B5CF6] hover:bg-[#8B5CF6]/20'
                    }`}
                  >
                    <span className="material-symbols-outlined text-[12px]">{generatingDrafts.has(warning.id) ? 'hourglass_top' : 'auto_awesome'}</span>
                    {generatingDrafts.has(warning.id) ? 'Generating Draft...' : 'Generate AI Copilot Draft'}
                  </button>
                </div>

                {copilotDrafts.has(warning.id) && copilotDraftTexts[warning.id] && (
                  <div className="mt-2 rounded-lg border border-[#8B5CF6]/20 bg-[#8B5CF6]/5 p-2.5">
                    <div className="flex items-center justify-between gap-2 mb-1.5">
                      <p className="text-[9px] font-black uppercase tracking-wider text-[#8B5CF6]">Copilot Draft Ready</p>
                      <button
                        onClick={() => handleCopyDraft(warning.id)}
                        className="text-[8px] font-bold px-2 py-1 rounded-full border border-[#8B5CF6]/30 text-[#8B5CF6] bg-white/70 dark:bg-white/[0.04] hover:bg-[#8B5CF6]/10"
                      >
                        {copiedDrafts.has(warning.id) ? 'Copied' : 'Copy Draft'}
                      </button>
                    </div>
                    <p className="text-[9px] text-slate-600 dark:text-gray-300 whitespace-pre-wrap leading-relaxed">
                      {copilotDraftTexts[warning.id]}
                    </p>
                  </div>
                )}
              </div>
            )) : (
              <div className="text-[9px] text-slate-500 dark:text-gray-400 bg-white/70 dark:bg-white/[0.03] rounded-xl p-3 border border-black/5 dark:border-white/5">
                {graphLoading ? 'Building civic graph signals...' : 'No active warning signals right now.'}
              </div>
            )}
          </div>

          {subtleNudge && (
            <div className="mt-2 text-[8px] text-slate-500 dark:text-gray-400 border-t border-black/5 dark:border-white/5 pt-2">
              Citizen assistant (subtle): {subtleNudge}
            </div>
          )}
        </div>

        {/* ═══ AI PREDICTIONS ═══ */}
        <div className="bg-gradient-to-br from-[#8B5CF6]/5 to-[#8B5CF6]/10 border border-[#8B5CF6]/15 rounded-2xl p-4">
          <h4 className="text-[10px] font-bold text-[#8B5CF6] uppercase tracking-widest mb-3 flex items-center gap-1.5">
            <span className="material-symbols-outlined text-[14px]">psychology</span>
            AI-Powered Resolution Copilot Signals
            <span className="ml-auto text-[8px] font-bold text-slate-400 dark:text-gray-500 bg-black/5 dark:bg-white/5 px-1.5 py-0.5 rounded">{graphData?.meta.source === 'cosmos' ? 'Cosmos-backed' : t('simulated', 'Simulated')}</span>
          </h4>

          {copilotHighlights.length > 0 && (
            <div className="space-y-1.5 mb-2.5">
              {copilotHighlights.slice(0, 2).map((item, i) => (
                <div key={i} className="text-[9px] rounded-lg px-2.5 py-2 bg-white/60 dark:bg-white/[0.03] border border-black/5 dark:border-white/5">
                  <p className="font-bold text-[#8B5CF6]">{item.title}</p>
                  <p className="text-slate-500 dark:text-gray-400 leading-snug">{item.body}</p>
                </div>
              ))}
            </div>
          )}

          <div className="space-y-2.5">
            {predictions.map((p, i) => (
              <div key={i} className="bg-white/60 dark:bg-white/[0.03] rounded-xl p-3 border border-black/5 dark:border-white/5">
                <div className="flex items-center gap-2.5 mb-1.5">
                  <span className="material-symbols-outlined text-lg" style={{ color: p.color }}>{p.icon}</span>
                  <div className="flex-1 min-w-0">
                    <p className="text-[11px] font-bold">{t(p.category, p.category)}</p>
                    <p className="text-[9px] text-slate-500 dark:text-gray-400">{t(p.area, p.area)}</p>
                  </div>
                  <div className="text-right shrink-0">
                    <p className="text-lg font-black" style={{ color: p.color }}>{p.probability}%</p>
                    <p className="text-[8px] text-slate-400 dark:text-gray-500">{t('likelihood', 'likelihood')}</p>
                  </div>
                </div>
                <p className="text-[9px] text-slate-500 dark:text-gray-400 italic leading-snug mb-2">⏱ {t(p.timeframe, p.timeframe)} — {t(p.reasoning, p.reasoning)}</p>
                
                {/* Actions */}
                <div className="flex items-center justify-between border-t border-black/5 dark:border-white/5 pt-2 mt-2 gap-2">
                   <button 
                     onClick={() => handleNotifyDept(i)}
                     disabled={notifiedDepts.has(i)}
                     className={`flex-1 flex items-center justify-center gap-1.5 py-1.5 rounded-lg text-[9px] font-bold transition-all ${
                       notifiedDepts.has(i) 
                         ? 'bg-blue-500/10 text-blue-500 opacity-80 cursor-not-allowed'
                         : 'bg-black/5 dark:bg-white/5 text-slate-600 dark:text-gray-300 hover:bg-black/10 dark:hover:bg-white/10'
                     }`}>
                     <span className="material-symbols-outlined text-[12px]">{notifiedDepts.has(i) ? 'check_circle' : 'forward_to_inbox'}</span>
                     {notifiedDepts.has(i) ? 'Notified' : 'Inform Dept'}
                   </button>

                   <button 
                     onClick={() => handleBroadcast(i)}
                     disabled={broadcastsSent.has(i)}
                     className={`flex-1 flex items-center justify-center gap-1.5 py-1.5 rounded-lg text-[9px] font-bold transition-all ${
                       broadcastsSent.has(i) 
                         ? 'bg-amber-500/10 text-amber-500 opacity-80 cursor-not-allowed'
                         : 'bg-amber-500/10 text-amber-600 dark:text-amber-500 hover:bg-amber-500/20'
                     }`}>
                     <span className="material-symbols-outlined text-[12px]">{broadcastsSent.has(i) ? 'campaign' : 'podcasts'}</span>
                     {broadcastsSent.has(i) ? 'Broadcast Sent' : 'Broadcast Warn'}
                   </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* ═══ COLLECTIVE ACTION CLUSTERS ═══ */}
        <div className="bg-white dark:bg-white/[0.03] border border-black/5 dark:border-white/5 rounded-2xl p-4 shadow-sm dark:shadow-none">
          <h4 className="text-[10px] font-bold text-slate-500 dark:text-gray-400 uppercase tracking-widest mb-3 flex items-center gap-1.5">
            <span className="material-symbols-outlined text-[14px] text-[#FF9933]">group_work</span>
            {t('activeCollectiveActions', 'Active Collective Actions')}
          </h4>
          <div className="space-y-2">
            {clusters.map((c, i) => (
              <div key={i} className={`flex items-center gap-3 p-3 rounded-xl border ${
                c.status === 'amplified' ? 'bg-[#138808]/5 border-[#138808]/20' : 'bg-black/[0.02] dark:bg-white/[0.02] border-black/5 dark:border-white/5'
              }`}>
                <div className="text-center shrink-0">
                  <p className="text-lg font-black text-[#FF9933]">{c.participantCount}</p>
                  <p className="text-[7px] text-slate-400 dark:text-gray-500 uppercase">{t('citizens', 'citizens')}</p>
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-[11px] font-bold capitalize">{t('categoryIssues', '{category} Issues').replace('{category}', t(c.category, c.category))}</p>
                  <p className="text-[9px] text-slate-500 dark:text-gray-400">Zone {c.location} · {c.clusterId}</p>
                </div>
                <span className={`text-[8px] font-bold px-1.5 py-0.5 rounded ${
                  c.status === 'amplified' ? 'text-[#138808] bg-[#138808]/10' : 'text-amber-500 bg-amber-500/10'
                }`}>
                  {c.status === 'amplified' ? t('amplified', '🔊 Amplified') : t('active', '📢 Active')}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* ═══ DEPARTMENT TRUST SCORES ═══ */}
        <div className="bg-white dark:bg-white/[0.03] border border-black/5 dark:border-white/5 rounded-2xl p-4 shadow-sm dark:shadow-none">
          <h4 className="text-[10px] font-bold text-slate-500 dark:text-gray-400 uppercase tracking-widest mb-3 flex items-center gap-1.5">
            <span className="material-symbols-outlined text-[14px] text-[#138808]">verified</span>
            {t('departmentTrustScores', 'Department Trust Scores')}
          </h4>
          <div className="space-y-2">
            {trustScores.map((ts, i) => (
              <div key={i} className="flex items-center gap-3 p-2.5 rounded-lg hover:bg-black/[0.02] dark:hover:bg-white/[0.02] transition-colors">
                <div className="w-10 text-center shrink-0">
                  <p className="text-base font-black" style={{ color: ts.color }}>{ts.score}</p>
                  <p className="text-[7px] text-slate-400 dark:text-gray-500">/ 10</p>
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-1.5 mb-0.5">
                    <span className="text-[11px] font-bold">{t(ts.department, ts.department)}</span>
                    <span className="text-[8px] font-bold px-1.5 py-0.5 rounded" style={{ color: ts.color, backgroundColor: ts.color + '15' }}>{ts.label}</span>
                  </div>
                  <div className="flex gap-3 text-[8px] text-slate-400 dark:text-gray-500">
                    <span>⏱ {ts.avgResolutionDays}d avg</span>
                    <span>📋 {ts.backlog} pending</span>
                    <span>⭐ {ts.satisfaction}/5</span>
                  </div>
                </div>
                <span className={`material-symbols-outlined text-sm ${
                  ts.trend === 'up' ? 'text-green-500' : ts.trend === 'down' ? 'text-red-500' : 'text-slate-400'
                }`}>
                  {ts.trend === 'up' ? 'trending_up' : ts.trend === 'down' ? 'trending_down' : 'trending_flat'}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
